#!/usr/bin/env bash

staged_files=$(git diff --name-only --cached)
declare -i errors=0

for file in $staged_files
do
    if [ -f "$file" ]
    then
        base="$(basename "${file}")"
        ext="${base##*.}"
        if [ "${ext}" == "${base}" ]
        then
            tmpfile=$(mktemp "/tmp/${USER}-format-XXXXXX")
        else
            tmpfile=$(mktemp "/tmp/${USER}-format-XXXXXX.${ext}")
        fi

        git show :"${file}" > "${tmpfile}"

        ./format-sources.sh "${tmpfile}"
        if ! git diff --no-index --quiet -- "${tmpfile}" <(git show :"${file}")
        then
            echo "Detected formatting issue in '${file}'"
            ((errors++))
        fi

        rm -f "${tmpfile}"
    fi
done

exec 1>&2

if (( errors > 0))
then
    echo "Please run 'format-sources.sh' manually!"
    echo "You can ignore this pre-commit hook using 'git commit --no-verify'"
    exit 1
fi
