#!/bin/bash

staged_files=$(git diff --name-only --cached)

if command -v gsed &> /dev/null
then
    sed_command=gsed
else
    sed_command=sed
fi

errors=""

for file in $staged_files
do
    if [ -f "$file" ]
    then
        filename=$(basename -- "$file")
        extension="${filename##*.}"
        if [ "$extension" == "h" ] || [ "$extension" == "c" ] || [ "$extension" == "cc" ]
        then
            format_result=$(git clang-format -q --style=file $file)
        else
            format_result=$($sed_command --in-place -e 's/[[:space:]]*$//' -e '${/^$/d;}' $file)
        fi
        errors="$errors$format_result"
        git add $file
    fi
done

exec 1>&2

if [ "$errors" != "" ]
then
    echo "Automatic format error:"
    echo $errors
    echo "Please run clang-format manually!"
    exit 1
fi
