MODULE OM_CORE_MOD

  ! Data kind
  USE :: OM_DATA_KIND_MOD, ONLY: JPEB_K
  USE :: OM_DATA_KIND_MOD, ONLY: JPIT_K
  USE :: OM_DATA_KIND_MOD, ONLY: JPIS_K
  USE :: OM_DATA_KIND_MOD, ONLY: JPIM_K
  USE :: OM_DATA_KIND_MOD, ONLY: JPIB_K
  USE :: OM_DATA_KIND_MOD, ONLY: JPTR_K
  USE :: OM_DATA_KIND_MOD, ONLY: JPIA_K
  USE :: OM_DATA_KIND_MOD, ONLY: JPRT_K
  USE :: OM_DATA_KIND_MOD, ONLY: JPRS_K
  USE :: OM_DATA_KIND_MOD, ONLY: JPRM_K
  USE :: OM_DATA_KIND_MOD, ONLY: JPRB_K
  USE :: OM_DATA_KIND_MOD, ONLY: JPRD_K
  USE :: OM_DATA_KIND_MOD, ONLY: CHECK_REAL_KIND

  ! Datatypes
  USE :: OM_DATA_TYPES_MOD, ONLY: PROC_TOPO_T
  USE :: OM_DATA_TYPES_MOD, ONLY: MODEL_PAR_T
  USE :: OM_DATA_TYPES_MOD, ONLY: MODEL_PAR_SERIAL_T
  USE :: OM_DATA_TYPES_MOD, ONLY: SIM_PAR_T
  USE :: OM_DATA_TYPES_MOD, ONLY: SAT_PAR_T
  USE :: OM_DATA_TYPES_MOD, ONLY: GEO_PAR_T
  USE :: OM_DATA_TYPES_MOD, ONLY: ATM_PAR_T
  USE :: OM_DATA_TYPES_MOD, ONLY: WAM_PAR_T
  USE :: OM_DATA_TYPES_MOD, ONLY: OM_BASE_MSG_A
  USE :: OM_DATA_TYPES_MOD, ONLY: OM_ATM_MSG_T
  USE :: OM_DATA_TYPES_MOD, ONLY: OM_WAM_MSG_T
  USE :: OM_DATA_TYPES_MOD, ONLY: CURR_TIME_T

  USE :: OM_CONSTANTS_MOD, ONLY: MAX_LINE
  USE :: OM_CONSTANTS_MOD, ONLY: MAX_LINE_LENGTH
  USE :: OM_CONSTANTS_MOD, ONLY: CAPACITY

  ! Enumerators
  USE :: OM_ENUMERATORS_MOD, ONLY: GRIB1_E
  USE :: OM_ENUMERATORS_MOD, ONLY: GRIB2_E
  USE :: OM_ENUMERATORS_MOD, ONLY: MODEL_LEVEL_E
  USE :: OM_ENUMERATORS_MOD, ONLY: PRESSURE_LEVEL_E
  USE :: OM_ENUMERATORS_MOD, ONLY: VORTICITY_LEVEL_E
  USE :: OM_ENUMERATORS_MOD, ONLY: THETA_LEVEL_E
  USE :: OM_ENUMERATORS_MOD, ONLY: SURFACE_E
  USE :: OM_ENUMERATORS_MOD, ONLY: WAVE_INT_E
  USE :: OM_ENUMERATORS_MOD, ONLY: WAVE_SPEC_E
  USE :: OM_ENUMERATORS_MOD, ONLY: ATM_MSG_E
  USE :: OM_ENUMERATORS_MOD, ONLY: WAM_MSG_E
  USE :: OM_ENUMERATORS_MOD, ONLY: VALUES_SP_E
  USE :: OM_ENUMERATORS_MOD, ONLY: VALUES_DP_E
  USE :: OM_ENUMERATORS_MOD, ONLY: REPRES_GRIDDED_E
  USE :: OM_ENUMERATORS_MOD, ONLY: REPRES_SPECTRAL_E
  USE :: OM_ENUMERATORS_MOD, ONLY: TYPE_OF_STATISTICAL_PROCESS_INSTANT_E
  USE :: OM_ENUMERATORS_MOD, ONLY: TYPE_OF_STATISTICAL_PROCESS_AVERAGE_E
  USE :: OM_ENUMERATORS_MOD, ONLY: TYPE_OF_STATISTICAL_PROCESS_ACCUMUL_E
  USE :: OM_ENUMERATORS_MOD, ONLY: TYPE_OF_STATISTICAL_PROCESS_MIN_E
  USE :: OM_ENUMERATORS_MOD, ONLY: TYPE_OF_STATISTICAL_PROCESS_MAX_E
  USE :: OM_ENUMERATORS_MOD, ONLY: TYPE_OF_STATISTICAL_PROCESS_SEVERITY_E
  USE :: OM_ENUMERATORS_MOD, ONLY: TYPE_OF_STATISTICAL_PROCESS_MODE_E
  USE :: OM_ENUMERATORS_MOD, ONLY: TYPE_OF_TIME_RANGE_INSTANT_E
  USE :: OM_ENUMERATORS_MOD, ONLY: TYPE_OF_TIME_RANGE_FROM_STEP0_E
  USE :: OM_ENUMERATORS_MOD, ONLY: TYPE_OF_TIME_RANGE_FROM_LASTPP_E
  USE :: OM_ENUMERATORS_MOD, ONLY: TYPE_OF_TIME_RANGE_FIXED_SIZE_E
  USE :: OM_ENUMERATORS_MOD, ONLY: UNDEF_PARAM_E
  USE :: OM_ENUMERATORS_MOD, ONLY: LEVTYPE_HHL_E
  USE :: OM_ENUMERATORS_MOD, ONLY: LEVTYPE_HPL_E
  USE :: OM_ENUMERATORS_MOD, ONLY: LEVTYPE_HL_E
  USE :: OM_ENUMERATORS_MOD, ONLY: LEVTYPE_ML_E
  USE :: OM_ENUMERATORS_MOD, ONLY: LEVTYPE_O2D_E
  USE :: OM_ENUMERATORS_MOD, ONLY: LEVTYPE_O3D_E
  USE :: OM_ENUMERATORS_MOD, ONLY: LEVTYPE_PL_E
  USE :: OM_ENUMERATORS_MOD, ONLY: LEVTYPE_PT_E
  USE :: OM_ENUMERATORS_MOD, ONLY: LEVTYPE_PV_E
  USE :: OM_ENUMERATORS_MOD, ONLY: LEVTYPE_SFC_E
  USE :: OM_ENUMERATORS_MOD, ONLY: LEVTYPE_SOL_E
  USE :: OM_ENUMERATORS_MOD, ONLY: PACKING_TYPE_GRIB_SIMPLE_E
  USE :: OM_ENUMERATORS_MOD, ONLY: PACKING_TYPE_GRIB_CCSDE_E
  USE :: OM_ENUMERATORS_MOD, ONLY: PACKING_TYPE_GRIB_COMPLEX_E
  USE :: OM_ENUMERATORS_MOD, ONLY: N_REPRES_E
  USE :: OM_ENUMERATORS_MOD, ONLY: N_LEVTYPE_E

  ! Grib info
  USE :: GRIB_INFO_DATA_MOD, ONLY: GRIB_INFO_T
  USE :: GRIB_INFO_DATA_MOD, ONLY: TIME_HISTORY_T
  USE :: GRIB_INFO_DATA_MOD, ONLY: LOOKUP_TABLE
  USE :: GRIB_INFO_DATA_MOD, ONLY: LOOKUP_TABLE_BWD

  ! Debugging utils
  USE :: OM_DEBUG_MOD, ONLY: OM_ABORT
  USE :: OM_DEBUG_MOD, ONLY: OM_CREATE_ERRMSG
  USE :: OM_DEBUG_MOD, ONLY: OM_SET_ABORT_PROCEDURE
  USE :: OM_DEBUG_MOD, ONLY: OM_SET_ERROR_UNIT
  USE :: OM_DEBUG_MOD, ONLY: OM_INIT_DEBUG_VARS
  USE :: OM_DEBUG_MOD, ONLY: OM_SET_CURRENT_MESSAGE_ATM
  USE :: OM_DEBUG_MOD, ONLY: OM_SET_CURRENT_MESSAGE_WAM
  USE :: OM_DEBUG_MOD, ONLY: OM_SET_CURRENT_GRIB_INFO
  USE :: OM_DEBUG_MOD, ONLY: OM_SET_ENCODING_STACK
  USE :: OM_DEBUG_MOD, ONLY: OM_RESET_ENCODING_STACK
  USE :: OM_DEBUG_MOD, ONLY: OM_RESET_ENCODING_INFO

  ! Trace Utils
  USE :: OM_TRACE_MOD, ONLY: TRACER_T
  USE :: OM_TRACE_MOD, ONLY: OM_TRACE_ENTER_PROCEDURE
  USE :: OM_TRACE_MOD, ONLY: OM_TRACE_EXIT_PROCEDURE_ON_SUCCESS
  USE :: OM_TRACE_MOD, ONLY: OM_TRACE_EXIT_PROCEDURE_ON_ERROR
  USE :: OM_TRACE_MOD, ONLY: OM_SET_DR_HOOK

IMPLICIT NONE

! Default visibility of the module
PRIVATE

! Whitelist of public symbols
PUBLIC :: JPEB_K
PUBLIC :: JPIT_K
PUBLIC :: JPIS_K
PUBLIC :: JPIM_K
PUBLIC :: JPIB_K
PUBLIC :: JPTR_K
PUBLIC :: JPIA_K
PUBLIC :: JPRT_K
PUBLIC :: JPRS_K
PUBLIC :: JPRM_K
PUBLIC :: JPRB_K
PUBLIC :: JPRD_K
PUBLIC :: CHECK_REAL_KIND

PUBLIC :: OM_ABORT
PUBLIC :: OM_CREATE_ERRMSG
PUBLIC :: OM_SET_ABORT_PROCEDURE
PUBLIC :: OM_SET_ERROR_UNIT

PUBLIC :: PROC_TOPO_T
PUBLIC :: MODEL_PAR_T
PUBLIC :: MODEL_PAR_SERIAL_T
PUBLIC :: SIM_PAR_T
PUBLIC :: SAT_PAR_T
PUBLIC :: GEO_PAR_T
PUBLIC :: ATM_PAR_T
PUBLIC :: WAM_PAR_T
PUBLIC :: OM_BASE_MSG_A
PUBLIC :: OM_ATM_MSG_T
PUBLIC :: OM_WAM_MSG_T
PUBLIC :: CURR_TIME_T

PUBLIC :: GRIB_INFO_T
PUBLIC :: TIME_HISTORY_T

PUBLIC :: TRACER_T
PUBLIC :: OM_TRACE_ENTER_PROCEDURE
PUBLIC :: OM_TRACE_EXIT_PROCEDURE_ON_SUCCESS
PUBLIC :: OM_TRACE_EXIT_PROCEDURE_ON_ERROR
PUBLIC :: OM_SET_DR_HOOK

PUBLIC :: MAX_LINE
PUBLIC :: MAX_LINE_LENGTH
PUBLIC :: CAPACITY

PUBLIC :: GRIB1_E
PUBLIC :: GRIB2_E
PUBLIC :: MODEL_LEVEL_E
PUBLIC :: PRESSURE_LEVEL_E
PUBLIC :: VORTICITY_LEVEL_E
PUBLIC :: THETA_LEVEL_E
PUBLIC :: SURFACE_E
PUBLIC :: WAVE_INT_E
PUBLIC :: WAVE_SPEC_E
PUBLIC :: ATM_MSG_E
PUBLIC :: WAM_MSG_E
PUBLIC :: VALUES_SP_E
PUBLIC :: VALUES_DP_E
PUBLIC :: REPRES_GRIDDED_E
PUBLIC :: REPRES_SPECTRAL_E
PUBLIC :: TYPE_OF_STATISTICAL_PROCESS_INSTANT_E
PUBLIC :: TYPE_OF_STATISTICAL_PROCESS_AVERAGE_E
PUBLIC :: TYPE_OF_STATISTICAL_PROCESS_ACCUMUL_E
PUBLIC :: TYPE_OF_STATISTICAL_PROCESS_MIN_E
PUBLIC :: TYPE_OF_STATISTICAL_PROCESS_MAX_E
PUBLIC :: TYPE_OF_STATISTICAL_PROCESS_SEVERITY_E
PUBLIC :: TYPE_OF_STATISTICAL_PROCESS_MODE_E
PUBLIC :: TYPE_OF_TIME_RANGE_INSTANT_E
PUBLIC :: TYPE_OF_TIME_RANGE_FROM_STEP0_E
PUBLIC :: TYPE_OF_TIME_RANGE_FROM_LASTPP_E
PUBLIC :: TYPE_OF_TIME_RANGE_FIXED_SIZE_E
PUBLIC :: UNDEF_PARAM_E
PUBLIC :: LEVTYPE_HHL_E
PUBLIC :: LEVTYPE_HPL_E
PUBLIC :: LEVTYPE_HL_E
PUBLIC :: LEVTYPE_ML_E
PUBLIC :: LEVTYPE_O2D_E
PUBLIC :: LEVTYPE_O3D_E
PUBLIC :: LEVTYPE_PL_E
PUBLIC :: LEVTYPE_PT_E
PUBLIC :: LEVTYPE_PV_E
PUBLIC :: LEVTYPE_SFC_E
PUBLIC :: LEVTYPE_SOL_E
PUBLIC :: PACKING_TYPE_GRIB_SIMPLE_E
PUBLIC :: PACKING_TYPE_GRIB_CCSDE_E
PUBLIC :: PACKING_TYPE_GRIB_COMPLEX_E
PUBLIC :: N_LEVTYPE_E
PUBLIC :: N_REPRES_E

PUBLIC :: OM_INIT_DEBUG_VARS
PUBLIC :: OM_SET_CURRENT_MESSAGE_ATM
PUBLIC :: OM_SET_CURRENT_MESSAGE_WAM
PUBLIC :: OM_SET_CURRENT_GRIB_INFO
PUBLIC :: OM_SET_ENCODING_STACK
PUBLIC :: OM_RESET_ENCODING_STACK
PUBLIC :: OM_RESET_ENCODING_INFO


! Shared data
PUBLIC :: LOOKUP_TABLE
PUBLIC :: LOOKUP_TABLE_BWD

END MODULE OM_CORE_MOD
