MODULE OM_DATA_KIND_MOD

IMPLICIT NONE

  ! Default visibility
  PRIVATE

  !
  !     Integer Kinds
  !     -------------
  !
  INTEGER, PARAMETER :: JPEB_K = SELECTED_INT_KIND(12)
  INTEGER, PARAMETER :: JPIT_K = SELECTED_INT_KIND(2)
  INTEGER, PARAMETER :: JPIS_K = SELECTED_INT_KIND(4)
  INTEGER, PARAMETER :: JPIM_K = SELECTED_INT_KIND(9)
  INTEGER, PARAMETER :: JPIB_K = SELECTED_INT_KIND(12)
  INTEGER, PARAMETER :: JPTR_K = SELECTED_REAL_KIND(13,300)

  !Special integer type to be used for sensative adress calculations
  !should be *8 for a machine with 8byte adressing for optimum performance
#ifdef ADDRESS64
  INTEGER, PARAMETER :: JPIA_K = JPIB_K
#else
  INTEGER, PARAMETER :: JPIA_K = JPIM_K
#endif


  !
  !     Real Kinds
  !     ----------
  !
  INTEGER, PARAMETER :: JPRT_K = SELECTED_REAL_KIND(2,1)
  INTEGER, PARAMETER :: JPRS_K = SELECTED_REAL_KIND(4,2)
  INTEGER, PARAMETER :: JPRM_K = SELECTED_REAL_KIND(6,37)
#ifdef PARKIND1_SINGLE
  INTEGER, PARAMETER :: JPRB_K = SELECTED_REAL_KIND(6,37)
#else
  INTEGER, PARAMETER :: JPRB_K = SELECTED_REAL_KIND(13,300)
#endif

  ! Double real for C code and special places requiring
  ! higher precision.
  INTEGER, PARAMETER :: JPRD_K = SELECTED_REAL_KIND(13,300)



  ! Whitelist of public symbols (parameters)
  PUBLIC :: JPEB_K
  PUBLIC :: JPIT_K
  PUBLIC :: JPIS_K
  PUBLIC :: JPIM_K
  PUBLIC :: JPIB_K
  PUBLIC :: JPTR_K
  PUBLIC :: JPIA_K
  PUBLIC :: JPRT_K
  PUBLIC :: JPRS_K
  PUBLIC :: JPRM_K
  PUBLIC :: JPRB_K
  PUBLIC :: JPRD_K


  ! Whitelist of public symbols (procedures)
  PUBLIC :: CHECK_REAL_KIND

CONTAINS

FUNCTION CHECK_REAL_KIND( JPRB ) RESULT(LCHK)
IMPLICIT NONE
INTEGER, INTENT(IN) :: JPRB
LOGICAL :: LCHK

LCHK = (JPRB .EQ. JPRB_K)

RETURN
END FUNCTION CHECK_REAL_KIND

END MODULE OM_DATA_KIND_MOD