MODULE OM_ENUMERATORS_MOD

    ! Symbols imported from other modules within the project.
    USE :: OM_DATA_KIND_MOD, ONLY: JPIB_K

IMPLICIT NONE

  ! Default visibility
  PRIVATE

  ! Enumerators for prefixes
  INTEGER(KIND=JPIB_K), PARAMETER :: MODEL_LEVEL_E=1
  INTEGER(KIND=JPIB_K), PARAMETER :: PRESSURE_LEVEL_E=2
  INTEGER(KIND=JPIB_K), PARAMETER :: VORTICITY_LEVEL_E=3
  INTEGER(KIND=JPIB_K), PARAMETER :: THETA_LEVEL_E=4
  INTEGER(KIND=JPIB_K), PARAMETER :: SURFACE_E=5

  INTEGER(KIND=JPIB_K), PARAMETER :: WAVE_INT_E=6
  INTEGER(KIND=JPIB_K), PARAMETER :: WAVE_SPEC_E=7

  ! Enumerators for messages
  INTEGER(KIND=JPIB_K), PARAMETER :: ATM_MSG_E=1
  INTEGER(KIND=JPIB_K), PARAMETER :: WAM_MSG_E=2

  ! Enumerators for values
  INTEGER(KIND=JPIB_K), PARAMETER :: VALUES_SP_E=1
  INTEGER(KIND=JPIB_K), PARAMETER :: VALUES_DP_E=2

  ! Grib editions
  INTEGER(KIND=JPIB_K), PARAMETER :: GRIB1_E=1
  INTEGER(KIND=JPIB_K), PARAMETER :: GRIB2_E=2

  ! Enumerators for representations
  INTEGER(KIND=JPIB_K), PARAMETER :: REPRES_GRIDDED_E=1
  INTEGER(KIND=JPIB_K), PARAMETER :: REPRES_SPECTRAL_E=2

  ! Enumerators for type of statisticsal process
  INTEGER(KIND=JPIB_K), PARAMETER :: TYPE_OF_STATISTICAL_PROCESS_INSTANT_E=1
  INTEGER(KIND=JPIB_K), PARAMETER :: TYPE_OF_STATISTICAL_PROCESS_AVERAGE_E=2
  INTEGER(KIND=JPIB_K), PARAMETER :: TYPE_OF_STATISTICAL_PROCESS_ACCUMUL_E=3
  INTEGER(KIND=JPIB_K), PARAMETER :: TYPE_OF_STATISTICAL_PROCESS_MIN_E=4
  INTEGER(KIND=JPIB_K), PARAMETER :: TYPE_OF_STATISTICAL_PROCESS_MAX_E=5
  INTEGER(KIND=JPIB_K), PARAMETER :: TYPE_OF_STATISTICAL_PROCESS_SEVERITY_E=6
  INTEGER(KIND=JPIB_K), PARAMETER :: TYPE_OF_STATISTICAL_PROCESS_MODE_E=7

  ! Enumeators for type of time range
  INTEGER(KIND=JPIB_K), PARAMETER :: TYPE_OF_TIME_RANGE_INSTANT_E=1
  INTEGER(KIND=JPIB_K), PARAMETER :: TYPE_OF_TIME_RANGE_FROM_STEP0_E=2
  INTEGER(KIND=JPIB_K), PARAMETER :: TYPE_OF_TIME_RANGE_FROM_LASTPP_E=3
  INTEGER(KIND=JPIB_K), PARAMETER :: TYPE_OF_TIME_RANGE_FIXED_SIZE_E=4



  ! Undefined parameters
  INTEGER(KIND=JPIB_K), PARAMETER :: UNDEF_PARAM_E=-99


  !
  ! Enumerators for prefixes
  PUBLIC :: MODEL_LEVEL_E
  PUBLIC :: PRESSURE_LEVEL_E
  PUBLIC :: VORTICITY_LEVEL_E
  PUBLIC :: THETA_LEVEL_E
  PUBLIC :: SURFACE_E

  PUBLIC :: WAVE_INT_E
  PUBLIC :: WAVE_SPEC_E

  ! Enumerators for messages
  PUBLIC :: ATM_MSG_E
  PUBLIC :: WAM_MSG_E

  ! Enumerators for values
  PUBLIC :: VALUES_SP_E
  PUBLIC :: VALUES_DP_E

  ! Grib editions
  PUBLIC :: GRIB1_E
  PUBLIC :: GRIB2_E

  ! Enumerators for representations
  PUBLIC :: REPRES_GRIDDED_E
  PUBLIC :: REPRES_SPECTRAL_E

  ! Enumerators for type of statisticsal process
  PUBLIC :: TYPE_OF_STATISTICAL_PROCESS_INSTANT_E
  PUBLIC :: TYPE_OF_STATISTICAL_PROCESS_AVERAGE_E
  PUBLIC :: TYPE_OF_STATISTICAL_PROCESS_ACCUMUL_E
  PUBLIC :: TYPE_OF_STATISTICAL_PROCESS_MIN_E
  PUBLIC :: TYPE_OF_STATISTICAL_PROCESS_MAX_E
  PUBLIC :: TYPE_OF_STATISTICAL_PROCESS_SEVERITY_E
  PUBLIC :: TYPE_OF_STATISTICAL_PROCESS_MODE_E

  ! Enumeators for type of time range
  PUBLIC :: TYPE_OF_TIME_RANGE_INSTANT_E
  PUBLIC :: TYPE_OF_TIME_RANGE_FROM_STEP0_E
  PUBLIC :: TYPE_OF_TIME_RANGE_FROM_LASTPP_E
  PUBLIC :: TYPE_OF_TIME_RANGE_FIXED_SIZE_E

  ! Undefined parameters
  PUBLIC :: UNDEF_PARAM_E

END MODULE OM_ENUMERATORS_MOD