MODULE OM_ENUMERATORS_MOD

    ! Symbols imported from other modules within the project.
    USE :: OM_DATA_KIND_MOD, ONLY: JPIB_K

IMPLICIT NONE

  ! Default visibility
  PRIVATE

  ! Enumerators for prefixes
  INTEGER(KIND=JPIB_K), PARAMETER :: MODEL_LEVEL_E=1
  INTEGER(KIND=JPIB_K), PARAMETER :: PRESSURE_LEVEL_E=2
  INTEGER(KIND=JPIB_K), PARAMETER :: VORTICITY_LEVEL_E=3
  INTEGER(KIND=JPIB_K), PARAMETER :: THETA_LEVEL_E=4
  INTEGER(KIND=JPIB_K), PARAMETER :: SURFACE_E=5

  INTEGER(KIND=JPIB_K), PARAMETER :: WAVE_INT_E=6
  INTEGER(KIND=JPIB_K), PARAMETER :: WAVE_SPEC_E=7

  ! Enumerators for levType
  INTEGER(KIND=JPIB_K), PARAMETER :: LEVTYPE_HHL_E=1
  INTEGER(KIND=JPIB_K), PARAMETER :: LEVTYPE_HPL_E=2
  INTEGER(KIND=JPIB_K), PARAMETER :: LEVTYPE_HL_E=3
  INTEGER(KIND=JPIB_K), PARAMETER :: LEVTYPE_ML_E=4
  INTEGER(KIND=JPIB_K), PARAMETER :: LEVTYPE_O2D_E=5
  INTEGER(KIND=JPIB_K), PARAMETER :: LEVTYPE_O3D_E=6
  INTEGER(KIND=JPIB_K), PARAMETER :: LEVTYPE_PL_E=7
  INTEGER(KIND=JPIB_K), PARAMETER :: LEVTYPE_PT_E=8
  INTEGER(KIND=JPIB_K), PARAMETER :: LEVTYPE_PV_E=9
  INTEGER(KIND=JPIB_K), PARAMETER :: LEVTYPE_SFC_E=10
  INTEGER(KIND=JPIB_K), PARAMETER :: LEVTYPE_SOL_E=11
  INTEGER(KIND=JPIB_K), PARAMETER :: N_LEVTYPE_E=11

  ! Enumerators for packing type
  INTEGER(KIND=JPIB_K), PARAMETER :: PACKING_TYPE_GRIB_SIMPLE_E=0
  INTEGER(KIND=JPIB_K), PARAMETER :: PACKING_TYPE_GRIB_CCSDE_E=1
  INTEGER(KIND=JPIB_K), PARAMETER :: PACKING_TYPE_GRIB_COMPLEX_E=2

  ! Enumerators for messages
  INTEGER(KIND=JPIB_K), PARAMETER :: ATM_MSG_E=1
  INTEGER(KIND=JPIB_K), PARAMETER :: WAM_MSG_E=2

  ! Enumerators for values
  INTEGER(KIND=JPIB_K), PARAMETER :: VALUES_SP_E=1
  INTEGER(KIND=JPIB_K), PARAMETER :: VALUES_DP_E=2

  ! Grib editions
  INTEGER(KIND=JPIB_K), PARAMETER :: GRIB1_E=1
  INTEGER(KIND=JPIB_K), PARAMETER :: GRIB2_E=2
  INTEGER(KIND=JPIB_K), PARAMETER, DIMENSION(2) :: GRIB_EDITIONS=[GRIB1_E,GRIB2_E]

  ! Enumerators for representations
  INTEGER(KIND=JPIB_K), PARAMETER :: REPRES_GRIDDED_E=1
  INTEGER(KIND=JPIB_K), PARAMETER :: REPRES_SPECTRAL_E=2
  INTEGER(KIND=JPIB_K), PARAMETER :: N_REPRES_E=2

  ! Enumerators for type of statisticsal process
  INTEGER(KIND=JPIB_K), PARAMETER :: TYPE_OF_STATISTICAL_PROCESS_INSTANT_E=1
  INTEGER(KIND=JPIB_K), PARAMETER :: TYPE_OF_STATISTICAL_PROCESS_AVERAGE_E=2
  INTEGER(KIND=JPIB_K), PARAMETER :: TYPE_OF_STATISTICAL_PROCESS_ACCUMUL_E=3
  INTEGER(KIND=JPIB_K), PARAMETER :: TYPE_OF_STATISTICAL_PROCESS_MIN_E=4
  INTEGER(KIND=JPIB_K), PARAMETER :: TYPE_OF_STATISTICAL_PROCESS_MAX_E=5
  INTEGER(KIND=JPIB_K), PARAMETER :: TYPE_OF_STATISTICAL_PROCESS_SEVERITY_E=6
  INTEGER(KIND=JPIB_K), PARAMETER :: TYPE_OF_STATISTICAL_PROCESS_MODE_E=7
  INTEGER(KIND=JPIB_K), DIMENSION(7), PARAMETER :: TYPE_OF_STATISTICAL_PROCESSES = [ &
&  TYPE_OF_STATISTICAL_PROCESS_INSTANT_E, &
&  TYPE_OF_STATISTICAL_PROCESS_AVERAGE_E, &
&  TYPE_OF_STATISTICAL_PROCESS_ACCUMUL_E, &
&  TYPE_OF_STATISTICAL_PROCESS_MIN_E,     &
&  TYPE_OF_STATISTICAL_PROCESS_MAX_E,     &
&  TYPE_OF_STATISTICAL_PROCESS_SEVERITY_E, &
&  TYPE_OF_STATISTICAL_PROCESS_MODE_E     ]


  ! Enumeators for type of time range
  INTEGER(KIND=JPIB_K), PARAMETER :: TYPE_OF_TIME_RANGE_INSTANT_E=1
  INTEGER(KIND=JPIB_K), PARAMETER :: TYPE_OF_TIME_RANGE_FROM_STEP0_E=2
  INTEGER(KIND=JPIB_K), PARAMETER :: TYPE_OF_TIME_RANGE_FROM_LASTPP_E=3
  INTEGER(KIND=JPIB_K), PARAMETER :: TYPE_OF_TIME_RANGE_FIXED_SIZE_E=4
  INTEGER(KIND=JPIB_K), DIMENSION(4), PARAMETER :: TYPE_OF_TIME_RANGES = [ &
&  TYPE_OF_TIME_RANGE_INSTANT_E,     &
&  TYPE_OF_TIME_RANGE_FROM_STEP0_E,  &
&  TYPE_OF_TIME_RANGE_FROM_LASTPP_E, &
&  TYPE_OF_TIME_RANGE_FIXED_SIZE_E   ]



  ! Undefined parameters
  INTEGER(KIND=JPIB_K), PARAMETER :: UNDEF_PARAM_E=-99

  PUBLIC :: GRIB_EDITIONS
  PUBLIC :: TYPE_OF_STATISTICAL_PROCESSES
  PUBLIC :: TYPE_OF_TIME_RANGES

  !
  ! Enumerators for prefixes
  PUBLIC :: MODEL_LEVEL_E
  PUBLIC :: PRESSURE_LEVEL_E
  PUBLIC :: VORTICITY_LEVEL_E
  PUBLIC :: THETA_LEVEL_E
  PUBLIC :: SURFACE_E

  PUBLIC :: WAVE_INT_E
  PUBLIC :: WAVE_SPEC_E

  ! Enumerators for messages
  PUBLIC :: ATM_MSG_E
  PUBLIC :: WAM_MSG_E

  ! Enumerators for values
  PUBLIC :: VALUES_SP_E
  PUBLIC :: VALUES_DP_E

  ! Grib editions
  PUBLIC :: GRIB1_E
  PUBLIC :: GRIB2_E

  ! Enumerators for representations
  PUBLIC :: REPRES_GRIDDED_E
  PUBLIC :: REPRES_SPECTRAL_E
  PUBLIC :: N_REPRES_E

  ! Enumerators for type of statisticsal process
  PUBLIC :: TYPE_OF_STATISTICAL_PROCESS_INSTANT_E
  PUBLIC :: TYPE_OF_STATISTICAL_PROCESS_AVERAGE_E
  PUBLIC :: TYPE_OF_STATISTICAL_PROCESS_ACCUMUL_E
  PUBLIC :: TYPE_OF_STATISTICAL_PROCESS_MIN_E
  PUBLIC :: TYPE_OF_STATISTICAL_PROCESS_MAX_E
  PUBLIC :: TYPE_OF_STATISTICAL_PROCESS_SEVERITY_E
  PUBLIC :: TYPE_OF_STATISTICAL_PROCESS_MODE_E

  ! Enumerators for packing type
  PUBLIC :: PACKING_TYPE_GRIB_SIMPLE_E
  PUBLIC :: PACKING_TYPE_GRIB_CCSDE_E
  PUBLIC :: PACKING_TYPE_GRIB_COMPLEX_E

  ! Enumeators for type of time range
  PUBLIC :: TYPE_OF_TIME_RANGE_INSTANT_E
  PUBLIC :: TYPE_OF_TIME_RANGE_FROM_STEP0_E
  PUBLIC :: TYPE_OF_TIME_RANGE_FROM_LASTPP_E
  PUBLIC :: TYPE_OF_TIME_RANGE_FIXED_SIZE_E

  ! Enumerators for levType
  PUBLIC :: LEVTYPE_HHL_E
  PUBLIC :: LEVTYPE_HPL_E
  PUBLIC :: LEVTYPE_HL_E
  PUBLIC :: LEVTYPE_ML_E
  PUBLIC :: LEVTYPE_O2D_E
  PUBLIC :: LEVTYPE_O3D_E
  PUBLIC :: LEVTYPE_PL_E
  PUBLIC :: LEVTYPE_PT_E
  PUBLIC :: LEVTYPE_PV_E
  PUBLIC :: LEVTYPE_SFC_E
  PUBLIC :: LEVTYPE_SOL_E
  PUBLIC :: N_LEVTYPE_E

  ! Undefined parameters
  PUBLIC :: UNDEF_PARAM_E

END MODULE OM_ENUMERATORS_MOD