! Include preprocessor utils
#include "output_manager_preprocessor_utils.h"
#include "output_manager_preprocessor_trace_utils.h"
#include "output_manager_preprocessor_logging_utils.h"
#include "output_manager_preprocessor_errhdl_utils.h"


#define PP_FILE_NAME 'sink_base_mod.F90'
#define PP_SECTION_TYPE 'MODULE'
#define PP_SECTION_NAME 'SINK_BASE_MOD'
MODULE SINK_BASE_MOD

  ! Symbols imported from other modules within the project.
  USE :: DATAKINDS_DEF_MOD, ONLY: JPIB_K

IMPLICIT NONE

! Defautl visibility of the module
PRIVATE

! Forward declarations
TYPE :: SINK_CONTAINER_T
  CLASS(SINK_BASE_A), POINTER :: SINK_=>NULL()
END TYPE

! The sink base
TYPE, ABSTRACT :: SINK_BASE_A

  ! The assignment base
  INTEGER(JPIB_K) :: SINK_KIND_=0_JPIB_K

  ! The filter base
  CHARACTER(LEN=128) :: METADATA_TO_BE_INJECTED_=REPEAT(' ',128)

CONTAINS

  PROCEDURE(SINK_READ_IF),                PUBLIC,  DEFERRED, PASS :: READ
  PROCEDURE(SINK_INITIALIZE_METADATA_IF), PUBLIC,  DEFERRED, PASS :: INIT_METADATA
  PROCEDURE(SINK_WRITE64_IF),             PRIVATE, DEFERRED, PASS :: WRITE64
  PROCEDURE(SINK_WRITE32_IF),             PRIVATE, DEFERRED, PASS :: WRITE32
  PROCEDURE(SINK_FREE_IF),                PUBLIC,  DEFERRED, PASS :: FREE
  GENERIC, PUBLIC :: WRITE => WRITE64, WRITE32

END TYPE

ABSTRACT INTERFACE
  PP_THREAD_SAFE FUNCTION SINK_READ_IF( SINK, CFG, HOOKS ) RESULT(RET)
    ! Symbols imported from other modules within the project.
    USE :: DATAKINDS_DEF_MOD, ONLY: JPIB_K
    USE :: HOOKS_MOD,         ONLY: HOOKS_T
    USE :: YAML_CORE_UTILS_MOD, ONLY: YAML_CONFIGURATION_T
    IMPORT :: SINK_BASE_A
  IMPLICIT NONE
    CLASS(SINK_BASE_A),         INTENT(INOUT) :: SINK
    TYPE(YAML_CONFIGURATION_T), INTENT(OUT)   :: CFG
    TYPE(HOOKS_T),              INTENT(INOUT) :: HOOKS
    INTEGER(KIND=JPIB_K) :: RET
  END FUNCTION SINK_READ_IF

  PP_THREAD_SAFE FUNCTION SINK_INITIALIZE_METADATA_IF( SINK, MIOH, METADATA, HOOKS ) RESULT(RET)
    ! Symbols imported from other modules within the project.
    USE :: DATAKINDS_DEF_MOD,   ONLY: JPIB_K
    USE :: DATAKINDS_DEF_MOD,   ONLY: JPRD_K
    USE :: HOOKS_MOD,           ONLY: HOOKS_T
    USE :: METADATA_BASE_MOD,   ONLY: METADATA_BASE_A
    ! Symbols imported from external libraries.
    USE :: MULTIO_API,  ONLY: MULTIO_HANDLE
    IMPORT :: SINK_BASE_A
  IMPLICIT NONE
    CLASS(SINK_BASE_A),              INTENT(INOUT) :: SINK
    TYPE(MULTIO_HANDLE),             INTENT(IN)    :: MIOH
    CLASS(METADATA_BASE_A), POINTER, INTENT(OUT)   :: METADATA
    TYPE(HOOKS_T),                   INTENT(INOUT) :: HOOKS
    INTEGER(KIND=JPIB_K) :: RET
  END FUNCTION SINK_INITIALIZE_METADATA_IF


  PP_THREAD_SAFE FUNCTION SINK_WRITE64_IF( SINK, MSG, PAR, METADATA, VALUES, HOOKS ) RESULT(RET)
    ! Symbols imported from other modules within the project.
    USE :: DATAKINDS_DEF_MOD,   ONLY: JPIB_K
    USE :: DATAKINDS_DEF_MOD,   ONLY: JPRD_K
    USE :: HOOKS_MOD,           ONLY: HOOKS_T
    USE :: METADATA_BASE_MOD,   ONLY: METADATA_BASE_A
    USE :: PARAMETRIZATION_MOD, ONLY: PARAMETRIZATION_T
    USE :: FORTRAN_MESSAGE_MOD, ONLY: FORTRAN_MESSAGE_T
    IMPORT :: SINK_BASE_A
  IMPLICIT NONE
    CLASS(SINK_BASE_A),              INTENT(INOUT) :: SINK
    TYPE(PARAMETRIZATION_T),         INTENT(IN)    :: PAR
    TYPE(FORTRAN_MESSAGE_T),         INTENT(IN)    :: MSG
    CLASS(METADATA_BASE_A), POINTER, INTENT(IN)    :: METADATA
    REAL(KIND=JPRD_K), DIMENSION(:), INTENT(IN)    :: VALUES
    TYPE(HOOKS_T),                   INTENT(INOUT) :: HOOKS
    INTEGER(KIND=JPIB_K) :: RET
  END FUNCTION SINK_WRITE64_IF

  PP_THREAD_SAFE FUNCTION SINK_WRITE32_IF( SINK, MSG, PAR, METADATA, VALUES, HOOKS ) RESULT(RET)
    ! Symbols imported from other modules within the project.
    USE :: DATAKINDS_DEF_MOD,   ONLY: JPIB_K
    USE :: DATAKINDS_DEF_MOD,   ONLY: JPRM_K
    USE :: HOOKS_MOD,           ONLY: HOOKS_T
    USE :: METADATA_BASE_MOD,   ONLY: METADATA_BASE_A
    USE :: PARAMETRIZATION_MOD, ONLY: PARAMETRIZATION_T
    USE :: FORTRAN_MESSAGE_MOD, ONLY: FORTRAN_MESSAGE_T
    IMPORT :: SINK_BASE_A
  IMPLICIT NONE
    CLASS(SINK_BASE_A),              INTENT(INOUT) :: SINK
    TYPE(PARAMETRIZATION_T),         INTENT(IN)    :: PAR
    TYPE(FORTRAN_MESSAGE_T),         INTENT(IN)    :: MSG
    CLASS(METADATA_BASE_A), POINTER, INTENT(IN)    :: METADATA
    REAL(KIND=JPRM_K), DIMENSION(:), INTENT(IN)    :: VALUES
    TYPE(HOOKS_T),                   INTENT(INOUT) :: HOOKS
    INTEGER(KIND=JPIB_K) :: RET
  END FUNCTION SINK_WRITE32_IF

  PP_THREAD_SAFE FUNCTION SINK_FREE_IF( SINK, HOOKS ) RESULT(RET)
    ! Symbols imported from other modules within the project.
    USE :: DATAKINDS_DEF_MOD, ONLY: JPIB_K
    USE :: HOOKS_MOD,         ONLY: HOOKS_T
    IMPORT :: SINK_BASE_A
  IMPLICIT NONE
    CLASS(SINK_BASE_A), INTENT(INOUT) :: SINK
    TYPE(HOOKS_T), INTENT(INOUT) :: HOOKS
    INTEGER(KIND=JPIB_K) :: RET
  END FUNCTION SINK_FREE_IF
END INTERFACE

! Whitelist of public symbols
PUBLIC :: SINK_BASE_A
PUBLIC :: SINK_CONTAINER_T

END MODULE SINK_BASE_MOD
#undef PP_SECTION_NAME
#undef PP_SECTION_TYPE
#undef PP_FILE_NAME
