build:
  python: "3.10"
  modules:
    - ninja
  dependencies:
    - ecmwf/ecbuild@master
    - ecmwf/eccodes@master
    - ecmwf/eckit@master
    - ecmwf/metkit@master
    - ecmwf/fckit@master
    - ecmwf/fdb@master
    - ecmwf/atlas@master
    - ecmwf/atlas-orca@master
    - ecmwf/mir@master
    - ecmwf/multio@master
  dependency_cmake_options:
    - "ecmwf/mir: '-DENABLE_BUILD_TOOLS=ON'"
    - "ecmwf/fdb: '-DENABLE_LUSTRE=OFF'"
  parallel: 64
  env:
    - CTEST_PARALLEL_LEVEL=1
    - ECCODES_SAMPLES_PATH=$ECCODES_DIR/share/eccodes/samples
    - ECCODES_DEFINITION_PATH=$ECCODES_DIR/share/eccodes/definitions
    - FINDLIBS_DISABLE_PACKAGE=yes
