matrix:
    - openmpi
    - hpcx_openmpi
    - intel_mpi
    - mpi_off


intel_mpi:
    build:
      modules:
        - ninja
        - intel-mpi
        - qhull
      modules_package:
        - eckit:intel-mpi
        - atlas:intel-mpi
      dependency_cmake_options:
        - "ecmwf/atlas: '-DENABLE_TESSELATION=ON'"
        - "ecmwf/mir: '-DENABLE_BUILD_TOOLS=ON'"
        - "ecmwf/fdb: '-DENABLE_LUSTRE=OFF'"
      dependencies:
        - ecmwf/ecbuild@develop
        - ecmwf/eccodes@develop
        - ecmwf/eckit@develop
        - ecmwf/metkit@feature/port-mars2grib
        - ecmwf/fckit@develop
        - ecmwf/fdb@develop
        - ecmwf/atlas@develop
        - ecmwf/atlas-orca@develop
        - ecmwf/mir@develop
      cmake_options:
        - -DECBUILD_DOWNLOAD_RETRIES=5
      parallel: 64
      ntasks: 16
      env:
        - OMPI_MCA_rmaps_base_oversubscribe=1
        - ECCODES_SAMPLES_PATH=$ECCODES_DIR/share/eccodes/samples
        - ECCODES_DEFINITION_PATH=$ECCODES_DIR/share/eccodes/definitions

hpcx_openmpi:
    build:
      modules:
        - ninja
        - hpcx-openmpi
        - qhull
      modules_package:
        - eckit:hpcx-openmpi
        - atlas:hpcx-openmpi
      dependency_cmake_options:
        - "ecmwf/atlas: '-DENABLE_TESSELATION=ON'"
        - "ecmwf/mir: '-DENABLE_BUILD_TOOLS=ON'"
        - "ecmwf/fdb: '-DENABLE_LUSTRE=OFF'"
      dependencies:
        - ecmwf/ecbuild@develop
        - ecmwf/eccodes@develop
        - ecmwf/eckit@develop
        - ecmwf/metkit@feature/port-mars2grib
        - ecmwf/fckit@develop
        - ecmwf/fdb@develop
        - ecmwf/atlas@develop
        - ecmwf/atlas-orca@develop
        - ecmwf/mir@develop
      cmake_options:
        - -DECBUILD_DOWNLOAD_RETRIES=5
      parallel: 64
      ntasks: 16
      env:
        - OMPI_MCA_rmaps_base_oversubscribe=1
        - ECCODES_SAMPLES_PATH=$ECCODES_DIR/share/eccodes/samples
        - ECCODES_DEFINITION_PATH=$ECCODES_DIR/share/eccodes/definitions

openmpi:
    build:
      modules:
        - ninja
        - openmpi
        - qhull
      modules_package:
        - eckit:openmpi
        - atlas:openmpi
      dependency_cmake_options:
        - "ecmwf/atlas: '-DENABLE_TESSELATION=ON'"
        - "ecmwf/mir: '-DENABLE_BUILD_TOOLS=ON'"
        - "ecmwf/fdb: '-DENABLE_LUSTRE=OFF'"
      dependencies:
        - ecmwf/ecbuild@develop
        - ecmwf/eccodes@develop
        - ecmwf/eckit@develop
        - ecmwf/metkit@feature/port-mars2grib
        - ecmwf/fckit@develop
        - ecmwf/fdb@develop
        - ecmwf/atlas@develop
        - ecmwf/atlas-orca@develop
        - ecmwf/mir@develop
      cmake_options:
        - -DECBUILD_DOWNLOAD_RETRIES=5
      parallel: 64
      ntasks: 16
      env:
        - OMPI_MCA_rmaps_base_oversubscribe=1
        - ECCODES_SAMPLES_PATH=$ECCODES_DIR/share/eccodes/samples
        - ECCODES_DEFINITION_PATH=$ECCODES_DIR/share/eccodes/definitions

mpi_off:
    build:
      modules:
        - ninja
        - qhull
      dependency_cmake_options:
        - "ecmwf/atlas: '-DENABLE_TESSELATION=ON'"
        - "ecmwf/mir: '-DENABLE_BUILD_TOOLS=ON'"
        - "ecmwf/fdb: '-DENABLE_LUSTRE=OFF'"
      dependencies:
        - ecmwf/ecbuild@develop
        - ecmwf/eccodes@develop
        - ecmwf/eckit@develop
        - ecmwf/metkit@feature/port-mars2grib
        - ecmwf/fckit@develop
        - ecmwf/fdb@develop
        - ecmwf/atlas@develop
        - ecmwf/atlas-orca@develop
        - ecmwf/mir@develop
      cmake_options:
        - -DECBUILD_DOWNLOAD_RETRIES=5
      parallel: 64
      env:
        - ECCODES_SAMPLES_PATH=$ECCODES_DIR/share/eccodes/samples
        - ECCODES_DEFINITION_PATH=$ECCODES_DIR/share/eccodes/definitions
