! Include preprocessor utils
#include "output_manager_preprocessor_utils.h"
#include "output_manager_preprocessor_trace_utils.h"
#include "output_manager_preprocessor_logging_utils.h"
#include "output_manager_preprocessor_errhdl_utils.h"

! Definition of the module
#define PP_FILE_NAME 'time_runtime_utils_mod.F90'
#define PP_SECTION_TYPE 'MODULE'
#define PP_SECTION_NAME 'TIME_RUNTIME_UTILS_MOD'
MODULE TIME_RUNTIME_UTILS_MOD

  ! Symbols imported from other modules within the project.
  USE :: TIME_ENCODERS_MOD, ONLY: ENCODERS_OPTIONS_T
  USE :: TIME_ENCODERS_MOD, ONLY: ENCODE_TIME_ATM_IF
  USE :: TIME_ENCODERS_MOD, ONLY: ENCODE_TIME_WAM_IF
  USE :: OM_CORE_MOD,       ONLY: CURR_TIME_T

IMPLICIT NONE

! Default visibility of the module
PRIVATE


TYPE :: TIME_MANAGER_CONTAINER_ATM_T
  PRIVATE
  PROCEDURE(ENCODE_TIME_ATM_IF), POINTER, NOPASS :: PATM_ => NULL()
CONTAINS
  PROCEDURE, NON_OVERRIDABLE, PASS, PUBLIC :: INITIALISE  => INITIALISE_ATM
  PROCEDURE, NON_OVERRIDABLE, PASS, PUBLIC :: FINALISE    => FINALISE_ATM
  PROCEDURE, NON_OVERRIDABLE, PASS, PUBLIC :: ENCODE_TIME => ENCODE_TIME_ATM
END TYPE

TYPE :: TIME_MANAGER_CONTAINER_WAM_T
  PRIVATE
  PROCEDURE(ENCODE_TIME_WAM_IF), POINTER, NOPASS :: PWAM_ => NULL()
CONTAINS
  PROCEDURE, NON_OVERRIDABLE, PASS, PUBLIC :: INITIALISE  => INITIALISE_WAM
  PROCEDURE, NON_OVERRIDABLE, PASS, PUBLIC :: FINALISE    => FINALISE_WAM
  PROCEDURE, NON_OVERRIDABLE, PASS, PUBLIC :: ENCODE_TIME => ENCODE_TIME_WAM
END TYPE

TYPE(ENCODERS_OPTIONS_T) :: OPTIONS
TYPE(TIME_MANAGER_CONTAINER_ATM_T), ALLOCATABLE, DIMENSION(:) :: TIME_ENCODERS_ATM
TYPE(TIME_MANAGER_CONTAINER_WAM_T), ALLOCATABLE, DIMENSION(:) :: TIME_ENCODERS_WAM


! Whitelist of public symbols
PUBLIC :: TIME_RUNTIME_INIT
PUBLIC :: TIME_RUNTIME_FREE
PUBLIC :: TIME_ENCODERS_ATM
PUBLIC :: TIME_ENCODERS_WAM
PUBLIC :: TIME_INDEXER
PUBLIC :: COMPUTE_CURRENT_TIME


CONTAINS


#define PP_PROCEDURE_TYPE 'SUBROUTINE'
#define PP_PROCEDURE_NAME 'COMPUTE_CURRENT_TIME'
FUNCTION COMPUTE_CURRENT_TIME( MODEL_PARAMS, GRIB_INFO, TIME_HIST, CURR_TIME ) RESULT(EX)

  ! Symbols imported from other modules within the project.
  USE :: OM_CORE_MOD,        ONLY: JPIB_K
  USE :: OM_CORE_MOD,        ONLY: JPRD_K
  USE :: OM_CORE_MOD,        ONLY: MODEL_PAR_T
  USE :: OM_CORE_MOD,        ONLY: OM_BASE_MSG_A
  USE :: OM_CORE_MOD,        ONLY: CURR_TIME_T
  USE :: OM_CORE_MOD,        ONLY: GRIB_INFO_T
  USE :: OM_CORE_MOD,        ONLY: TIME_HISTORY_T

  ! Symbols imported by the preprocessor for debugging purposes
  PP_DEBUG_USE_VARS

  ! Symbols imported by the preprocessor for tracing purposes
  PP_TRACE_USE_VARS

IMPLICIT NONE

  ! Dummy arguments
  TYPE(MODEL_PAR_T),    INTENT(IN)  :: MODEL_PARAMS
  TYPE(GRIB_INFO_T),    INTENT(IN)  :: GRIB_INFO
  TYPE(TIME_HISTORY_T), INTENT(IN)  :: TIME_HIST
  TYPE(CURR_TIME_T),    INTENT(OUT) :: CURR_TIME

  ! Function result
  LOGICAL :: EX

  ! Local variables
  INTEGER(KIND=JPIB_K)  :: ISTEP

  ! Local variables declared by the preprocessor for debugging purposes
  PP_DEBUG_DECL_VARS

  ! Local variables declared by the preprocessor for tracing purposes
  PP_TRACE_DECL_VARS

  ! Trace begin of procedure
  PP_TRACE_ENTER_PROCEDURE()

  ! Error handling
  PP_DEBUG_CRITICAL_COND_THROW( TRIM(MODEL_PARAMS%SIM_%CTYPE).NE.'fc', 1 )
  PP_DEBUG_CRITICAL_COND_THROW( MODEL_PARAMS%SIM_%LPPSTEPS, 2 )

  ! Get current step
  ISTEP = TIME_HIST%HIST_(TIME_HIST%SIZE_)

  ! Compute Current time
  ! This must be moved somewhere else since it is shared between
  ! grib1 and grib2
  ! IF( MODEL_PARAMS%SIM_%LPPSTEPS ) THEN
  !   CURR_TIME%TSTEP = 3600._JPRD_K
  !   CURR_TIME%ISEC  = INT( REAL(ISTEP,JPRD_K)*CURR_TIME%TSTEP, JPIB_K)
  ! ELSE
  CURR_TIME%TSTEP = MODEL_PARAMS%SIM_%TSTEP
  CURR_TIME%ISEC  = INT( REAL(ISTEP,JPRD_K)*CURR_TIME%TSTEP, JPIB_K)
  ! ENDIF

  ! IF( TRIM(MODEL_PARAMS%SIM_%CTYPE) .EQ. 'fc' ) THEN
  CURR_TIME%ISEC = CURR_TIME%ISEC + MODEL_PARAMS%SIM_%NSTEPINI*3600
  ! ENDIF

  ! This was supposed to be different from 0 only for the VAREPS case
  ! which is not supported anymore
  CURR_TIME%ISEC0=0

  ! Cehck if the field needs to be encoded
  EX = TO_BE_ENCODED( GRIB_INFO, TIME_HIST, CURR_TIME )

  ! Trace end of procedure (on success)
  PP_TRACE_EXIT_PROCEDURE_ON_SUCCESS()

  ! Exit point on success
  RETURN


! Error handler
PP_ERROR_HANDLER

  ErrorHandler: BLOCK

    ! Error handling variables
    CHARACTER(LEN=:), ALLOCATABLE :: STR

    ! HAndle different errors
    SELECT CASE(ERRIDX)
    CASE (1)
      PP_DEBUG_CREATE_ERROR_MSG( STR, 'Instant time encoding logic not implemented for mars type: "'//TRIM(MODEL_PARAMS%SIM_%CTYPE)//'"' )
    CASE (2)
      PP_DEBUG_CREATE_ERROR_MSG( STR, 'Logic not implemented for LPPSTEPS' )
    CASE DEFAULT
      PP_DEBUG_CREATE_ERROR_MSG( STR, 'Unhandled error' )
    END SELECT

    ! Trace end of procedure (on error)
    PP_TRACE_EXIT_PROCEDURE_ON_ERROR()

    ! Write the error message and stop the program
    PP_DEBUG_ABORT( STR )

  END BLOCK ErrorHandler

  ! Exit point on error
  RETURN

END FUNCTION COMPUTE_CURRENT_TIME
#undef PP_PROCEDURE_NAME
#undef PP_PROCEDURE_TYPE


#define PP_PROCEDURE_TYPE 'FUNCTION'
#define PP_PROCEDURE_NAME 'TO_BE_ENCODED'
FUNCTION TO_BE_ENCODED( GRIB_INFO, TIME_HIST, CURR_TIME ) RESULT(CHECK)

  ! Symbols imported from other modules within the project.
  USE :: OM_CORE_MOD, ONLY: GRIB_INFO_T
  USE :: OM_CORE_MOD, ONLY: TIME_HISTORY_T
  USE :: OM_CORE_MOD, ONLY: CURR_TIME_T
  USE :: OM_CORE_MOD, ONLY: TYPE_OF_TIME_RANGE_INSTANT_E
  USE :: OM_CORE_MOD, ONLY: TYPE_OF_TIME_RANGE_FROM_STEP0_E
  USE :: OM_CORE_MOD, ONLY: TYPE_OF_TIME_RANGE_FROM_LASTPP_E
  USE :: OM_CORE_MOD, ONLY: TYPE_OF_TIME_RANGE_FIXED_SIZE_E

  ! Symbols imported by the preprocessor for debugging purposes
  PP_DEBUG_USE_VARS

  ! Symbols imported by the preprocessor for tracing purposes
  PP_TRACE_USE_VARS

IMPLICIT NONE


  ! Dummy arguments
  TYPE(GRIB_INFO_T),    INTENT(IN)    :: GRIB_INFO
  TYPE(TIME_HISTORY_T), INTENT(IN)    :: TIME_HIST
  TYPE(CURR_TIME_T),    INTENT(INOUT) :: CURR_TIME

  ! Function result
  LOGICAL :: CHECK

  ! Local variables declared by the preprocessor for debugging purposes
  PP_DEBUG_DECL_VARS

  ! Local variables declared by the preprocessor for tracing purposes
  PP_TRACE_DECL_VARS

  ! Trace begin of procedure
  PP_TRACE_ENTER_PROCEDURE()

  SELECT CASE (GRIB_INFO%TYPE_OF_TIME_RANGE_)
  CASE (TYPE_OF_TIME_RANGE_INSTANT_E)
    IF ( CURR_TIME%ISEC .EQ. CURR_TIME%ISEC0 ) THEN
      CHECK = GRIB_INFO%IS_STEP0_VALID_
      CURR_TIME%IS_STEP_0 = .TRUE.
    ELSE
      CHECK = .TRUE.
      CURR_TIME%IS_STEP_0 = .FALSE.
    ENDIF
  CASE (TYPE_OF_TIME_RANGE_FROM_STEP0_E)
    IF ( CURR_TIME%ISEC .EQ. CURR_TIME%ISEC0 ) THEN
      CHECK = GRIB_INFO%IS_STEP0_VALID_
      CURR_TIME%IS_STEP_0 = .TRUE.
    ELSE
      CHECK = .TRUE.
      CURR_TIME%IS_STEP_0 = .FALSE.
    ENDIF
  CASE (TYPE_OF_TIME_RANGE_FROM_LASTPP_E)
    IF ( CURR_TIME%ISEC .EQ. CURR_TIME%ISEC0 ) THEN
      CHECK = GRIB_INFO%IS_STEP0_VALID_
      CURR_TIME%IS_STEP_0 = .TRUE.
    ELSE
      CHECK = .TRUE.
      CURR_TIME%IS_STEP_0 = .FALSE.
    ENDIF
  CASE (TYPE_OF_TIME_RANGE_FIXED_SIZE_E)
    IF ( CURR_TIME%ISEC - GRIB_INFO%OVERALL_LENGTH_OF_TIME_RANGE_ .LT. CURR_TIME%ISEC0 ) THEN
      CHECK = GRIB_INFO%IS_STEP0_VALID_
      CURR_TIME%IS_STEP_0 = .TRUE.
    ELSE
      CHECK = .TRUE.
      CURR_TIME%IS_STEP_0 = .FALSE.
    END IF
  CASE DEFAULT
    PP_DEBUG_CRITICAL_THROW( 1 )
  END SELECT

  PP_TRACE_EXIT_PROCEDURE_ON_SUCCESS()

  ! Exit point on success
  RETURN

! Error handler
PP_ERROR_HANDLER

  ErrorHandler: BLOCK

    ! Error handling variables
    CHARACTER(LEN=:), ALLOCATABLE :: STR
    CHARACTER(LEN=32) :: TMP

    ! Handle different errors
    SELECT CASE(ERRIDX)
    CASE (1)
      TMP=REPEAT(' ',32)
      WRITE(TMP,*) GRIB_INFO%TYPE_OF_TIME_RANGE_
      PP_DEBUG_CREATE_ERROR_MSG( STR, 'Unknknown type of timerange: '//TRIM(ADJUSTL(TMP))//')' )
    CASE DEFAULT
      PP_DEBUG_CREATE_ERROR_MSG( STR, 'Unhandled error' )
    END SELECT

    ! Trace end of procedure (on error)
    PP_TRACE_EXIT_PROCEDURE_ON_ERROR()

    ! Write the error message and stop the program
    PP_DEBUG_ABORT( STR )

  END BLOCK ErrorHandler

  ! Exit point on error
  RETURN

END FUNCTION TO_BE_ENCODED
#undef PP_PROCEDURE_NAME
#undef PP_PROCEDURE_TYPE


#define PP_PROCEDURE_TYPE 'FUNCTION'
#define PP_PROCEDURE_NAME 'TIME_INDEXER'
FUNCTION TIME_INDEXER( TYPE_OF_STATSTICSL_PROCESS, TYPE_OF_TIMERANGE, EDITION ) RESULT(IDX)

  ! Symbols imported from other modules within the project.
  USE :: OM_CORE_MOD, ONLY: JPIB_K

  ! Symbols imported by the preprocessor for debugging purposes
  PP_DEBUG_USE_VARS

  ! Symbols imported by the preprocessor for tracing purposes
  PP_TRACE_USE_VARS

IMPLICIT NONE

  ! Dummy arguments
  INTEGER(KIND=JPIB_K), INTENT(IN) :: TYPE_OF_STATSTICSL_PROCESS
  INTEGER(KIND=JPIB_K), INTENT(IN) :: TYPE_OF_TIMERANGE
  INTEGER(KIND=JPIB_K), INTENT(IN) :: EDITION

  ! Function result
  INTEGER(KIND=JPIB_K) :: IDX

  ! Local variables declared by the preprocessor for debugging purposes
  PP_DEBUG_DECL_VARS

  ! Local variables declared by the preprocessor for tracing purposes
  PP_TRACE_DECL_VARS

  ! Trace begin of procedure
  PP_TRACE_ENTER_PROCEDURE()

  ! Compute time encoder indexindex
  IDX = ( TYPE_OF_STATSTICSL_PROCESS-1 ) * 4 * 2 + &
&       ( TYPE_OF_TIMERANGE-1 ) * 2 + &
&       EDITION

  ! Trace end of procedure (on success)
  PP_TRACE_EXIT_PROCEDURE_ON_SUCCESS()

  ! Exit point
  RETURN

END FUNCTION TIME_INDEXER
#undef PP_PROCEDURE_NAME
#undef PP_PROCEDURE_TYPE


#define PP_PROCEDURE_TYPE 'SUBROUTINE'
#define PP_PROCEDURE_NAME 'TIME_RUNTIME_INIT'
SUBROUTINE TIME_RUNTIME_INIT( CFG, MODEL_PARAMS )

  ! Symbols imported from other modules within the project.
  USE :: OM_CORE_MOD,  ONLY: MODEL_PAR_T
  USE :: OM_CORE_MOD,  ONLY: JPIB_K

  ! Symbols imported from other libraries
  USE :: FCKIT_CONFIGURATION_MODULE, ONLY: FCKIT_CONFIGURATION

  ! Symbols imported by the preprocessor for debugging purposes
  PP_DEBUG_USE_VARS

  ! Symbols imported by the preprocessor for tracing purposes
  PP_TRACE_USE_VARS

IMPLICIT NONE

  ! Dummy arguments
  TYPE(FCKIT_CONFIGURATION), INTENT(IN) :: CFG
  TYPE(MODEL_PAR_T), TARGET, INTENT(IN) :: MODEL_PARAMS

  ! Local variables
  INTEGER(KIND=JPIB_K) :: STAT
  CHARACTER(LEN=:), ALLOCATABLE :: ERRMSG

  ! Local variables declared by the preprocessor for debugging purposes
  PP_DEBUG_DECL_VARS

  ! Local variables declared by the preprocessor for tracing purposes
  PP_TRACE_DECL_VARS

  ! Trace begin of procedure
  PP_TRACE_ENTER_PROCEDURE()


  ! Allocate ATM encoder memory
  ALLOCATE( TIME_ENCODERS_ATM(64), STAT=STAT, ERRMSG=ERRMSG )
  PP_DEBUG_DEVELOP_COND_THROW( STAT.NE.0, 1 )

  ! Call proper initialization procedures for atm
  CALL ATM_SET_INSTANT( CFG, MODEL_PARAMS )
  CALL ATM_SET_AVERAGE( CFG, MODEL_PARAMS )
  CALL ATM_SET_ACCUMULATION( CFG, MODEL_PARAMS )
  CALL ATM_SET_MIN( CFG, MODEL_PARAMS )
  CALL ATM_SET_MAX( CFG, MODEL_PARAMS )
  CALL ATM_SET_SEVERITY( CFG, MODEL_PARAMS )
  CALL ATM_SET_MODE( CFG, MODEL_PARAMS )

  ! Allocate WAM encoder memory
  ALLOCATE( TIME_ENCODERS_WAM(64), STAT=STAT, ERRMSG=ERRMSG )
  PP_DEBUG_DEVELOP_COND_THROW( STAT.NE.0, 2 )

  ! Call proper initialization procedures for wam
  CALL TIME_RUNTIME_INIT_WAM( CFG, MODEL_PARAMS )

  ! Paranoid check
  IF ( ALLOCATED(ERRMSG) ) THEN
    DEALLOCATE(ERRMSG)
  ENDIF

  ! Trace end of procedure (on success)
  PP_TRACE_EXIT_PROCEDURE_ON_SUCCESS()

  ! Exit point
  RETURN

! Error handler
PP_ERROR_HANDLER

  ErrorHandler: BLOCK

    ! Error handling variables
    CHARACTER(LEN=:), ALLOCATABLE :: STR

    ! HAndle different errors
    SELECT CASE(ERRIDX)
    CASE (1)
      IF ( ALLOCATED(ERRMSG) ) THEN
        PP_DEBUG_CREATE_ERROR_MSG( STR, 'Unable to allocate time ATM encoders: '//TRIM(ADJUSTL(ERRMSG)) )
        DEALLOCATE(ERRMSG)
      ELSE
        PP_DEBUG_CREATE_ERROR_MSG( STR, 'Unable to allocate time ATM encoders.' )
      ENDIF
    CASE (2)
      IF ( ALLOCATED(ERRMSG) ) THEN
        PP_DEBUG_CREATE_ERROR_MSG( STR, 'Unable to allocate time WAM encoders: '//TRIM(ADJUSTL(ERRMSG)) )
        DEALLOCATE(ERRMSG)
      ELSE
        PP_DEBUG_CREATE_ERROR_MSG( STR, 'Unable to allocate time WAM encoders.' )
      ENDIF
    CASE DEFAULT
      PP_DEBUG_CREATE_ERROR_MSG( STR, 'Unhandled error' )
    END SELECT

    ! Trace end of procedure (on error)
    PP_TRACE_EXIT_PROCEDURE_ON_ERROR()

    ! Write the error message and stop the program
    PP_DEBUG_ABORT( STR )

  END BLOCK ErrorHandler

  ! Exit point on error
  RETURN

END SUBROUTINE TIME_RUNTIME_INIT
#undef PP_PROCEDURE_NAME
#undef PP_PROCEDURE_TYPE



#define PP_PROCEDURE_TYPE 'SUBROUTINE'
#define PP_PROCEDURE_NAME 'ATM_SET_INSTANT'
SUBROUTINE ATM_SET_INSTANT( CFG, MODEL_PARAMS )

  ! Enumerators for type of statisticsal process
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_STATISTICAL_PROCESS_INSTANT_E

  ! Enumeators for type of time range
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_TIME_RANGE_INSTANT_E
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_TIME_RANGE_FROM_STEP0_E
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_TIME_RANGE_FROM_LASTPP_E
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_TIME_RANGE_FIXED_SIZE_E

  ! Enumerators For edition
  USE :: OM_CORE_MOD,  ONLY: GRIB1_E
  USE :: OM_CORE_MOD,  ONLY: GRIB2_E

  ! Procedures
  USE :: TIME_ENCODERS_MOD, ONLY: ERROR_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: INSTANT_TIME_ENCODER_GRIB1_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: INSTANT_TIME_ENCODER_GRIB2_ATM

  ! Symbols imported from other modules within the project.
  USE :: OM_CORE_MOD,  ONLY: MODEL_PAR_T

  ! Symbols imported from other libraries
  USE :: FCKIT_CONFIGURATION_MODULE, ONLY: FCKIT_CONFIGURATION

  ! Symbols imported by the preprocessor for debugging purposes
  PP_DEBUG_USE_VARS

  ! Symbols imported by the preprocessor for tracing purposes
  PP_TRACE_USE_VARS

IMPLICIT NONE

  ! Dummy arguments
  TYPE(FCKIT_CONFIGURATION), INTENT(IN) :: CFG
  TYPE(MODEL_PAR_T), TARGET, INTENT(IN) :: MODEL_PARAMS

  ! Local variables declared by the preprocessor for debugging purposes
  PP_DEBUG_DECL_VARS

  ! Local variables declared by the preprocessor for tracing purposes
  PP_TRACE_DECL_VARS

  ! Trace begin of procedure
  PP_TRACE_ENTER_PROCEDURE()

  ! Instant
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_INSTANT_E,TYPE_OF_TIME_RANGE_INSTANT_E,    GRIB1_E) )%INITIALISE( INSTANT_TIME_ENCODER_GRIB1_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_INSTANT_E,TYPE_OF_TIME_RANGE_INSTANT_E,    GRIB2_E) )%INITIALISE( INSTANT_TIME_ENCODER_GRIB2_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_INSTANT_E,TYPE_OF_TIME_RANGE_FROM_STEP0_E, GRIB1_E) )%INITIALISE( ERROR_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_INSTANT_E,TYPE_OF_TIME_RANGE_FROM_STEP0_E, GRIB2_E) )%INITIALISE( ERROR_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_INSTANT_E,TYPE_OF_TIME_RANGE_FROM_LASTPP_E,GRIB1_E) )%INITIALISE( ERROR_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_INSTANT_E,TYPE_OF_TIME_RANGE_FROM_LASTPP_E,GRIB2_E) )%INITIALISE( ERROR_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_INSTANT_E,TYPE_OF_TIME_RANGE_FIXED_SIZE_E, GRIB1_E) )%INITIALISE( ERROR_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_INSTANT_E,TYPE_OF_TIME_RANGE_FIXED_SIZE_E, GRIB2_E) )%INITIALISE( ERROR_ATM )

  ! Trace end of procedure (on success)
  PP_TRACE_EXIT_PROCEDURE_ON_SUCCESS()

  ! Exit point
  RETURN

END SUBROUTINE ATM_SET_INSTANT
#undef PP_PROCEDURE_NAME
#undef PP_PROCEDURE_TYPE

#define PP_PROCEDURE_TYPE 'SUBROUTINE'
#define PP_PROCEDURE_NAME 'ATM_SET_AVERAGE'
SUBROUTINE ATM_SET_AVERAGE( CFG, MODEL_PARAMS )

  ! Enumerators for type of statisticsal process
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_STATISTICAL_PROCESS_AVERAGE_E

  ! Enumeators for type of time range
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_TIME_RANGE_INSTANT_E
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_TIME_RANGE_FROM_STEP0_E
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_TIME_RANGE_FROM_LASTPP_E
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_TIME_RANGE_FIXED_SIZE_E

  ! Enumerators For edition
  USE :: OM_CORE_MOD,  ONLY: GRIB1_E
  USE :: OM_CORE_MOD,  ONLY: GRIB2_E

  ! Procedures
  USE :: TIME_ENCODERS_MOD, ONLY: ERROR_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: AVERAGE_FROM_STEP0_TIME_ENCODER_GRIB1_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: AVERAGE_FROM_STEP0_TIME_ENCODER_GRIB2_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: AVERAGE_FROM_LASTPP_TIME_ENCODER_GRIB1_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: AVERAGE_FROM_LASTPP_TIME_ENCODER_GRIB2_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: AVERAGE_FIXED_RANGE_TIME_ENCODER_GRIB1_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: AVERAGE_FIXED_RANGE_TIME_ENCODER_GRIB2_ATM

  ! Symbols imported from other modules within the project.
  USE :: OM_CORE_MOD,  ONLY: MODEL_PAR_T

  ! Symbols imported from other libraries
  USE :: FCKIT_CONFIGURATION_MODULE, ONLY: FCKIT_CONFIGURATION

  ! Symbols imported by the preprocessor for debugging purposes
  PP_DEBUG_USE_VARS

  ! Symbols imported by the preprocessor for tracing purposes
  PP_TRACE_USE_VARS

IMPLICIT NONE

  ! Dummy arguments
  TYPE(FCKIT_CONFIGURATION), INTENT(IN) :: CFG
  TYPE(MODEL_PAR_T), TARGET, INTENT(IN) :: MODEL_PARAMS

  ! Local variables declared by the preprocessor for debugging purposes
  PP_DEBUG_DECL_VARS

  ! Local variables declared by the preprocessor for tracing purposes
  PP_TRACE_DECL_VARS

  ! Trace begin of procedure
  PP_TRACE_ENTER_PROCEDURE()

  ! Average
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_AVERAGE_E,TYPE_OF_TIME_RANGE_INSTANT_E,    GRIB1_E) )%INITIALISE( ERROR_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_AVERAGE_E,TYPE_OF_TIME_RANGE_INSTANT_E,    GRIB2_E) )%INITIALISE( ERROR_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_AVERAGE_E,TYPE_OF_TIME_RANGE_FROM_STEP0_E, GRIB1_E) )%INITIALISE( AVERAGE_FROM_STEP0_TIME_ENCODER_GRIB1_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_AVERAGE_E,TYPE_OF_TIME_RANGE_FROM_STEP0_E, GRIB2_E) )%INITIALISE( AVERAGE_FROM_STEP0_TIME_ENCODER_GRIB2_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_AVERAGE_E,TYPE_OF_TIME_RANGE_FROM_LASTPP_E,GRIB1_E) )%INITIALISE( AVERAGE_FROM_LASTPP_TIME_ENCODER_GRIB1_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_AVERAGE_E,TYPE_OF_TIME_RANGE_FROM_LASTPP_E,GRIB2_E) )%INITIALISE( AVERAGE_FROM_LASTPP_TIME_ENCODER_GRIB2_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_AVERAGE_E,TYPE_OF_TIME_RANGE_FIXED_SIZE_E, GRIB1_E) )%INITIALISE( AVERAGE_FIXED_RANGE_TIME_ENCODER_GRIB1_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_AVERAGE_E,TYPE_OF_TIME_RANGE_FIXED_SIZE_E, GRIB2_E) )%INITIALISE( AVERAGE_FIXED_RANGE_TIME_ENCODER_GRIB2_ATM )

  ! Trace end of procedure (on success)
  PP_TRACE_EXIT_PROCEDURE_ON_SUCCESS()

  ! Exit point
  RETURN

END SUBROUTINE ATM_SET_AVERAGE
#undef PP_PROCEDURE_NAME
#undef PP_PROCEDURE_TYPE

#define PP_PROCEDURE_TYPE 'SUBROUTINE'
#define PP_PROCEDURE_NAME 'ATM_SET_ACCUMULATION'
SUBROUTINE ATM_SET_ACCUMULATION( CFG, MODEL_PARAMS )

  ! Enumerators for type of statisticsal process
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_STATISTICAL_PROCESS_ACCUMUL_E

  ! Enumeators for type of time range
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_TIME_RANGE_INSTANT_E
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_TIME_RANGE_FROM_STEP0_E
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_TIME_RANGE_FROM_LASTPP_E
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_TIME_RANGE_FIXED_SIZE_E

  ! Enumerators For edition
  USE :: OM_CORE_MOD,  ONLY: GRIB1_E
  USE :: OM_CORE_MOD,  ONLY: GRIB2_E

  ! Procedures
  USE :: TIME_ENCODERS_MOD, ONLY: ERROR_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: ACCUMULATION_FROM_LASTPP_TIME_ENCODER_GRIB1_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: ACCUMULATION_FROM_LASTPP_TIME_ENCODER_GRIB2_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: ACCUMULATION_FIXED_RANGE_TIME_ENCODER_GRIB1_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: ACCUMULATION_FIXED_RANGE_TIME_ENCODER_GRIB2_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: ACCUMULATION_FROM_STEP0_TIME_ENCODER_GRIB1_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: ACCUMULATION_FROM_STEP0_TIME_ENCODER_GRIB2_ATM

  ! Symbols imported from other modules within the project.
  USE :: OM_CORE_MOD,  ONLY: MODEL_PAR_T

  ! Symbols imported from other libraries
  USE :: FCKIT_CONFIGURATION_MODULE, ONLY: FCKIT_CONFIGURATION

  ! Symbols imported by the preprocessor for debugging purposes
  PP_DEBUG_USE_VARS

  ! Symbols imported by the preprocessor for tracing purposes
  PP_TRACE_USE_VARS

IMPLICIT NONE

  ! Dummy arguments
  TYPE(FCKIT_CONFIGURATION), INTENT(IN) :: CFG
  TYPE(MODEL_PAR_T), TARGET, INTENT(IN) :: MODEL_PARAMS

  ! Local variables declared by the preprocessor for debugging purposes
  PP_DEBUG_DECL_VARS

  ! Local variables declared by the preprocessor for tracing purposes
  PP_TRACE_DECL_VARS

  ! Trace begin of procedure
  PP_TRACE_ENTER_PROCEDURE()

  ! Accumulation
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_ACCUMUL_E,TYPE_OF_TIME_RANGE_INSTANT_E,    GRIB1_E) )%INITIALISE( ERROR_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_ACCUMUL_E,TYPE_OF_TIME_RANGE_INSTANT_E,    GRIB2_E) )%INITIALISE( ERROR_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_ACCUMUL_E,TYPE_OF_TIME_RANGE_FROM_STEP0_E, GRIB1_E) )%INITIALISE( ACCUMULATION_FROM_STEP0_TIME_ENCODER_GRIB1_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_ACCUMUL_E,TYPE_OF_TIME_RANGE_FROM_STEP0_E, GRIB2_E) )%INITIALISE( ACCUMULATION_FROM_STEP0_TIME_ENCODER_GRIB2_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_ACCUMUL_E,TYPE_OF_TIME_RANGE_FROM_LASTPP_E,GRIB1_E) )%INITIALISE( ACCUMULATION_FROM_LASTPP_TIME_ENCODER_GRIB1_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_ACCUMUL_E,TYPE_OF_TIME_RANGE_FROM_LASTPP_E,GRIB2_E) )%INITIALISE( ACCUMULATION_FROM_LASTPP_TIME_ENCODER_GRIB2_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_ACCUMUL_E,TYPE_OF_TIME_RANGE_FIXED_SIZE_E, GRIB1_E) )%INITIALISE( ACCUMULATION_FIXED_RANGE_TIME_ENCODER_GRIB1_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_ACCUMUL_E,TYPE_OF_TIME_RANGE_FIXED_SIZE_E, GRIB2_E) )%INITIALISE( ACCUMULATION_FIXED_RANGE_TIME_ENCODER_GRIB2_ATM )

  ! Trace end of procedure (on success)
  PP_TRACE_EXIT_PROCEDURE_ON_SUCCESS()

  ! Exit point
  RETURN

END SUBROUTINE ATM_SET_ACCUMULATION
#undef PP_PROCEDURE_NAME
#undef PP_PROCEDURE_TYPE

#define PP_PROCEDURE_TYPE 'SUBROUTINE'
#define PP_PROCEDURE_NAME 'ATM_SET_MIN'
SUBROUTINE ATM_SET_MIN( CFG, MODEL_PARAMS )

  ! Enumerators for type of statisticsal process
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_STATISTICAL_PROCESS_MIN_E

  ! Enumeators for type of time range
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_TIME_RANGE_INSTANT_E
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_TIME_RANGE_FROM_STEP0_E
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_TIME_RANGE_FROM_LASTPP_E
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_TIME_RANGE_FIXED_SIZE_E

  ! Enumerators For edition
  USE :: OM_CORE_MOD,  ONLY: GRIB1_E
  USE :: OM_CORE_MOD,  ONLY: GRIB2_E

  ! Procedures
  USE :: TIME_ENCODERS_MOD, ONLY: ERROR_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: MIN_FROM_LASTPP_TIME_ENCODER_GRIB1_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: MIN_FROM_LASTPP_TIME_ENCODER_GRIB2_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: MIN_FIXED_RANGE_TIME_ENCODER_GRIB1_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: MIN_FIXED_RANGE_TIME_ENCODER_GRIB2_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: MIN_FROM_STEP0_TIME_ENCODER_GRIB1_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: MIN_FROM_STEP0_TIME_ENCODER_GRIB2_ATM

  ! Symbols imported from other modules within the project.
  USE :: OM_CORE_MOD,  ONLY: MODEL_PAR_T

  ! Symbols imported from other libraries
  USE :: FCKIT_CONFIGURATION_MODULE, ONLY: FCKIT_CONFIGURATION

  ! Symbols imported by the preprocessor for debugging purposes
  PP_DEBUG_USE_VARS

  ! Symbols imported by the preprocessor for tracing purposes
  PP_TRACE_USE_VARS

IMPLICIT NONE

  ! Dummy arguments
  TYPE(FCKIT_CONFIGURATION), INTENT(IN) :: CFG
  TYPE(MODEL_PAR_T), TARGET, INTENT(IN) :: MODEL_PARAMS

  ! Local variables declared by the preprocessor for debugging purposes
  PP_DEBUG_DECL_VARS

  ! Local variables declared by the preprocessor for tracing purposes
  PP_TRACE_DECL_VARS

  ! Trace begin of procedure
  PP_TRACE_ENTER_PROCEDURE()

  ! Min
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MIN_E,TYPE_OF_TIME_RANGE_INSTANT_E,    GRIB1_E) )%INITIALISE( ERROR_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MIN_E,TYPE_OF_TIME_RANGE_INSTANT_E,    GRIB2_E) )%INITIALISE( ERROR_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MIN_E,TYPE_OF_TIME_RANGE_FROM_STEP0_E, GRIB1_E) )%INITIALISE( MIN_FROM_STEP0_TIME_ENCODER_GRIB1_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MIN_E,TYPE_OF_TIME_RANGE_FROM_STEP0_E, GRIB2_E) )%INITIALISE( MIN_FROM_STEP0_TIME_ENCODER_GRIB2_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MIN_E,TYPE_OF_TIME_RANGE_FROM_LASTPP_E,GRIB1_E) )%INITIALISE( MIN_FROM_LASTPP_TIME_ENCODER_GRIB1_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MIN_E,TYPE_OF_TIME_RANGE_FROM_LASTPP_E,GRIB2_E) )%INITIALISE( MIN_FROM_LASTPP_TIME_ENCODER_GRIB2_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MIN_E,TYPE_OF_TIME_RANGE_FIXED_SIZE_E, GRIB1_E) )%INITIALISE( MIN_FIXED_RANGE_TIME_ENCODER_GRIB1_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MIN_E,TYPE_OF_TIME_RANGE_FIXED_SIZE_E, GRIB2_E) )%INITIALISE( MIN_FIXED_RANGE_TIME_ENCODER_GRIB2_ATM )

  ! Trace end of procedure (on success)
  PP_TRACE_EXIT_PROCEDURE_ON_SUCCESS()

  ! Exit point
  RETURN

END SUBROUTINE ATM_SET_MIN
#undef PP_PROCEDURE_NAME
#undef PP_PROCEDURE_TYPE

#define PP_PROCEDURE_TYPE 'SUBROUTINE'
#define PP_PROCEDURE_NAME 'ATM_SET_MAX'
SUBROUTINE ATM_SET_MAX( CFG, MODEL_PARAMS )

  ! Enumerators for type of statisticsal process
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_STATISTICAL_PROCESS_MAX_E

  ! Enumeators for type of time range
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_TIME_RANGE_INSTANT_E
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_TIME_RANGE_FROM_STEP0_E
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_TIME_RANGE_FROM_LASTPP_E
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_TIME_RANGE_FIXED_SIZE_E

  ! Enumerators For edition
  USE :: OM_CORE_MOD,  ONLY: GRIB1_E
  USE :: OM_CORE_MOD,  ONLY: GRIB2_E

  ! Procedures
  USE :: TIME_ENCODERS_MOD, ONLY: ERROR_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: MAX_FROM_LASTPP_TIME_ENCODER_GRIB1_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: MAX_FROM_LASTPP_TIME_ENCODER_GRIB2_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: MAX_FIXED_RANGE_TIME_ENCODER_GRIB1_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: MAX_FIXED_RANGE_TIME_ENCODER_GRIB2_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: MAX_FROM_STEP0_TIME_ENCODER_GRIB1_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: MAX_FROM_STEP0_TIME_ENCODER_GRIB2_ATM

  ! Symbols imported from other modules within the project.
  USE :: OM_CORE_MOD,  ONLY: MODEL_PAR_T

  ! Symbols imported from other libraries
  USE :: FCKIT_CONFIGURATION_MODULE, ONLY: FCKIT_CONFIGURATION

  ! Symbols imported by the preprocessor for debugging purposes
  PP_DEBUG_USE_VARS

  ! Symbols imported by the preprocessor for tracing purposes
  PP_TRACE_USE_VARS

IMPLICIT NONE

  ! Dummy arguments
  TYPE(FCKIT_CONFIGURATION), INTENT(IN) :: CFG
  TYPE(MODEL_PAR_T), TARGET, INTENT(IN) :: MODEL_PARAMS

  ! Local variables declared by the preprocessor for debugging purposes
  PP_DEBUG_DECL_VARS

  ! Local variables declared by the preprocessor for tracing purposes
  PP_TRACE_DECL_VARS

  ! Trace begin of procedure
  PP_TRACE_ENTER_PROCEDURE()

  ! Max
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MAX_E,TYPE_OF_TIME_RANGE_INSTANT_E,    GRIB1_E) )%INITIALISE( ERROR_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MAX_E,TYPE_OF_TIME_RANGE_INSTANT_E,    GRIB2_E) )%INITIALISE( ERROR_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MAX_E,TYPE_OF_TIME_RANGE_FROM_STEP0_E, GRIB1_E) )%INITIALISE( MAX_FROM_STEP0_TIME_ENCODER_GRIB1_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MAX_E,TYPE_OF_TIME_RANGE_FROM_STEP0_E, GRIB2_E) )%INITIALISE( MAX_FROM_STEP0_TIME_ENCODER_GRIB2_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MAX_E,TYPE_OF_TIME_RANGE_FROM_LASTPP_E,GRIB1_E) )%INITIALISE( MAX_FROM_LASTPP_TIME_ENCODER_GRIB1_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MAX_E,TYPE_OF_TIME_RANGE_FROM_LASTPP_E,GRIB2_E) )%INITIALISE( MAX_FROM_LASTPP_TIME_ENCODER_GRIB2_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MAX_E,TYPE_OF_TIME_RANGE_FIXED_SIZE_E, GRIB1_E) )%INITIALISE( MAX_FIXED_RANGE_TIME_ENCODER_GRIB1_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MAX_E,TYPE_OF_TIME_RANGE_FIXED_SIZE_E, GRIB2_E) )%INITIALISE( MAX_FIXED_RANGE_TIME_ENCODER_GRIB2_ATM )

  ! Trace end of procedure (on success)
  PP_TRACE_EXIT_PROCEDURE_ON_SUCCESS()

  ! Exit point
  RETURN

END SUBROUTINE ATM_SET_MAX
#undef PP_PROCEDURE_NAME
#undef PP_PROCEDURE_TYPE

#define PP_PROCEDURE_TYPE 'SUBROUTINE'
#define PP_PROCEDURE_NAME 'ATM_SET_SEVERITY'
SUBROUTINE ATM_SET_SEVERITY( CFG, MODEL_PARAMS )

  ! Enumerators for type of statisticsal process
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_STATISTICAL_PROCESS_SEVERITY_E

  ! Enumeators for type of time range
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_TIME_RANGE_INSTANT_E
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_TIME_RANGE_FROM_STEP0_E
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_TIME_RANGE_FROM_LASTPP_E
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_TIME_RANGE_FIXED_SIZE_E

  ! Enumerators For edition
  USE :: OM_CORE_MOD,  ONLY: GRIB1_E
  USE :: OM_CORE_MOD,  ONLY: GRIB2_E

  ! Procedures
  USE :: TIME_ENCODERS_MOD, ONLY: ERROR_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: SEVERITY_FROM_LASTPP_TIME_ENCODER_GRIB1_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: SEVERITY_FROM_LASTPP_TIME_ENCODER_GRIB2_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: SEVERITY_FIXED_RANGE_TIME_ENCODER_GRIB1_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: SEVERITY_FIXED_RANGE_TIME_ENCODER_GRIB2_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: SEVERITY_FROM_STEP0_TIME_ENCODER_GRIB1_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: SEVERITY_FROM_STEP0_TIME_ENCODER_GRIB2_ATM

  ! Symbols imported from other modules within the project.
  USE :: OM_CORE_MOD,  ONLY: MODEL_PAR_T

  ! Symbols imported from other libraries
  USE :: FCKIT_CONFIGURATION_MODULE, ONLY: FCKIT_CONFIGURATION

  ! Symbols imported by the preprocessor for debugging purposes
  PP_DEBUG_USE_VARS

  ! Symbols imported by the preprocessor for tracing purposes
  PP_TRACE_USE_VARS

IMPLICIT NONE

  ! Dummy arguments
  TYPE(FCKIT_CONFIGURATION), INTENT(IN) :: CFG
  TYPE(MODEL_PAR_T), TARGET, INTENT(IN) :: MODEL_PARAMS

  ! Local variables declared by the preprocessor for debugging purposes
  PP_DEBUG_DECL_VARS

  ! Local variables declared by the preprocessor for tracing purposes
  PP_TRACE_DECL_VARS

  ! Trace begin of procedure
  PP_TRACE_ENTER_PROCEDURE()

  ! Severity
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_SEVERITY_E,TYPE_OF_TIME_RANGE_INSTANT_E,    GRIB1_E) )%INITIALISE( ERROR_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_SEVERITY_E,TYPE_OF_TIME_RANGE_INSTANT_E,    GRIB2_E) )%INITIALISE( ERROR_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_SEVERITY_E,TYPE_OF_TIME_RANGE_FROM_STEP0_E, GRIB1_E) )%INITIALISE( SEVERITY_FROM_STEP0_TIME_ENCODER_GRIB1_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_SEVERITY_E,TYPE_OF_TIME_RANGE_FROM_STEP0_E, GRIB2_E) )%INITIALISE( SEVERITY_FROM_STEP0_TIME_ENCODER_GRIB2_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_SEVERITY_E,TYPE_OF_TIME_RANGE_FROM_LASTPP_E,GRIB1_E) )%INITIALISE( SEVERITY_FROM_LASTPP_TIME_ENCODER_GRIB1_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_SEVERITY_E,TYPE_OF_TIME_RANGE_FROM_LASTPP_E,GRIB2_E) )%INITIALISE( SEVERITY_FROM_LASTPP_TIME_ENCODER_GRIB2_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_SEVERITY_E,TYPE_OF_TIME_RANGE_FIXED_SIZE_E, GRIB1_E) )%INITIALISE( SEVERITY_FIXED_RANGE_TIME_ENCODER_GRIB1_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_SEVERITY_E,TYPE_OF_TIME_RANGE_FIXED_SIZE_E, GRIB2_E) )%INITIALISE( SEVERITY_FIXED_RANGE_TIME_ENCODER_GRIB2_ATM )

  ! Trace end of procedure (on success)
  PP_TRACE_EXIT_PROCEDURE_ON_SUCCESS()

  ! Exit point
  RETURN

END SUBROUTINE ATM_SET_SEVERITY
#undef PP_PROCEDURE_NAME
#undef PP_PROCEDURE_TYPE

#define PP_PROCEDURE_TYPE 'SUBROUTINE'
#define PP_PROCEDURE_NAME 'ATM_SET_MODE'
SUBROUTINE ATM_SET_MODE( CFG, MODEL_PARAMS )

  ! Enumerators for type of statisticsal process
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_STATISTICAL_PROCESS_MODE_E

  ! Enumeators for type of time range
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_TIME_RANGE_INSTANT_E
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_TIME_RANGE_FROM_STEP0_E
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_TIME_RANGE_FROM_LASTPP_E
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_TIME_RANGE_FIXED_SIZE_E

  ! Enumerators For edition
  USE :: OM_CORE_MOD,  ONLY: GRIB1_E
  USE :: OM_CORE_MOD,  ONLY: GRIB2_E

  ! Procedures
  USE :: TIME_ENCODERS_MOD, ONLY: ERROR_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: MODE_FROM_LASTPP_TIME_ENCODER_GRIB1_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: MODE_FROM_LASTPP_TIME_ENCODER_GRIB2_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: MODE_FIXED_RANGE_TIME_ENCODER_GRIB1_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: MODE_FIXED_RANGE_TIME_ENCODER_GRIB2_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: MODE_FROM_STEP0_TIME_ENCODER_GRIB1_ATM
  USE :: TIME_ENCODERS_MOD, ONLY: MODE_FROM_STEP0_TIME_ENCODER_GRIB2_ATM

  ! Symbols imported from other modules within the project.
  USE :: OM_CORE_MOD,  ONLY: MODEL_PAR_T

  ! Symbols imported from other libraries
  USE :: FCKIT_CONFIGURATION_MODULE, ONLY: FCKIT_CONFIGURATION

  ! Symbols imported by the preprocessor for debugging purposes
  PP_DEBUG_USE_VARS

  ! Symbols imported by the preprocessor for tracing purposes
  PP_TRACE_USE_VARS

IMPLICIT NONE

  ! Dummy arguments
  TYPE(FCKIT_CONFIGURATION), INTENT(IN) :: CFG
  TYPE(MODEL_PAR_T), TARGET, INTENT(IN) :: MODEL_PARAMS

  ! Local variables declared by the preprocessor for debugging purposes
  PP_DEBUG_DECL_VARS

  ! Local variables declared by the preprocessor for tracing purposes
  PP_TRACE_DECL_VARS

  ! Trace begin of procedure
  PP_TRACE_ENTER_PROCEDURE()

  ! Mode
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MODE_E,TYPE_OF_TIME_RANGE_INSTANT_E,    GRIB1_E) )%INITIALISE( ERROR_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MODE_E,TYPE_OF_TIME_RANGE_INSTANT_E,    GRIB2_E) )%INITIALISE( ERROR_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MODE_E,TYPE_OF_TIME_RANGE_FROM_STEP0_E, GRIB1_E) )%INITIALISE( MODE_FROM_STEP0_TIME_ENCODER_GRIB1_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MODE_E,TYPE_OF_TIME_RANGE_FROM_STEP0_E, GRIB2_E) )%INITIALISE( MODE_FROM_STEP0_TIME_ENCODER_GRIB2_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MODE_E,TYPE_OF_TIME_RANGE_FROM_LASTPP_E,GRIB1_E) )%INITIALISE( MODE_FROM_LASTPP_TIME_ENCODER_GRIB1_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MODE_E,TYPE_OF_TIME_RANGE_FROM_LASTPP_E,GRIB2_E) )%INITIALISE( MODE_FROM_LASTPP_TIME_ENCODER_GRIB2_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MODE_E,TYPE_OF_TIME_RANGE_FIXED_SIZE_E, GRIB1_E) )%INITIALISE( MODE_FIXED_RANGE_TIME_ENCODER_GRIB1_ATM )
  CALL TIME_ENCODERS_ATM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MODE_E,TYPE_OF_TIME_RANGE_FIXED_SIZE_E, GRIB2_E) )%INITIALISE( MODE_FIXED_RANGE_TIME_ENCODER_GRIB2_ATM )

  ! Trace end of procedure (on success)
  PP_TRACE_EXIT_PROCEDURE_ON_SUCCESS()

  ! Exit point
  RETURN

END SUBROUTINE ATM_SET_MODE
#undef PP_PROCEDURE_NAME
#undef PP_PROCEDURE_TYPE




#define PP_PROCEDURE_TYPE 'SUBROUTINE'
#define PP_PROCEDURE_NAME 'TIME_RUNTIME_INIT_WAM'
SUBROUTINE TIME_RUNTIME_INIT_WAM( CFG, MODEL_PARAMS )

  ! Symbols imported from other modules within the project.
  USE :: OM_CORE_MOD,  ONLY: JPIB_K
  USE :: OM_CORE_MOD,  ONLY: MODEL_PAR_T

  ! Enumerators for messages
  USE :: OM_CORE_MOD,  ONLY: ATM_MSG_E
  USE :: OM_CORE_MOD,  ONLY: WAM_MSG_E

  ! Enumerators for type of statisticsal process
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_STATISTICAL_PROCESS_INSTANT_E
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_STATISTICAL_PROCESS_AVERAGE_E
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_STATISTICAL_PROCESS_ACCUMUL_E
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_STATISTICAL_PROCESS_MIN_E
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_STATISTICAL_PROCESS_MAX_E
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_STATISTICAL_PROCESS_SEVERITY_E
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_STATISTICAL_PROCESS_MODE_E

  ! Enumeators for type of time range
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_TIME_RANGE_INSTANT_E
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_TIME_RANGE_FROM_STEP0_E
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_TIME_RANGE_FROM_LASTPP_E
  USE :: OM_CORE_MOD,  ONLY: TYPE_OF_TIME_RANGE_FIXED_SIZE_E
  USE :: OM_CORE_MOD,  ONLY: GRIB1_E
  USE :: OM_CORE_MOD,  ONLY: GRIB2_E

  ! Encoders for time information
  USE :: TIME_ENCODERS_MOD, ONLY: ERROR_WAM
  USE :: TIME_ENCODERS_MOD, ONLY: NOT_IMPLEMENTED_WAM
  USE :: TIME_ENCODERS_MOD, ONLY: INSTANT_TIME_ENCODER_GRIB1_WAM
  USE :: TIME_ENCODERS_MOD, ONLY: INSTANT_TIME_ENCODER_GRIB2_WAM


  ! Symbols imported from other libraries
  USE :: FCKIT_CONFIGURATION_MODULE, ONLY: FCKIT_CONFIGURATION

  ! Symbols imported by the preprocessor for debugging purposes
  PP_DEBUG_USE_VARS

  ! Symbols imported by the preprocessor for tracing purposes
  PP_TRACE_USE_VARS

IMPLICIT NONE

  ! Dummy arguments
  TYPE(FCKIT_CONFIGURATION), INTENT(IN) :: CFG
  TYPE(MODEL_PAR_T), TARGET, INTENT(IN) :: MODEL_PARAMS

  ! Local variables declared by the preprocessor for debugging purposes
  PP_DEBUG_DECL_VARS

  ! Local variables declared by the preprocessor for tracing purposes
  PP_TRACE_DECL_VARS

  ! Trace begin of procedure
  PP_TRACE_ENTER_PROCEDURE()

  ! Instant
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_INSTANT_E,TYPE_OF_TIME_RANGE_INSTANT_E,GRIB1_E) )%INITIALISE( INSTANT_TIME_ENCODER_GRIB1_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_INSTANT_E,TYPE_OF_TIME_RANGE_INSTANT_E,GRIB2_E) )%INITIALISE( INSTANT_TIME_ENCODER_GRIB2_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_INSTANT_E,TYPE_OF_TIME_RANGE_FROM_STEP0_E,GRIB1_E) )%INITIALISE( ERROR_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_INSTANT_E,TYPE_OF_TIME_RANGE_FROM_STEP0_E,GRIB2_E) )%INITIALISE( ERROR_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_INSTANT_E,TYPE_OF_TIME_RANGE_FROM_LASTPP_E,GRIB1_E) )%INITIALISE( ERROR_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_INSTANT_E,TYPE_OF_TIME_RANGE_FROM_LASTPP_E,GRIB2_E) )%INITIALISE( ERROR_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_INSTANT_E,TYPE_OF_TIME_RANGE_FIXED_SIZE_E,GRIB1_E) )%INITIALISE( ERROR_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_INSTANT_E,TYPE_OF_TIME_RANGE_FIXED_SIZE_E,GRIB2_E) )%INITIALISE( ERROR_WAM )

  ! Average
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_AVERAGE_E,TYPE_OF_TIME_RANGE_INSTANT_E,GRIB1_E) )%INITIALISE( ERROR_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_AVERAGE_E,TYPE_OF_TIME_RANGE_INSTANT_E,GRIB2_E) )%INITIALISE( ERROR_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_AVERAGE_E,TYPE_OF_TIME_RANGE_FROM_STEP0_E,GRIB1_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_AVERAGE_E,TYPE_OF_TIME_RANGE_FROM_STEP0_E,GRIB2_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_AVERAGE_E,TYPE_OF_TIME_RANGE_FROM_LASTPP_E,GRIB1_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_AVERAGE_E,TYPE_OF_TIME_RANGE_FROM_LASTPP_E,GRIB2_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_AVERAGE_E,TYPE_OF_TIME_RANGE_FIXED_SIZE_E,GRIB1_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_AVERAGE_E,TYPE_OF_TIME_RANGE_FIXED_SIZE_E,GRIB2_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )

  ! Accumulation
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_ACCUMUL_E,TYPE_OF_TIME_RANGE_INSTANT_E,GRIB1_E) )%INITIALISE( ERROR_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_ACCUMUL_E,TYPE_OF_TIME_RANGE_INSTANT_E,GRIB2_E) )%INITIALISE( ERROR_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_ACCUMUL_E,TYPE_OF_TIME_RANGE_FROM_STEP0_E,GRIB1_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_ACCUMUL_E,TYPE_OF_TIME_RANGE_FROM_STEP0_E,GRIB2_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_ACCUMUL_E,TYPE_OF_TIME_RANGE_FROM_LASTPP_E,GRIB1_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_ACCUMUL_E,TYPE_OF_TIME_RANGE_FROM_LASTPP_E,GRIB2_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_ACCUMUL_E,TYPE_OF_TIME_RANGE_FIXED_SIZE_E,GRIB1_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_ACCUMUL_E,TYPE_OF_TIME_RANGE_FIXED_SIZE_E,GRIB2_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )

  ! Min
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MIN_E,TYPE_OF_TIME_RANGE_INSTANT_E,GRIB1_E) )%INITIALISE( ERROR_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MIN_E,TYPE_OF_TIME_RANGE_INSTANT_E,GRIB2_E) )%INITIALISE( ERROR_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MIN_E,TYPE_OF_TIME_RANGE_FROM_STEP0_E,GRIB1_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MIN_E,TYPE_OF_TIME_RANGE_FROM_STEP0_E,GRIB2_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MIN_E,TYPE_OF_TIME_RANGE_FROM_LASTPP_E,GRIB1_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MIN_E,TYPE_OF_TIME_RANGE_FROM_LASTPP_E,GRIB2_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MIN_E,TYPE_OF_TIME_RANGE_FIXED_SIZE_E,GRIB1_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MIN_E,TYPE_OF_TIME_RANGE_FIXED_SIZE_E,GRIB2_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )

  ! Min
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MAX_E,TYPE_OF_TIME_RANGE_INSTANT_E,GRIB1_E) )%INITIALISE( ERROR_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MAX_E,TYPE_OF_TIME_RANGE_INSTANT_E,GRIB2_E) )%INITIALISE( ERROR_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MAX_E,TYPE_OF_TIME_RANGE_FROM_STEP0_E,GRIB1_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MAX_E,TYPE_OF_TIME_RANGE_FROM_STEP0_E,GRIB2_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MAX_E,TYPE_OF_TIME_RANGE_FROM_LASTPP_E,GRIB1_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MAX_E,TYPE_OF_TIME_RANGE_FROM_LASTPP_E,GRIB2_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MAX_E,TYPE_OF_TIME_RANGE_FIXED_SIZE_E,GRIB1_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MAX_E,TYPE_OF_TIME_RANGE_FIXED_SIZE_E,GRIB2_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )

  ! Severity
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_SEVERITY_E,TYPE_OF_TIME_RANGE_INSTANT_E,GRIB1_E) )%INITIALISE( ERROR_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_SEVERITY_E,TYPE_OF_TIME_RANGE_INSTANT_E,GRIB2_E) )%INITIALISE( ERROR_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_SEVERITY_E,TYPE_OF_TIME_RANGE_FROM_STEP0_E,GRIB1_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_SEVERITY_E,TYPE_OF_TIME_RANGE_FROM_STEP0_E,GRIB2_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_SEVERITY_E,TYPE_OF_TIME_RANGE_FROM_LASTPP_E,GRIB1_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_SEVERITY_E,TYPE_OF_TIME_RANGE_FROM_LASTPP_E,GRIB2_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_SEVERITY_E,TYPE_OF_TIME_RANGE_FIXED_SIZE_E,GRIB1_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_SEVERITY_E,TYPE_OF_TIME_RANGE_FIXED_SIZE_E,GRIB2_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )

  ! Mode
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MODE_E,TYPE_OF_TIME_RANGE_INSTANT_E,GRIB1_E) )%INITIALISE( ERROR_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MODE_E,TYPE_OF_TIME_RANGE_INSTANT_E,GRIB2_E) )%INITIALISE( ERROR_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MODE_E,TYPE_OF_TIME_RANGE_FROM_STEP0_E,GRIB1_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MODE_E,TYPE_OF_TIME_RANGE_FROM_STEP0_E,GRIB2_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MODE_E,TYPE_OF_TIME_RANGE_FROM_LASTPP_E,GRIB1_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MODE_E,TYPE_OF_TIME_RANGE_FROM_LASTPP_E,GRIB2_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MODE_E,TYPE_OF_TIME_RANGE_FIXED_SIZE_E,GRIB1_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )
  CALL TIME_ENCODERS_WAM( TIME_INDEXER(TYPE_OF_STATISTICAL_PROCESS_MODE_E,TYPE_OF_TIME_RANGE_FIXED_SIZE_E,GRIB2_E) )%INITIALISE( NOT_IMPLEMENTED_WAM )

  ! Trace end of procedure (on success)
  PP_TRACE_EXIT_PROCEDURE_ON_SUCCESS()

  ! Exit point
  RETURN

END SUBROUTINE TIME_RUNTIME_INIT_WAM
#undef PP_PROCEDURE_NAME
#undef PP_PROCEDURE_TYPE


#define PP_PROCEDURE_TYPE 'SUBROUTINE'
#define PP_PROCEDURE_NAME 'TIME_RUNTIME_FREE'
SUBROUTINE TIME_RUNTIME_FREE( )

  ! Symbols imported from other modules within the project.
  USE :: OM_CORE_MOD,  ONLY: JPIB_K

  ! Symbols imported by the preprocessor for debugging purposes
  PP_DEBUG_USE_VARS

  ! Symbols imported by the preprocessor for tracing purposes
  PP_TRACE_USE_VARS

IMPLICIT NONE

  ! Local variables
  INTEGER(KIND=JPIB_K) :: STAT
  CHARACTER(LEN=:), ALLOCATABLE :: ERRMSG

  ! Local variables declared by the preprocessor for debugging purposes
  PP_DEBUG_DECL_VARS

  ! Local variables declared by the preprocessor for tracing purposes
  PP_TRACE_DECL_VARS

  ! Trace begin of procedure
  PP_TRACE_ENTER_PROCEDURE()

  ! Free ATM encoder memory
  DEALLOCATE( TIME_ENCODERS_ATM, STAT=STAT, ERRMSG=ERRMSG )
  PP_DEBUG_DEVELOP_COND_THROW( STAT.NE.0, 1 )

  ! Free WAM encoder memory
  DEALLOCATE( TIME_ENCODERS_WAM, STAT=STAT, ERRMSG=ERRMSG )
  PP_DEBUG_DEVELOP_COND_THROW( STAT.NE.0, 2 )

  ! Trace end of procedure (on success)
  PP_TRACE_EXIT_PROCEDURE_ON_SUCCESS()

  ! Exit point
  RETURN

! Error handler
PP_ERROR_HANDLER

  ErrorHandler: BLOCK

    ! Error handling variables
    CHARACTER(LEN=:), ALLOCATABLE :: STR

    ! HAndle different errors
    SELECT CASE(ERRIDX)
    CASE (1)
      IF ( ALLOCATED(ERRMSG) ) THEN
        PP_DEBUG_CREATE_ERROR_MSG( STR, 'Unable to deallocate time ATM encoders: '//TRIM(ADJUSTL(ERRMSG)) )
        DEALLOCATE(ERRMSG)
      ELSE
        PP_DEBUG_CREATE_ERROR_MSG( STR, 'Unable to deallocate time ATM encoders.' )
      ENDIF
    CASE (2)
      IF ( ALLOCATED(ERRMSG) ) THEN
        PP_DEBUG_CREATE_ERROR_MSG( STR, 'Unable to deallocate time WAM encoders: '//TRIM(ADJUSTL(ERRMSG)) )
        DEALLOCATE(ERRMSG)
      ELSE
        PP_DEBUG_CREATE_ERROR_MSG( STR, 'Unable to deallocate time WAM encoders.' )
      ENDIF
    CASE DEFAULT
      PP_DEBUG_CREATE_ERROR_MSG( STR, 'Unhandled error' )
    END SELECT

    ! Trace end of procedure (on error)
    PP_TRACE_EXIT_PROCEDURE_ON_ERROR()

    ! Write the error message and stop the program
    PP_DEBUG_ABORT( STR )

  END BLOCK ErrorHandler

  ! Exit point on error
  RETURN

END SUBROUTINE TIME_RUNTIME_FREE
#undef PP_PROCEDURE_NAME
#undef PP_PROCEDURE_TYPE


#define PP_PROCEDURE_TYPE 'SUBROUTINE'
#define PP_PROCEDURE_NAME 'INITIALISE_ATM'
SUBROUTINE INITIALISE_ATM( THIS, PROC )

  ! Symbols imported from other modules within the project.
  USE :: TIME_ENCODERS_MOD, ONLY: ENCODE_TIME_ATM_IF

  ! Symbols imported by the preprocessor for debugging purposes
  PP_DEBUG_USE_VARS

  ! Symbols imported by the preprocessor for tracing purposes
  PP_TRACE_USE_VARS

IMPLICIT NONE

  ! Dummy arguments
  CLASS(TIME_MANAGER_CONTAINER_ATM_T), INTENT(INOUT) :: THIS
  PROCEDURE(ENCODE_TIME_ATM_IF)                      :: PROC

  ! Local variables declared by the preprocessor for debugging purposes
  PP_DEBUG_DECL_VARS

  ! Local variables declared by the preprocessor for tracing purposes
  PP_TRACE_DECL_VARS

  ! Trace begin of procedure
  PP_TRACE_ENTER_PROCEDURE()

  THIS%PATM_ => PROC

  ! Trace end of procedure (on success)
  PP_TRACE_EXIT_PROCEDURE_ON_SUCCESS()

  ! Exit point
  RETURN

END SUBROUTINE INITIALISE_ATM
#undef PP_PROCEDURE_NAME
#undef PP_PROCEDURE_TYPE




#define PP_PROCEDURE_TYPE 'SUBROUTINE'
#define PP_PROCEDURE_NAME 'ENCODE_TIME_ATM'
SUBROUTINE ENCODE_TIME_ATM( THIS, MODEL_PARAMS, GRIB_INFO, TIME_HIST, CURR_TIME, MSG, METADATA )

  ! Symbols imported from other modules within the project.
  USE :: OM_CORE_MOD,        ONLY: MODEL_PAR_T
  USE :: OM_CORE_MOD,        ONLY: CURR_TIME_T
  USE :: OM_CORE_MOD,        ONLY: GRIB_INFO_T
  USE :: OM_CORE_MOD,        ONLY: TIME_HISTORY_T
  USE :: OM_CORE_MOD,        ONLY: OM_ATM_MSG_T
  USE :: METADATA_BASE_MOD,  ONLY: METADATA_BASE_A

  ! Symbols imported by the preprocessor for debugging purposes
  PP_DEBUG_USE_VARS

  ! Symbols imported by the preprocessor for tracing purposes
  PP_TRACE_USE_VARS

IMPLICIT NONE

  ! Dummy arguments
  CLASS(TIME_MANAGER_CONTAINER_ATM_T), INTENT(INOUT) :: THIS
  TYPE(MODEL_PAR_T),                   INTENT(IN)    :: MODEL_PARAMS
  TYPE(GRIB_INFO_T),                   INTENT(IN)    :: GRIB_INFO
  TYPE(TIME_HISTORY_T),                INTENT(IN)    :: TIME_HIST
  TYPE(CURR_TIME_T),                   INTENT(IN)    :: CURR_TIME
  CLASS(OM_ATM_MSG_T),                 INTENT(IN)    :: MSG
  CLASS(METADATA_BASE_A), POINTER,     INTENT(INOUT) :: METADATA

  ! Local variables declared by the preprocessor for debugging purposes
  PP_DEBUG_DECL_VARS

  ! Local variables declared by the preprocessor for tracing purposes
  PP_TRACE_DECL_VARS

  ! Trace begin of procedure
  PP_TRACE_ENTER_PROCEDURE()
  PP_METADATA_ENTER_PROCEDURE( METADATA )

  ! Error handling
  PP_DEBUG_DEVELOP_COND_THROW( .NOT.ASSOCIATED(THIS%PATM_), 1 )

  ! Call the time encoder
  CALL THIS%PATM_( MODEL_PARAMS, GRIB_INFO, TIME_HIST, CURR_TIME, MSG, METADATA, OPTIONS )

  ! Trace end of procedure (on success)
  PP_METADATA_EXIT_PROCEDURE( METADATA )
  PP_TRACE_EXIT_PROCEDURE_ON_SUCCESS()

  ! Exit point
  RETURN

! Error handler
PP_ERROR_HANDLER

  ErrorHandler: BLOCK

    ! Error handling variables
    CHARACTER(LEN=:), ALLOCATABLE :: STR

    ! HAndle different errors
    SELECT CASE(ERRIDX)
    CASE (1)
      PP_DEBUG_CREATE_ERROR_MSG( STR, 'Time encoder not associated' )
    CASE DEFAULT
      PP_DEBUG_CREATE_ERROR_MSG( STR, 'Unhandled error' )
    END SELECT

    ! Trace end of procedure (on error)
    PP_TRACE_EXIT_PROCEDURE_ON_ERROR()

    ! Write the error message and stop the program
    PP_DEBUG_ABORT( STR )

  END BLOCK ErrorHandler

  ! Exit point on error
  RETURN

END SUBROUTINE ENCODE_TIME_ATM
#undef PP_PROCEDURE_NAME
#undef PP_PROCEDURE_TYPE


#define PP_PROCEDURE_TYPE 'SUBROUTINE'
#define PP_PROCEDURE_NAME 'FINALISE_ATM'
SUBROUTINE FINALISE_ATM( THIS )

  ! Symbols imported by the preprocessor for debugging purposes
  PP_DEBUG_USE_VARS

  ! Symbols imported by the preprocessor for tracing purposes
  PP_TRACE_USE_VARS

IMPLICIT NONE

  ! Dummy arguments
  CLASS(TIME_MANAGER_CONTAINER_ATM_T), INTENT(INOUT) :: THIS

  ! Local variables declared by the preprocessor for debugging purposes
  PP_DEBUG_DECL_VARS

  ! Local variables declared by the preprocessor for tracing purposes
  PP_TRACE_DECL_VARS

  ! Trace begin of procedure
  PP_TRACE_ENTER_PROCEDURE()

  ! Nullify the function pointers
  NULLIFY( THIS%PATM_ )

  ! Trace end of procedure (on success)
  PP_TRACE_EXIT_PROCEDURE_ON_SUCCESS()

  ! Exit point
  RETURN

END SUBROUTINE FINALISE_ATM
#undef PP_PROCEDURE_NAME
#undef PP_PROCEDURE_TYPE





#define PP_PROCEDURE_TYPE 'SUBROUTINE'
#define PP_PROCEDURE_NAME 'INITIALISE_WAM'
SUBROUTINE INITIALISE_WAM( THIS, PROC )

  ! Symbols imported from other modules within the project.
  USE :: TIME_ENCODERS_MOD, ONLY: ENCODE_TIME_WAM_IF

  ! Symbols imported by the preprocessor for debugging purposes
  PP_DEBUG_USE_VARS

  ! Symbols imported by the preprocessor for tracing purposes
  PP_TRACE_USE_VARS

IMPLICIT NONE

  ! Dummy arguments
  CLASS(TIME_MANAGER_CONTAINER_WAM_T), INTENT(INOUT) :: THIS
  PROCEDURE(ENCODE_TIME_WAM_IF)                      :: PROC

  ! Local variables declared by the preprocessor for debugging purposes
  PP_DEBUG_DECL_VARS

  ! Local variables declared by the preprocessor for tracing purposes
  PP_TRACE_DECL_VARS

  ! Trace begin of procedure
  PP_TRACE_ENTER_PROCEDURE()

  THIS%PWAM_ => PROC

  ! Trace end of procedure (on success)
  PP_TRACE_EXIT_PROCEDURE_ON_SUCCESS()

  ! Exit point
  RETURN

END SUBROUTINE INITIALISE_WAM
#undef PP_PROCEDURE_NAME
#undef PP_PROCEDURE_TYPE


#define PP_PROCEDURE_TYPE 'SUBROUTINE'
#define PP_PROCEDURE_NAME 'ENCODE_TIME_WAM'
SUBROUTINE ENCODE_TIME_WAM( THIS, MODEL_PARAMS, GRIB_INFO, TIME_HIST, CURR_TIME, MSG, METADATA )

  ! Symbols imported from other modules within the project.
  USE :: OM_CORE_MOD,        ONLY: MODEL_PAR_T
  USE :: OM_CORE_MOD,        ONLY: CURR_TIME_T
  USE :: OM_CORE_MOD,        ONLY: GRIB_INFO_T
  USE :: OM_CORE_MOD,        ONLY: TIME_HISTORY_T
  USE :: OM_CORE_MOD,        ONLY: OM_WAM_MSG_T
  USE :: METADATA_BASE_MOD,  ONLY: METADATA_BASE_A

  ! Symbols imported by the preprocessor for debugging purposes
  PP_DEBUG_USE_VARS

  ! Symbols imported by the preprocessor for tracing purposes
  PP_TRACE_USE_VARS

IMPLICIT NONE

  ! Dummy arguments
  CLASS(TIME_MANAGER_CONTAINER_WAM_T), INTENT(INOUT) :: THIS
  TYPE(MODEL_PAR_T),                   INTENT(IN)    :: MODEL_PARAMS
  TYPE(GRIB_INFO_T),                   INTENT(IN)    :: GRIB_INFO
  TYPE(TIME_HISTORY_T),                INTENT(IN)    :: TIME_HIST
  TYPE(CURR_TIME_T),                   INTENT(IN)    :: CURR_TIME
  CLASS(OM_WAM_MSG_T),                 INTENT(IN)    :: MSG
  CLASS(METADATA_BASE_A), POINTER,     INTENT(INOUT) :: METADATA

  ! Local variables declared by the preprocessor for debugging purposes
  PP_DEBUG_DECL_VARS

  ! Local variables declared by the preprocessor for tracing purposes
  PP_TRACE_DECL_VARS

  ! Trace begin of procedure
  PP_TRACE_ENTER_PROCEDURE()
  PP_METADATA_ENTER_PROCEDURE( METADATA )

  ! Error handling
  PP_DEBUG_DEVELOP_COND_THROW( .NOT.ASSOCIATED(THIS%PWAM_), 1 )

  ! Call the proper encoder
  CALL THIS%PWAM_( MODEL_PARAMS, GRIB_INFO, TIME_HIST, CURR_TIME, MSG, METADATA, OPTIONS )

  ! Trace end of procedure (on success)
  PP_METADATA_EXIT_PROCEDURE( METADATA )
  PP_TRACE_EXIT_PROCEDURE_ON_SUCCESS()

  ! Exit point
  RETURN

! Error handler
PP_ERROR_HANDLER

  ErrorHandler: BLOCK

    ! Error handling variables
    CHARACTER(LEN=:), ALLOCATABLE :: STR

    ! HAndle different errors
    SELECT CASE(ERRIDX)
    CASE (1)
      PP_DEBUG_CREATE_ERROR_MSG( STR, 'Time encoder not associated' )
    CASE DEFAULT
      PP_DEBUG_CREATE_ERROR_MSG( STR, 'Unhandled error' )
    END SELECT

    ! Trace end of procedure (on error)
    PP_TRACE_EXIT_PROCEDURE_ON_ERROR()

    ! Write the error message and stop the program
    PP_DEBUG_ABORT( STR )

  END BLOCK ErrorHandler

  ! Exit point on error
  RETURN

END SUBROUTINE ENCODE_TIME_WAM
#undef PP_PROCEDURE_NAME
#undef PP_PROCEDURE_TYPE



#define PP_PROCEDURE_TYPE 'SUBROUTINE'
#define PP_PROCEDURE_NAME 'FINALISE_WAM'
SUBROUTINE FINALISE_WAM( THIS )

  ! Symbols imported by the preprocessor for debugging purposes
  PP_DEBUG_USE_VARS

  ! Symbols imported by the preprocessor for tracing purposes
  PP_TRACE_USE_VARS

IMPLICIT NONE

  ! Dummy arguments
  CLASS(TIME_MANAGER_CONTAINER_WAM_T), INTENT(INOUT) :: THIS

  ! Local variables declared by the preprocessor for debugging purposes
  PP_DEBUG_DECL_VARS

  ! Local variables declared by the preprocessor for tracing purposes
  PP_TRACE_DECL_VARS

  ! Trace begin of procedure
  PP_TRACE_ENTER_PROCEDURE()

  ! Nullify the function pointers
  NULLIFY( THIS%PWAM_ )

  ! Trace end of procedure (on success)
  PP_TRACE_EXIT_PROCEDURE_ON_SUCCESS()

  ! Exit point
  RETURN

END SUBROUTINE FINALISE_WAM
#undef PP_PROCEDURE_NAME
#undef PP_PROCEDURE_TYPE



END MODULE TIME_RUNTIME_UTILS_MOD
#undef PP_SECTION_NAME
#undef PP_SECTION_TYPE
#undef PP_FILE_NAME
