! Include preprocessor utils
#include "output_manager_preprocessor_utils.h"
#include "output_manager_preprocessor_trace_utils.h"
#include "output_manager_preprocessor_logging_utils.h"
#include "output_manager_preprocessor_errhdl_utils.h"


#define PP_FILE_NAME 'levels_utils_mod.F90'
#define PP_SECTION_TYPE 'MODULE'
#define PP_SECTION_NAME 'LEVELS_UTILS_MOD'
MODULE LEVELS_UTILS_MOD

  !> Symbols imported from other modules within the project.
  USE :: GRIB_SECTION_BASE_MOD, ONLY: GRIB_SECTION_BASE_A

IMPLICIT NONE

!> Default visibility
PRIVATE

!> Whitelist of public symbols
PUBLIC :: BAD_INIT_LEVELS
PUBLIC :: CHECK_LEVELS

CONTAINS


#define PP_PROCEDURE_TYPE 'FUNCTION'
#define PP_PROCEDURE_NAME 'BAD_INIT_LEVELS'
PP_THREAD_SAFE FUNCTION BAD_INIT_LEVELS( &
&  METADATA, &
&  HOOKS ) RESULT(RET)

  !> Symbols imported from other modules within the project.
  USE :: DATAKINDS_DEF_MOD, ONLY: JPIB_K
  USE :: METADATA_BASE_MOD, ONLY: METADATA_BASE_A
  USE :: HOOKS_MOD,         ONLY: HOOKS_T

  ! Symbols imported by the preprocessor for debugging purposes
  PP_DEBUG_USE_VARS

  ! Symbols imported by the preprocessor for logging purposes
  PP_LOG_USE_VARS

  ! Symbols imported by the preprocessor for tracing purposes
  PP_TRACE_USE_VARS

IMPLICIT NONE

  !> Dummy arguments
  CLASS(METADATA_BASE_A), POINTER, INTENT(INOUT) :: METADATA
  TYPE(HOOKS_T),                   INTENT(INOUT) :: HOOKS

  !> Function result
  INTEGER(KIND=JPIB_K) :: RET

  ! Local error flags
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_METADATA=1_JPIB_K


  ! Local variables declared by the preprocessor for debugging purposes
  PP_DEBUG_DECL_VARS

  ! Local variables declared by the preprocessor for logging purposes
  PP_LOG_DECL_VARS

  ! Local variables declared by the preprocessor for tracing purposes
  PP_TRACE_DECL_VARS

  ! Trace begin of procedure
  PP_TRACE_ENTER_PROCEDURE()

  ! Initialization of good path return value
  PP_SET_ERR_SUCCESS( RET )

  ! Bad initialization of levels to check if it is fixed by the "typeOfLevel" setter
  PP_METADATA_SET( METADATA, ERRFLAG_METADATA, 'typeOfFirstFixedSurface', 237_JPIB_K )
  PP_METADATA_SET( METADATA, ERRFLAG_METADATA, 'typeOfSecondFixedSurface', 237_JPIB_K )
  PP_METADATA_SET( METADATA, ERRFLAG_METADATA, 'scaledValueOfFirstFixedSurface', 237_JPIB_K)
  PP_METADATA_SET( METADATA, ERRFLAG_METADATA, 'scaledValueOfSecondFixedSurface', 237_JPIB_K )
  PP_METADATA_SET( METADATA, ERRFLAG_METADATA, 'scaleFactorOfFirstFixedSurface', 237_JPIB_K)
  PP_METADATA_SET( METADATA, ERRFLAG_METADATA, 'scaleFactorOfFirstFixedSurface', 237_JPIB_K )

  ! Trace end of procedure (on success)
  PP_TRACE_EXIT_PROCEDURE_ON_SUCCESS()

  ! Exit point (On success)
  RETURN

! Error handler
PP_ERROR_HANDLER

  ! Initialization of bad path return value
  PP_SET_ERR_FAILURE( RET )

#if defined( PP_DEBUG_ENABLE_ERROR_HANDLING )
!$omp critical(ERROR_HANDLER)

  BLOCK

    ! Error handling variables
    PP_DEBUG_PUSH_FRAME()

    ! Handle different errors
    SELECT CASE(ERRIDX)
    CASE ( ERRFLAG_METADATA )
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'unable to set metadata' )
    CASE DEFAULT
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'unhandled error' )
    END SELECT

    ! Trace end of procedure (on error)
    PP_TRACE_EXIT_PROCEDURE_ON_ERROR()

    ! Write the error message and stop the program
    PP_DEBUG_ABORT

  END BLOCK

!$omp end critical(ERROR_HANDLER)
#endif

  ! Exit point (on error)
  RETURN

END FUNCTION BAD_INIT_LEVELS
#undef PP_PROCEDURE_NAME
#undef PP_PROCEDURE_TYPE


#define PP_PROCEDURE_TYPE 'FUNCTION'
#define PP_PROCEDURE_NAME 'CHECK_LEVELS'
PP_THREAD_SAFE FUNCTION CHECK_LEVELS( &
&  METADATA, &
&  TYPE_OF_LEVEL, &
&  TYPE_OF_FIRST_FIXED_SURFACE, &
&  TYPE_OF_SECOND_FIXED_SURFACE, &
&  HOOKS, &
&  SCALED_VALUE_OF_FIRST_FIXED_SURFACES, &
&  SCALE_FACTOR_OF_FIRST_FIXED_SURFACES, &
&  SCALED_VALUE_OF_SECOND_FIXED_SURFACES, &
&  SCALE_FACTOR_OF_SECOND_FIXED_SURFACES, &
&  LEVEL ) RESULT(RET)

  !> Symbols imported from other modules within the project.
  USE :: DATAKINDS_DEF_MOD, ONLY: JPIB_K
  USE :: DATAKINDS_DEF_MOD, ONLY: JPIM_K
  USE :: METADATA_BASE_MOD, ONLY: METADATA_BASE_A
  USE :: GRIB_METADATA_MOD, ONLY: GRIB_METADATA_T
  USE :: HOOKS_MOD,         ONLY: HOOKS_T


  ! Symbols imported from external libraries
  USE :: GRIB_API, ONLY: GRIB_GET
  USE :: GRIB_API, ONLY: GRIB_IS_MISSING
  USE :: GRIB_API, ONLY: GRIB_IS_DEFINED
  USE :: GRIB_API, ONLY: GRIB_SUCCESS

  ! Symbols imported by the preprocessor for debugging purposes
  PP_DEBUG_USE_VARS

  ! Symbols imported by the preprocessor for logging purposes
  PP_LOG_USE_VARS

  ! Symbols imported by the preprocessor for tracing purposes
  PP_TRACE_USE_VARS

IMPLICIT NONE

  !> Dummy arguments
  CLASS(METADATA_BASE_A), POINTER, INTENT(INOUT) :: METADATA
  CHARACTER(LEN=*),                INTENT(IN)    :: TYPE_OF_LEVEL
  INTEGER(KIND=JPIB_K),            INTENT(IN)    :: TYPE_OF_FIRST_FIXED_SURFACE
  INTEGER(KIND=JPIB_K),            INTENT(IN)    :: TYPE_OF_SECOND_FIXED_SURFACE
  TYPE(HOOKS_T),                   INTENT(INOUT) :: HOOKS

  INTEGER(KIND=JPIB_K), OPTIONAL,  INTENT(IN)    :: SCALED_VALUE_OF_FIRST_FIXED_SURFACES
  INTEGER(KIND=JPIB_K), OPTIONAL,  INTENT(IN)    :: SCALE_FACTOR_OF_FIRST_FIXED_SURFACES
  INTEGER(KIND=JPIB_K), OPTIONAL,  INTENT(IN)    :: SCALED_VALUE_OF_SECOND_FIXED_SURFACES
  INTEGER(KIND=JPIB_K), OPTIONAL,  INTENT(IN)    :: SCALE_FACTOR_OF_SECOND_FIXED_SURFACES
  INTEGER(KIND=JPIB_K), OPTIONAL,  INTENT(IN)    :: LEVEL

  !> Function result
  INTEGER(KIND=JPIB_K) :: RET

  ! Local variables
  INTEGER(KIND=JPIM_K) :: HANDLE
  INTEGER(KIND=JPIM_K), DIMENSION(8) :: KRET

  CHARACTER(LEN=128)   :: LOC_TYPE_OF_LEVEL
  INTEGER(KIND=JPIB_K) :: LOC_TYPE_OF_FIRST_FIXED_SURFACE
  INTEGER(KIND=JPIB_K) :: LOC_TYPE_OF_SECOND_FIXED_SURFACE
  INTEGER(KIND=JPIB_K) :: LOC_SCALED_VALUE_OF_FIRST_FIXED_SURFACES
  INTEGER(KIND=JPIB_K) :: LOC_SCALE_FACTOR_OF_FIRST_FIXED_SURFACES
  INTEGER(KIND=JPIB_K) :: LOC_SCALED_VALUE_OF_SECOND_FIXED_SURFACES
  INTEGER(KIND=JPIB_K) :: LOC_SCALE_FACTOR_OF_SECOND_FIXED_SURFACES
  INTEGER(KIND=JPIB_K) :: LOC_LEVEL
  INTEGER(KIND=JPIM_K) :: IS_MISSING
  INTEGER(KIND=JPIM_K) :: STAT
  CHARACTER(LEn=32), DIMENSION(7) :: REF
  CHARACTER(LEn=32), DIMENSION(7) :: GOT


  ! Local error flags
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_GET_HANLDE=1_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_GET_TYPE_OF_LEVEL=2_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_TYPE_OF_LEVEL_NOT_MATCH=3_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_GET_TYPE_FIRST_FIXED_SURFACE=4_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_TYPE_OF_FIRST_FIXED_SURFACE_NOT_MATCH=5_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_GET_TYPE_SECOND_FIXED_SURFACE=6_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_TYPE_OF_SECOND_FIXED_SURFACE_NOT_MATCH=7_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_GET_SCALED_VALUE_FIRST_FIXED_SURFACE=8_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_SCALED_VALUE_FIRST_FIXED_SURFACE_NOT_MATCH=9_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_SCALED_VALUE_FIRST_FIXED_SURFACE_NOT_MISSING=10_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_GET_SCALE_FACTOR_FIRST_FIXED_SURFACE=11_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_SCALE_FACTOR_FIRST_FIXED_SURFACE_NOT_MATCH=12_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_SCALE_FACTOR_FIRST_FIXED_SURFACE_NOT_MISSING=13_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_GET_SCALED_VALUE_SECOND_FIXED_SURFACE=14_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_SCALED_VALUE_SECOND_FIXED_SURFACE_NOT_MATCH=15_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_SCALED_VALUE_SECOND_FIXED_SURFACE_NOT_MISSING=16_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_GET_SCALE_FACTOR_SECOND_FIXED_SURFACE=17_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_SCALE_FACTOR_SECOND_FIXED_SURFACE_NOT_MATCH=18_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_SCALE_FACTOR_SECOND_FIXED_SURFACE_NOT_MISSING=19_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_LEVEL_NOT_MATCH=20_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_LEVEL_NOT_MISSING=21_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_GET_LEVEL=22_JPIB_K


  ! Local variables declared by the preprocessor for debugging purposes
  PP_DEBUG_DECL_VARS

  ! Local variables declared by the preprocessor for logging purposes
  PP_LOG_DECL_VARS

  ! Local variables declared by the preprocessor for tracing purposes
  PP_TRACE_DECL_VARS

  ! Trace begin of procedure
  PP_TRACE_ENTER_PROCEDURE()

  ! Initialization of good path return value
  PP_SET_ERR_SUCCESS( RET )

  SELECT TYPE( GRIB => METADATA)

  CLASS IS (GRIB_METADATA_T)

    ! Get the grib handle from the metadata
    PP_TRYCALL(ERRFLAG_GET_HANLDE) GRIB%GET_HANDLE( HANDLE, HOOKS )

    ! Initialization of local variables
    LOC_TYPE_OF_LEVEL = REPEAT( ' ', 128)
    LOC_TYPE_OF_FIRST_FIXED_SURFACE=-1_JPIB_K
    LOC_TYPE_OF_SECOND_FIXED_SURFACE=-1_JPIB_K
    LOC_SCALED_VALUE_OF_FIRST_FIXED_SURFACES=-1_JPIB_K
    LOC_SCALE_FACTOR_OF_FIRST_FIXED_SURFACES=-1_JPIB_K
    LOC_SCALED_VALUE_OF_SECOND_FIXED_SURFACES=-1_JPIB_K
    LOC_SCALE_FACTOR_OF_SECOND_FIXED_SURFACES=-1_JPIB_K
    LOC_LEVEL=-1_JPIB_K

    ! Read the values from the grib handle
    CALL GRIB_GET( HANDLE, 'typeOfLevel', LOC_TYPE_OF_LEVEL, STATUS=KRET(1) )
    CALL GRIB_GET( HANDLE, 'typeOfFirstFixedSurface', LOC_TYPE_OF_FIRST_FIXED_SURFACE, STATUS=KRET(2) )
    CALL GRIB_GET( HANDLE, 'typeOfSecondFixedSurface', LOC_TYPE_OF_SECOND_FIXED_SURFACE, STATUS=KRET(3) )

    ! Perform checks
    PP_DEBUG_CRITICAL_COND_THROW( KRET(1).NE.GRIB_SUCCESS , ERRFLAG_UNABLE_TO_GET_TYPE_OF_LEVEL )
    PP_DEBUG_CRITICAL_COND_THROW( TRIM(ADJUSTL(LOC_TYPE_OF_LEVEL)) .NE. TRIM(ADJUSTL(TYPE_OF_LEVEL)), ERRFLAG_TYPE_OF_LEVEL_NOT_MATCH )

    ! Check if the first fixed surface is the same
    PP_DEBUG_CRITICAL_COND_THROW( KRET(2).NE.GRIB_SUCCESS , ERRFLAG_UNABLE_TO_GET_TYPE_FIRST_FIXED_SURFACE )
    PP_DEBUG_CRITICAL_COND_THROW( TYPE_OF_FIRST_FIXED_SURFACE .NE. LOC_TYPE_OF_FIRST_FIXED_SURFACE, ERRFLAG_TYPE_OF_FIRST_FIXED_SURFACE_NOT_MATCH )

    ! Check if the second fixed surface is the same
    PP_DEBUG_CRITICAL_COND_THROW( KRET(3).NE.GRIB_SUCCESS , ERRFLAG_UNABLE_TO_GET_TYPE_SECOND_FIXED_SURFACE )
    PP_DEBUG_CRITICAL_COND_THROW( TYPE_OF_SECOND_FIXED_SURFACE .NE. LOC_TYPE_OF_SECOND_FIXED_SURFACE, ERRFLAG_TYPE_OF_SECOND_FIXED_SURFACE_NOT_MATCH )

    ! Check if the scaled value of the first fixed surface is the same
    IF ( PRESENT(SCALED_VALUE_OF_FIRST_FIXED_SURFACES) ) THEN
      CALL GRIB_GET( HANDLE, 'scaledValueOfFirstFixedSurface', LOC_SCALED_VALUE_OF_FIRST_FIXED_SURFACES, STATUS=KRET(4) )
      PP_DEBUG_CRITICAL_COND_THROW( KRET(4).NE.GRIB_SUCCESS , ERRFLAG_UNABLE_TO_GET_SCALED_VALUE_FIRST_FIXED_SURFACE )
      PP_DEBUG_CRITICAL_COND_THROW( SCALED_VALUE_OF_FIRST_FIXED_SURFACES .NE. LOC_SCALED_VALUE_OF_FIRST_FIXED_SURFACES, ERRFLAG_SCALED_VALUE_FIRST_FIXED_SURFACE_NOT_MATCH )
    ELSE
      CALL GRIB_IS_MISSING( HANDLE, 'scaledValueOfFirstFixedSurface', IS_MISSING, STATUS=KRET(4) )
      PP_DEBUG_CRITICAL_COND_THROW( KRET(4).NE.GRIB_SUCCESS , ERRFLAG_UNABLE_TO_GET_SCALED_VALUE_FIRST_FIXED_SURFACE )
      IF ( IS_MISSING .EQ. 0 ) THEN
        CALL GRIB_GET( HANDLE, 'scaledValueOfFirstFixedSurface', LOC_SCALED_VALUE_OF_FIRST_FIXED_SURFACES, STATUS=KRET(4) )
        PP_DEBUG_CRITICAL_COND_THROW( KRET(4).NE.GRIB_SUCCESS , ERRFLAG_UNABLE_TO_GET_SCALED_VALUE_FIRST_FIXED_SURFACE )
        PP_DEBUG_CRITICAL_THROW( ERRFLAG_SCALED_VALUE_FIRST_FIXED_SURFACE_NOT_MISSING )
      ENDIF
    ENDIF

    ! Check if the scale factor of the first fixed surface is the same
    IF ( PRESENT(SCALE_FACTOR_OF_FIRST_FIXED_SURFACES) ) THEN
      CALL GRIB_GET( HANDLE, 'scaleFactorOfFirstFixedSurface', LOC_SCALE_FACTOR_OF_FIRST_FIXED_SURFACES, STATUS=KRET(5) )
      PP_DEBUG_CRITICAL_COND_THROW( KRET(5).NE.GRIB_SUCCESS , ERRFLAG_UNABLE_TO_GET_SCALE_FACTOR_FIRST_FIXED_SURFACE )
      PP_DEBUG_CRITICAL_COND_THROW( SCALE_FACTOR_OF_FIRST_FIXED_SURFACES .NE. LOC_SCALE_FACTOR_OF_FIRST_FIXED_SURFACES, ERRFLAG_SCALE_FACTOR_FIRST_FIXED_SURFACE_NOT_MATCH )
    ELSE
      CALL GRIB_IS_MISSING( HANDLE, 'scaleFactorOfFirstFixedSurface', IS_MISSING, STATUS=KRET(5) )
      PP_DEBUG_CRITICAL_COND_THROW( KRET(5).NE.GRIB_SUCCESS , ERRFLAG_UNABLE_TO_GET_SCALE_FACTOR_FIRST_FIXED_SURFACE )
      IF ( IS_MISSING .EQ. 0 ) THEN
        CALL GRIB_GET( HANDLE, 'scaleFactorOfFirstFixedSurface', LOC_SCALE_FACTOR_OF_FIRST_FIXED_SURFACES, STATUS=KRET(5) )
        PP_DEBUG_CRITICAL_COND_THROW( KRET(5).NE.GRIB_SUCCESS , ERRFLAG_UNABLE_TO_GET_SCALE_FACTOR_FIRST_FIXED_SURFACE )
        PP_DEBUG_CRITICAL_THROW( ERRFLAG_SCALE_FACTOR_FIRST_FIXED_SURFACE_NOT_MISSING )
      ENDIF
    ENDIF

    ! Check if the scaled value of the second fixed surface is the same
    IF ( PRESENT(SCALED_VALUE_OF_SECOND_FIXED_SURFACES) ) THEN
      CALL GRIB_GET( HANDLE, 'scaledValueOfSecondFixedSurface', LOC_SCALED_VALUE_OF_SECOND_FIXED_SURFACES, STATUS=KRET(6) )
      PP_DEBUG_CRITICAL_COND_THROW( KRET(6).NE.GRIB_SUCCESS , ERRFLAG_UNABLE_TO_GET_SCALED_VALUE_SECOND_FIXED_SURFACE )
      PP_DEBUG_CRITICAL_COND_THROW( SCALED_VALUE_OF_SECOND_FIXED_SURFACES .NE. LOC_SCALED_VALUE_OF_SECOND_FIXED_SURFACES, ERRFLAG_SCALED_VALUE_SECOND_FIXED_SURFACE_NOT_MATCH )
    ELSE
      CALL GRIB_IS_MISSING( HANDLE, 'scaledValueOfSecondFixedSurface', IS_MISSING, STATUS=KRET(6) )
      PP_DEBUG_CRITICAL_COND_THROW( KRET(6).NE.GRIB_SUCCESS , ERRFLAG_UNABLE_TO_GET_SCALED_VALUE_SECOND_FIXED_SURFACE )
      IF ( IS_MISSING .EQ. 0 ) THEN
        CALL GRIB_GET( HANDLE, 'scaledValueOfSecondFixedSurface', LOC_SCALED_VALUE_OF_SECOND_FIXED_SURFACES, STATUS=KRET(6) )
        PP_DEBUG_CRITICAL_COND_THROW( KRET(6).NE.GRIB_SUCCESS , ERRFLAG_UNABLE_TO_GET_SCALED_VALUE_SECOND_FIXED_SURFACE )
        PP_DEBUG_CRITICAL_THROW( ERRFLAG_SCALED_VALUE_SECOND_FIXED_SURFACE_NOT_MISSING )
      ENDIF
    ENDIF

    ! Check if the scale factor of the second fixed surface is the same
    IF ( PRESENT(SCALE_FACTOR_OF_SECOND_FIXED_SURFACES) ) THEN
      CALL GRIB_GET( HANDLE, 'scaleFactorOfSecondFixedSurface', LOC_SCALE_FACTOR_OF_SECOND_FIXED_SURFACES, STATUS=KRET(7) )
      PP_DEBUG_CRITICAL_COND_THROW( KRET(7).NE.GRIB_SUCCESS , ERRFLAG_UNABLE_TO_GET_SCALE_FACTOR_SECOND_FIXED_SURFACE )
      PP_DEBUG_CRITICAL_COND_THROW( SCALE_FACTOR_OF_SECOND_FIXED_SURFACES .NE. LOC_SCALE_FACTOR_OF_SECOND_FIXED_SURFACES, ERRFLAG_SCALE_FACTOR_SECOND_FIXED_SURFACE_NOT_MATCH )
    ELSE
      CALL GRIB_IS_MISSING( HANDLE, 'scaleFactorOfSecondFixedSurface', IS_MISSING, STATUS=KRET(7) )
      PP_DEBUG_CRITICAL_COND_THROW( KRET(7).NE.GRIB_SUCCESS , ERRFLAG_UNABLE_TO_GET_SCALE_FACTOR_SECOND_FIXED_SURFACE )
      IF ( IS_MISSING .EQ. 0 ) THEN
        CALL GRIB_GET( HANDLE, 'scaleFactorOfSecondFixedSurface', LOC_SCALE_FACTOR_OF_SECOND_FIXED_SURFACES, STATUS=KRET(7) )
        PP_DEBUG_CRITICAL_COND_THROW( KRET(7).NE.GRIB_SUCCESS , ERRFLAG_UNABLE_TO_GET_SCALE_FACTOR_SECOND_FIXED_SURFACE )
        PP_DEBUG_CRITICAL_THROW( ERRFLAG_SCALE_FACTOR_SECOND_FIXED_SURFACE_NOT_MISSING )
      ENDIF
    ENDIF

    ! Check if the level is the same
    IF ( PRESENT(LEVEL) ) THEN
      CALL GRIB_GET( HANDLE, 'level', LOC_LEVEL, STATUS=KRET(8) )
      PP_DEBUG_CRITICAL_COND_THROW( KRET(8).NE.GRIB_SUCCESS , ERRFLAG_UNABLE_TO_GET_LEVEL )
      PP_DEBUG_CRITICAL_COND_THROW( LEVEL .NE. LOC_LEVEL, ERRFLAG_LEVEL_NOT_MATCH )
    ELSE
      PP_DEBUG_CRITICAL_COND_THROW( KRET(8).EQ.GRIB_SUCCESS , ERRFLAG_LEVEL_NOT_MISSING )
    ENDIF

  END SELECT

  ! Trace end of procedure (on success)
  PP_TRACE_EXIT_PROCEDURE_ON_SUCCESS()

  ! Exit point (On success)
  RETURN

! Error handler
PP_ERROR_HANDLER

  ! Initialization of bad path return value
  PP_SET_ERR_FAILURE( RET )

#if defined( PP_DEBUG_ENABLE_ERROR_HANDLING )
!$omp critical(ERROR_HANDLER)

  BLOCK

    CHARACTER(LEN=32) :: TMP1
    CHARACTER(LEN=32) :: TMP2

    ! Error handling variables
    PP_DEBUG_PUSH_FRAME()

    ! Handle different errors
    SELECT CASE(ERRIDX)
    CASE ( ERRFLAG_GET_HANLDE )
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'unable to get the grib handle' )
    CASE ( ERRFLAG_UNABLE_TO_GET_TYPE_OF_LEVEL )
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'unable to get the type of level' )
    CASE ( ERRFLAG_TYPE_OF_LEVEL_NOT_MATCH )
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'type of level does not match' )
    CASE ( ERRFLAG_UNABLE_TO_GET_TYPE_FIRST_FIXED_SURFACE )
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'unable to get the type of first fixed surface' )
    CASE ( ERRFLAG_TYPE_OF_FIRST_FIXED_SURFACE_NOT_MATCH )
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'type of first fixed surface does not match' )
    CASE ( ERRFLAG_UNABLE_TO_GET_TYPE_SECOND_FIXED_SURFACE )
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'unable to get the type of second fixed surface' )
    CASE ( ERRFLAG_TYPE_OF_SECOND_FIXED_SURFACE_NOT_MATCH )
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'type of second fixed surface does not match' )
    CASE ( ERRFLAG_UNABLE_TO_GET_SCALED_VALUE_FIRST_FIXED_SURFACE )
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'unable to get the scaled value of first fixed surface' )
    CASE ( ERRFLAG_SCALED_VALUE_FIRST_FIXED_SURFACE_NOT_MATCH )
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'scaled value of first fixed surface does not match' )
      WRITE(TMP1,*,IOSTAT=STAT) LOC_SCALED_VALUE_OF_FIRST_FIXED_SURFACES
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'got: '//TRIM(ADJUSTL(TMP1)) )
      IF ( PRESENT(SCALED_VALUE_OF_FIRST_FIXED_SURFACES) ) THEN
        WRITE(TMP2,*,IOSTAT=STAT) SCALED_VALUE_OF_FIRST_FIXED_SURFACES
        PP_DEBUG_PUSH_MSG_TO_FRAME( 'expect: '//TRIM(ADJUSTL(TMP2)) )
      ENDIF
    CASE ( ERRFLAG_SCALED_VALUE_FIRST_FIXED_SURFACE_NOT_MISSING )
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'scaled value of first fixed surface is NOT missing as expected' )
      WRITE(TMP1,*,IOSTAT=STAT) LOC_SCALED_VALUE_OF_FIRST_FIXED_SURFACES
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'got:      '//TRIM(ADJUSTL(TMP1)) )
    CASE ( ERRFLAG_UNABLE_TO_GET_SCALE_FACTOR_FIRST_FIXED_SURFACE )
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'unable to get the scale factor of first fixed surface' )
    CASE ( ERRFLAG_SCALE_FACTOR_FIRST_FIXED_SURFACE_NOT_MATCH )
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'scale factor of first fixed surface does not match' )
      WRITE(TMP1,*,IOSTAT=STAT) LOC_SCALE_FACTOR_OF_FIRST_FIXED_SURFACES
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'got:      '//TRIM(ADJUSTL(TMP1)) )
      IF ( PRESENT(SCALE_FACTOR_OF_FIRST_FIXED_SURFACES) ) THEN
        WRITE(TMP2,*,IOSTAT=STAT) SCALE_FACTOR_OF_FIRST_FIXED_SURFACES
        PP_DEBUG_PUSH_MSG_TO_FRAME( 'expect: '//TRIM(ADJUSTL(TMP2)) )
      ENDIF
    CASE ( ERRFLAG_SCALE_FACTOR_FIRST_FIXED_SURFACE_NOT_MISSING )
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'scale factor of first fixed surface is NOT missing as expected' )
      WRITE(TMP1,*,IOSTAT=STAT) LOC_SCALE_FACTOR_OF_FIRST_FIXED_SURFACES
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'got: '//TRIM(ADJUSTL(TMP1)) )
    CASE ( ERRFLAG_UNABLE_TO_GET_SCALED_VALUE_SECOND_FIXED_SURFACE )
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'unable to get the scaled value of second fixed surface' )
    CASE ( ERRFLAG_SCALED_VALUE_SECOND_FIXED_SURFACE_NOT_MATCH )
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'scaled value of second fixed surface does not match' )
      WRITE(TMP1,*,IOSTAT=STAT) LOC_SCALED_VALUE_OF_SECOND_FIXED_SURFACES
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'got:      '//TRIM(ADJUSTL(TMP1)) )
      IF ( PRESENT(SCALED_VALUE_OF_SECOND_FIXED_SURFACES) ) THEN
        WRITE(TMP2,*,IOSTAT=STAT) SCALED_VALUE_OF_SECOND_FIXED_SURFACES
        PP_DEBUG_PUSH_MSG_TO_FRAME( 'expect: '//TRIM(ADJUSTL(TMP2)) )
      ENDIF
    CASE ( ERRFLAG_SCALED_VALUE_SECOND_FIXED_SURFACE_NOT_MISSING )
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'scaled value of second fixed surface is NOT missing as expected' )
      WRITE(TMP1,*,IOSTAT=STAT) LOC_SCALED_VALUE_OF_SECOND_FIXED_SURFACES
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'got: '//TRIM(ADJUSTL(TMP1)) )
    CASE ( ERRFLAG_UNABLE_TO_GET_SCALE_FACTOR_SECOND_FIXED_SURFACE )
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'unable to get the scale factor of second fixed surface' )
    CASE ( ERRFLAG_SCALE_FACTOR_SECOND_FIXED_SURFACE_NOT_MATCH )
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'scale factor of second fixed surface does not match' )
      WRITE(TMP1,*,IOSTAT=STAT) LOC_SCALE_FACTOR_OF_SECOND_FIXED_SURFACES
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'got:      '//TRIM(ADJUSTL(TMP1)) )
      IF ( PRESENT(SCALE_FACTOR_OF_SECOND_FIXED_SURFACES) ) THEN
        WRITE(TMP2,*,IOSTAT=STAT) SCALE_FACTOR_OF_SECOND_FIXED_SURFACES
        PP_DEBUG_PUSH_MSG_TO_FRAME( 'expect: '//TRIM(ADJUSTL(TMP2)) )
      ENDIF
    CASE ( ERRFLAG_SCALE_FACTOR_SECOND_FIXED_SURFACE_NOT_MISSING )
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'scaled factor of second fixed surface is NOT missing as expected' )
      WRITE(TMP1,*,IOSTAT=STAT) LOC_SCALE_FACTOR_OF_SECOND_FIXED_SURFACES
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'got: '//TRIM(ADJUSTL(TMP1)) )
    CASE ( ERRFLAG_LEVEL_NOT_MATCH )
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'level does not match' )
      WRITE(TMP1,*,IOSTAT=STAT) LOC_LEVEL
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'got:      '//TRIM(ADJUSTL(TMP1)) )
      IF ( PRESENT(LEVEL) ) THEN
        WRITE(TMP2,*,IOSTAT=STAT) LEVEL
        PP_DEBUG_PUSH_MSG_TO_FRAME( 'expect: '//TRIM(ADJUSTL(TMP2)) )
      ENDIF
    CASE ( ERRFLAG_LEVEL_NOT_MISSING )
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'level is missing' )
    CASE ( ERRFLAG_UNABLE_TO_GET_LEVEL )
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'unable to get the level' )
    CASE DEFAULT
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'unhandled error' )
    END SELECT

    ! Trace end of procedure (on error)
    PP_TRACE_EXIT_PROCEDURE_ON_ERROR()

    ! Write the error message and stop the program
    PP_DEBUG_ABORT

  END BLOCK

!$omp end critical(ERROR_HANDLER)
#endif

  ! Exit point (on error)
  RETURN

END FUNCTION CHECK_LEVELS
#undef PP_PROCEDURE_NAME
#undef PP_PROCEDURE_TYPE


END MODULE LEVELS_UTILS_MOD
#undef PP_SECTION_NAME
#undef PP_SECTION_TYPE
#undef PP_FILE_NAME
