PROGRAM YAML_PARSER_PROG

  ! USE :: RULES_MOD
  USE :: YAML_RULES_MOD,  ONLY: DEFINITIONS_T
  USE :: YAML_RULES_MOD,  ONLY: INIT_RULES
  USE :: YAML_RULES_MOD,  ONLY: MATCH_RULES
  USE :: YAML_RULES_MOD,  ONLY: FREE_RULES
  USE :: OM_API_MOD, ONLY: JPIB_K


  USE :: FCKIT_PATHNAME_MODULE,      ONLY: FCKIT_PATHNAME
  USE :: FCKIT_CONFIGURATION_MODULE, ONLY: FCKIT_YAMLCONFIGURATION
  USE :: FCKIT_CONFIGURATION_MODULE, ONLY: FCKIT_CONFIGURATION

IMPLICIT NONE

  TYPE(FCKIT_CONFIGURATION) :: CFG
  TYPE(DEFINITIONS_T) :: DEF


  WRITE(*,*) 'parser 01'

  ! Open the filename
  CFG = FCKIT_YAMLCONFIGURATION( FCKIT_PATHNAME( './test.yaml' ) )


  WRITE(*,*) 'parser 02'

  CALL INIT_RULES( CFG, .TRUE. )


  WRITE(*,*) 'parser 03'

  CALL MATCH_RULES( 76_JPIB_K, 2_JPIB_K, 1_JPIB_K, 577_JPIB_K, DEF )


  WRITE(*,*) 'parser 04'

  CALL FREE_RULES()

  WRITE(*,*) 'parser 05'

  CALL CFG%FINAL()

  WRITE(*,*) 'parser 06'

  WRITE(*,*) 'Done'

  RETURN

END PROGRAM YAML_PARSER_PROG
