# flake8: noqa: F401

"""
Multiopython
"""

from . import plans
from .lib import MultioException
from .metadata import Metadata
from .multio import Multio
from .utils import MultioPlan

try:
    # NOTE: the `version.py` file must not be present in the git repository
    #   as it is generated by setuptools at install time
    from ._version import __version__
except ImportError:  # pragma: no cover
    # Local copy or not installed with setuptools
    __version__ = "999"
