! Include preprocessor utils
#include "output_manager_preprocessor_utils.h"
#include "output_manager_preprocessor_trace_utils.h"
#include "output_manager_preprocessor_logging_utils.h"
#include "output_manager_preprocessor_errhdl_utils.h"


#define PP_FILE_NAME 'record_base_mod.F90'
#define PP_SECTION_TYPE 'MODULE'
#define PP_SECTION_NAME 'RECORD_BASE_MOD'
MODULE RECORD_BASE_MOD

  !> Symbols imported from other modules within the project.
  USE :: DATAKINDS_DEF_MOD, ONLY: JPIB_K

IMPLICIT NONE

!> Default visibility of the module members
PRIVATE

TYPE :: RECORD_COLLECTION_T
  CHARACTER(LEN=128) :: NAME_= REPEAT( ' ', 16 )
  CLASS(RECORD_BASE_A), ALLOCATABLE :: RECORD_ => NULL()
END TYPE


TYPE, ABSTRACT :: RECORD_BASE_A

  !> Symbols imported from other modules within the project.
  LOGICAL :: INITIALIZED_ = .FALSE.

  !> Value

CONTAINS

  PROCEDURE(RECORD_INIT_IF), DEFERRED, PASS, PUBLIC :: INIT

  PROCEDURE(RECORD_HAS_IF),   DEFERRED, PASS, PUBLIC :: HAS
  PROCEDURE(RECORD_CHECK_IF), DEFERRED, PASS, PUBLIC :: CHECK
  PROCEDURE(RECORD_RESET_IF), DEFERRED, PASS, PUBLIC :: RESET

  PROCEDURE(RECORD_SET_STRING_IF), DEFERRED, PASS, PUBLIC :: SET_STRING
  PROCEDURE(RECORD_SET_BOOL_IF),   DEFERRED, PASS, PUBLIC :: SET_BOOL
  PROCEDURE(RECORD_SET_INT8_IF),   DEFERRED, PASS, PUBLIC :: SET_INT8
  PROCEDURE(RECORD_SET_INT16_IF),  DEFERRED, PASS, PUBLIC :: SET_INT16
  PROCEDURE(RECORD_SET_INT32_IF),  DEFERRED, PASS, PUBLIC :: SET_INT32
  PROCEDURE(RECORD_SET_INT64_IF),  DEFERRED, PASS, PUBLIC :: SET_INT64
  PROCEDURE(RECORD_SET_REAL32_IF), DEFERRED, PASS, PUBLIC :: SET_REAL32
  PROCEDURE(RECORD_SET_REAL64_IF), DEFERRED, PASS, PUBLIC :: SET_REAL64

  PROCEDURE(RECORD_GET_STRING_IF), DEFERRED, PASS, PUBLIC :: GET_STRING
  PROCEDURE(RECORD_GET_BOOL_IF),   DEFERRED, PASS, PUBLIC :: GET_BOOL
  PROCEDURE(RECORD_GET_INT8_IF),   DEFERRED, PASS, PUBLIC :: GET_INT8
  PROCEDURE(RECORD_GET_INT16_IF),  DEFERRED, PASS, PUBLIC :: GET_INT16
  PROCEDURE(RECORD_GET_INT32_IF),  DEFERRED, PASS, PUBLIC :: GET_INT32
  PROCEDURE(RECORD_GET_INT64_IF),  DEFERRED, PASS, PUBLIC :: GET_INT64
  PROCEDURE(RECORD_GET_REAL32_IF), DEFERRED, PASS, PUBLIC :: GET_REAL32
  PROCEDURE(RECORD_GET_REAL64_IF), DEFERRED, PASS, PUBLIC :: GET_REAL64

  PROCEDURE(RECORD_TO_JSON_IF), DEFERRED, PASS, PUBLIC :: TO_JSON
  PROCEDURE(RECORD_TO_YAML_IF), DEFERRED, PASS, PUBLIC :: TO_YAML

  PROCEDURE(RECORD_FROM_JSON_IF), DEFERRED, PASS, PUBLIC :: FROM_JSON
  PROCEDURE(RECORD_FROM_YAML_IF), DEFERRED, PASS, PUBLIC :: FROM_YAML

  PROCEDURE(RECORD_FREE_IF), DEFERRED, PASS, PUBLIC :: FREE

END TYPE


ABSTRACT INTERFACE

PP_THREAD_SAFE FUNCTION RECORD_INIT_IF( THIS, HOOKS ) RESULT(RET)

  !> Symbols imported from other modules within the project.
  USE :: DATAKINDS_DEF_MOD, ONLY: JPIB_K
  USE :: HOOKS_MOD,         ONLY: HOOKS_T

  ! Imported abstract class
  IMPORT :: RECORD_BASE_A

IMPLICIT NONE

  !> Dummy arguments
  CLASS(GRIB_SECTION_BASE_A), INTENT(INOUT) :: THIS
  TYPE(HOOKS_T),              INTENT(INOUT) :: HOOKS

  !> Function result
  INTEGER(KIND=JPIB_K) :: RET

END FUNCTION RECORD_INIT_IF



PP_THREAD_SAFE FUNCTION RECORD_FREE_IF( THIS, HOOKS ) RESULT(RET)

  !> Symbols imported from other modules within the project.
  USE :: DATAKINDS_DEF_MOD, ONLY: JPIB_K
  USE :: HOOKS_MOD,         ONLY: HOOKS_T

  ! Imported abstract class
  IMPORT :: RECORD_BASE_A

IMPLICIT NONE

  !> Dummy arguments
  CLASS(GRIB_SECTION_BASE_A), INTENT(INOUT) :: THIS
  TYPE(HOOKS_T),              INTENT(INOUT) :: HOOKS

  !> Function result
  INTEGER(KIND=JPIB_K) :: RET

END FUNCTION RECORD_FREE_IF



END INTERFACE

!> Whitelist of public symbols (Interfaces)
PUBLIC :: RECORD_BASE_A

END MODULE RECORD_BASE_MOD
#undef PP_SECTION_NAME
#undef PP_SECTION_TYPE
#undef PP_FILE_NAME
