MODULE OM_API_MOD

  ! Data kind
  USE :: OM_CORE_MOD, ONLY: JPIM_K
  USE :: OM_CORE_MOD, ONLY: JPIB_K
  USE :: OM_CORE_MOD, ONLY: JPRM_K
  USE :: OM_CORE_MOD, ONLY: JPRD_K
  USE :: OM_CORE_MOD, ONLY: JPTR_K
  USE :: OM_CORE_MOD, ONLY: ATM_MSG_E
  USE :: OM_CORE_MOD, ONLY: WAM_MSG_E
  USE :: OM_CORE_MOD, ONLY: VALUES_SP_E
  USE :: OM_CORE_MOD, ONLY: VALUES_DP_E
  USE :: OM_CORE_MOD, ONLY: REPRES_GRIDDED_E
  USE :: OM_CORE_MOD, ONLY: REPRES_SPECTRAL_E

  ! Datatypes
  USE :: OM_CORE_MOD, ONLY: PROC_TOPO_T
  USE :: OM_CORE_MOD, ONLY: MODEL_PAR_T
  USE :: OM_CORE_MOD, ONLY: MODEL_PAR_SERIAL_T
  USE :: OM_CORE_MOD, ONLY: OM_BASE_MSG_A
  USE :: OM_CORE_MOD, ONLY: OM_ATM_MSG_T
  USE :: OM_CORE_MOD, ONLY: OM_WAM_MSG_T

  ! Utils
  USE :: OM_CORE_MOD, ONLY: CHECK_REAL_KIND
  USE :: OM_CORE_MOD, ONLY: OM_SET_ABORT_PROCEDURE
  USE :: OM_CORE_MOD, ONLY: OM_SET_ERROR_UNIT
  USE :: OM_CORE_MOD, ONLY: OM_SET_DR_HOOK

  ! USE :: PAR_UTILS_MOD, ONLY: PAR_READ
  ! USE :: MSG_UTILS_MOD, ONLY: READ_MSG
  ! USE :: MSG_UTILS_MOD, ONLY: FREE_MSG

  ! Parameters utils
  USE :: PAR_UTILS_MOD, ONLY: PAR_CREATE_NAME
  USE :: PAR_UTILS_MOD, ONLY: PAR_ROPEN
  USE :: PAR_UTILS_MOD, ONLY: PAR_CLOSE
  USE :: PAR_UTILS_MOD, ONLY: PAR_PRINT
  USE :: PAR_UTILS_MOD, ONLY: PAR_READ
  USE :: PAR_UTILS_MOD, ONLY: PAR_SERIALIZE
  USE :: PAR_UTILS_MOD, ONLY: PAR_DESERIALIZE

  ! Message utils
  USE :: MSG_UTILS_MOD, ONLY: CPREF2IPREF
  USE :: MSG_UTILS_MOD, ONLY: IPREF2MSGTYPE
  USE :: MSG_UTILS_MOD, ONLY: IPREFIX2ILEVTYPE
  USE :: MSG_UTILS_MOD, ONLY: CLEVTYPE2ILEVTYPE
  USE :: MSG_UTILS_MOD, ONLY: ILEVTYPE2CLEVTYPE
  USE :: MSG_UTILS_MOD, ONLY: IREPRES2CREPRES

  USE :: MSG_UTILS_MOD, ONLY: MSG_CREATE_NAME
  USE :: MSG_UTILS_MOD, ONLY: MSG_ROPEN
  USE :: MSG_UTILS_MOD, ONLY: MSG_CLOSE
  USE :: MSG_UTILS_MOD, ONLY: MSG_PRINT_ATM
  USE :: MSG_UTILS_MOD, ONLY: MSG_PRINT_WAM
  USE :: MSG_UTILS_MOD, ONLY: MSG_READ_ATM
  USE :: MSG_UTILS_MOD, ONLY: MSG_READ_WAM

  ! Values utils
  USE :: VAL_UTILS_MOD, ONLY: VAL_CREATE_NAME
  USE :: VAL_UTILS_MOD, ONLY: VAL_ROPEN
  USE :: VAL_UTILS_MOD, ONLY: VAL_CLOSE
  USE :: VAL_UTILS_MOD, ONLY: VAL_WRITE_SP
  USE :: VAL_UTILS_MOD, ONLY: VAL_WRITE_DP
  USE :: VAL_UTILS_MOD, ONLY: VAL_READ_SP
  USE :: VAL_UTILS_MOD, ONLY: VAL_READ_DP
  USE :: VAL_UTILS_MOD, ONLY: VAL_GENERATE_SP
  USE :: VAL_UTILS_MOD, ONLY: VAL_GENERATE_DP


  USE :: OUTPUT_MANAGER_FACTORY_MOD, ONLY: OUTPUT_MANAGER_BASE_A
  USE :: OUTPUT_MANAGER_FACTORY_MOD, ONLY: MAKE_OUTPUT_MANAGER
  USE :: OUTPUT_MANAGER_FACTORY_MOD, ONLY: DESTROY_OUTPUT_MANAGER

  USE :: TOC_UTILS_MOD, ONLY: TOC_CONTAINER_T
  USE :: TOC_UTILS_MOD, ONLY: TOC_ENTRY_BASE_T
  USE :: TOC_UTILS_MOD, ONLY: TOC_SIM_INIT_T
  USE :: TOC_UTILS_MOD, ONLY: TOC_ATM_FIELD_T
  USE :: TOC_UTILS_MOD, ONLY: TOC_WAM_FIELD_T
  USE :: TOC_UTILS_MOD, ONLY: TOC_FLUSH_STEP_T
  USE :: TOC_UTILS_MOD, ONLY: TOC_FLUSH_STEP_RST_T
  USE :: TOC_UTILS_MOD, ONLY: TOC_FLUSH_LAST_STEP_T
  USE :: TOC_UTILS_MOD, ONLY: TOC_SIM_END_T
  USE :: TOC_UTILS_MOD, ONLY: TOC_READ
  USE :: TOC_UTILS_MOD, ONLY: TOC_READ_ALL
  USE :: TOC_UTILS_MOD, ONLY: TOC_FREE
  USE :: TOC_UTILS_MOD, ONLY: TOC_CREATE_NAME

  USE :: OM_GENERAL_UTILS_MOD, ONLY: OM_READ_TYPE_FROM_ENV
  USE :: OM_GENERAL_UTILS_MOD, ONLY: OM_READ_YAML_FROM_ENV

  USE :: PACKAGING_RUNTIME_UTILS_MOD, ONLY: NEED_FIT_SPECTRUM

  USE :: MAP_MOD, ONLY: MAP_T
  USE :: MAP_MOD, ONLY: KEY_T
  USE :: MAP_MOD, ONLY: MAP_INIT
  USE :: MAP_MOD, ONLY: MAP_GET
  USE :: MAP_MOD, ONLY: MAP_INSERT
  USE :: MAP_MOD, ONLY: MAP_GET_SORTED_KEYS_INT
  USE :: MAP_MOD, ONLY: MAP_FREE


IMPLICIT NONE

! Default visibility
PRIVATE

! Whitelist of public symbols (datakinds)
PUBLIC :: JPIM_K
PUBLIC :: JPIB_K
PUBLIC :: JPRM_K
PUBLIC :: JPRD_K
PUBLIC :: JPTR_K


! Whitelist of public symbols (datatypes)
PUBLIC :: PROC_TOPO_T
PUBLIC :: MODEL_PAR_T
PUBLIC :: MODEL_PAR_SERIAL_T
PUBLIC :: OM_BASE_MSG_A
PUBLIC :: OM_ATM_MSG_T
PUBLIC :: OM_WAM_MSG_T

! Whitelise of public symbols (enumerators)
PUBLIC :: ATM_MSG_E
PUBLIC :: WAM_MSG_E
PUBLIC :: REPRES_GRIDDED_E
PUBLIC :: REPRES_SPECTRAL_E
PUBLIC :: VALUES_SP_E
PUBLIC :: VALUES_DP_E

! Whitelist of public symbols (procedures)
PUBLIC :: OUTPUT_MANAGER_BASE_A
PUBLIC :: MAKE_OUTPUT_MANAGER
PUBLIC :: DESTROY_OUTPUT_MANAGER
PUBLIC :: CHECK_REAL_KIND
PUBLIC :: OM_SET_ABORT_PROCEDURE
PUBLIC :: OM_SET_ERROR_UNIT
PUBLIC :: OM_SET_DR_HOOK

PUBLIC :: TOC_CONTAINER_T
PUBLIC :: TOC_ENTRY_BASE_T
PUBLIC :: TOC_SIM_INIT_T
PUBLIC :: TOC_ATM_FIELD_T
PUBLIC :: TOC_WAM_FIELD_T
PUBLIC :: TOC_FLUSH_STEP_T
PUBLIC :: TOC_FLUSH_STEP_RST_T
PUBLIC :: TOC_FLUSH_LAST_STEP_T
PUBLIC :: TOC_SIM_END_T
PUBLIC :: TOC_READ
PUBLIC :: TOC_READ_ALL
PUBLIC :: TOC_FREE
PUBLIC :: TOC_CREATE_NAME
! PUBLIC :: PAR_READ
! PUBLIC :: OM_READ_MSG
! PUBLIC :: OM_FREE_MSG

! Map utils
PUBLIC :: MAP_T
PUBLIC :: KEY_T
PUBLIC :: MAP_INIT
PUBLIC :: MAP_GET
PUBLIC :: MAP_INSERT
PUBLIC :: MAP_GET_SORTED_KEYS_INT
PUBLIC :: MAP_FREE

! Parameters utils
PUBLIC :: PAR_CREATE_NAME
PUBLIC :: PAR_ROPEN
PUBLIC :: PAR_CLOSE
PUBLIC :: PAR_PRINT
PUBLIC :: PAR_READ
PUBLIC :: PAR_SERIALIZE
PUBLIC :: PAR_DESERIALIZE

! Message utils
PUBLIC :: CPREF2IPREF
PUBLIC :: IPREF2MSGTYPE
PUBLIC :: IPREFIX2ILEVTYPE
PUBLIC :: CLEVTYPE2ILEVTYPE
PUBLIC :: ILEVTYPE2CLEVTYPE
PUBLIC :: IREPRES2CREPRES
PUBLIC :: MSG_CREATE_NAME
PUBLIC :: MSG_ROPEN
PUBLIC :: MSG_CLOSE
PUBLIC :: MSG_PRINT_ATM
PUBLIC :: MSG_PRINT_WAM
PUBLIC :: MSG_READ_ATM
PUBLIC :: MSG_READ_WAM

  ! Values utils
PUBLIC :: VAL_CREATE_NAME
PUBLIC :: VAL_ROPEN
PUBLIC :: VAL_CLOSE
PUBLIC :: VAL_WRITE_SP
PUBLIC :: VAL_WRITE_DP
PUBLIC :: VAL_READ_SP
PUBLIC :: VAL_READ_DP
PUBLIC :: VAL_GENERATE_SP
PUBLIC :: VAL_GENERATE_DP

PUBLIC :: OM_READ_TYPE_FROM_ENV
PUBLIC :: OM_READ_YAML_FROM_ENV
PUBLIC :: NEED_FIT_SPECTRUM

END MODULE OM_API_MOD