build: testMultioGrib2.cpp
	clang++ --std=c++17 -O3 testMultioGrib2.cpp -o testMultioGrib2

debug: testMultioGrib2.cpp
	clang++ --std=c++17 -g -O0 testMultioGrib2.cpp -o testMultioGrib2
	lldb testMultioGrib2
