
#pragma once

// This file is generated from python. Do not touch.

#include <functional>
#include <optional>
#include <sstream>
#include <string>
#include <unordered_map>
#include <variant>


namespace multio::grib2 {

struct Error {
    std::string str;
};


template <typename T>
using Result = std::variant<T, Error>;

enum class KeyType : unsigned int
{
    FloatType,
    IntType,
    StringArrayType,
    FloatArrayType,
    IntArrayType,
    StringType,
};


using Key = std::string;
using KeyList = std::vector<Key>;
struct KeyInfo {
    std::vector<KeyType> types;
    std::optional<KeyList> alternativeKeys;
};
using KeyInfoMap = std::unordered_map<Key, KeyInfo>;
using PdtKeyMap = std::unordered_map<unsigned int, KeyList>;


enum class TimeExtent : unsigned int
{
    None = 0,
    PointInTime,
    TimeRange,
};


enum class TimeFormat : unsigned int
{
    None = 0,
    LocalTime,
};


enum class ForecastType : unsigned int
{
    None = 0,
    Percentile,
    IndividualEnsemble,
    Quantile,
    DerivedEnsemble,
    Categorial,
    Probability,
};


enum class ProductCategory : unsigned int
{
    None = 0,
    CcittIA5,
    PostProcess,
    SpatialStatisticalProcessing,
    Hovmoeller,
    Wave,
    Satellite,
    Radar,
    Partitioned,
    ReferencePeriod,
    Aerosol,
    SpatioTemporalTile,
    Optical,
    CrossSect,
    Chemical,
};


enum class ProductSubCategory : unsigned int
{
    None = 0,
    StatisticalOverLatLong,
    Srcsink,
    SpectraList,
    Distribution,
    Optical,
    OpticalSrcsink,
    SpectraFormula,
    PeriodRange,
    QualityValue,
};


enum class ForecastSubType : unsigned int
{
    None = 0,
    ClusterStatCircular,
    Reforecast,
    ClusterStatRectangular,
};


Result<TimeExtent> parseTimeExtent(std::optional<std::string> val) noexcept {
    static const std::unordered_map<std::string, TimeExtent> map{
        {{"None", TimeExtent::None}, {"pointInTime", TimeExtent::PointInTime}, {"timeRange", TimeExtent::TimeRange}}};

    if (!val) {
        return TimeExtent::None;
    }

    auto it = map.find(*val);
    if (it != map.end()) {
        return it->second;
    }
    return Error{
        std::string("parseTimeExtent(") + *val
        + std::string("): Value for timeExtent does not match on of the following [None, pointInTime, timeRange]")};
}


Result<TimeFormat> parseTimeFormat(std::optional<std::string> val) noexcept {
    static const std::unordered_map<std::string, TimeFormat> map{
        {{"None", TimeFormat::None}, {"localTime", TimeFormat::LocalTime}}};

    if (!val) {
        return TimeFormat::None;
    }

    auto it = map.find(*val);
    if (it != map.end()) {
        return it->second;
    }
    return Error{std::string("parseTimeFormat(") + *val
                 + std::string("): Value for timeFormat does not match on of the following [None, localTime]")};
}


Result<ForecastType> parseForecastType(std::optional<std::string> val) noexcept {
    static const std::unordered_map<std::string, ForecastType> map{
        {{"percentile", ForecastType::Percentile},
         {"individualEnsemble", ForecastType::IndividualEnsemble},
         {"quantile", ForecastType::Quantile},
         {"None", ForecastType::None},
         {"derivedEnsemble", ForecastType::DerivedEnsemble},
         {"categorial", ForecastType::Categorial},
         {"probability", ForecastType::Probability}}};

    if (!val) {
        return ForecastType::None;
    }

    auto it = map.find(*val);
    if (it != map.end()) {
        return it->second;
    }
    return Error{std::string("parseForecastType(") + *val
                 + std::string("): Value for forecastType does not match on of the following [percentile, "
                               "individualEnsemble, quantile, None, derivedEnsemble, categorial, probability]")};
}


Result<ProductCategory> parseProductCategory(std::optional<std::string> val) noexcept {
    static const std::unordered_map<std::string, ProductCategory> map{
        {{"ccittIA5", ProductCategory::CcittIA5},
         {"postProcess", ProductCategory::PostProcess},
         {"spatialStatisticalProcessing", ProductCategory::SpatialStatisticalProcessing},
         {"None", ProductCategory::None},
         {"hovmoeller", ProductCategory::Hovmoeller},
         {"wave", ProductCategory::Wave},
         {"satellite", ProductCategory::Satellite},
         {"radar", ProductCategory::Radar},
         {"partitioned", ProductCategory::Partitioned},
         {"referencePeriod", ProductCategory::ReferencePeriod},
         {"aerosol", ProductCategory::Aerosol},
         {"spatioTemporalTile", ProductCategory::SpatioTemporalTile},
         {"optical", ProductCategory::Optical},
         {"crossSect", ProductCategory::CrossSect},
         {"chemical", ProductCategory::Chemical}}};

    if (!val) {
        return ProductCategory::None;
    }

    auto it = map.find(*val);
    if (it != map.end()) {
        return it->second;
    }
    return Error{
        std::string("parseProductCategory(") + *val
        + std::string("): Value for productCategory does not match on of the following [ccittIA5, postProcess, "
                      "spatialStatisticalProcessing, None, hovmoeller, wave, satellite, radar, partitioned, "
                      "referencePeriod, aerosol, spatioTemporalTile, optical, crossSect, chemical]")};
}


Result<ProductSubCategory> parseProductSubCategory(std::optional<std::string> val) noexcept {
    static const std::unordered_map<std::string, ProductSubCategory> map{
        {{"statisticalOverLatLong", ProductSubCategory::StatisticalOverLatLong},
         {"srcsink", ProductSubCategory::Srcsink},
         {"spectraList", ProductSubCategory::SpectraList},
         {"None", ProductSubCategory::None},
         {"distribution", ProductSubCategory::Distribution},
         {"optical", ProductSubCategory::Optical},
         {"opticalSrcsink", ProductSubCategory::OpticalSrcsink},
         {"spectraFormula", ProductSubCategory::SpectraFormula},
         {"periodRange", ProductSubCategory::PeriodRange},
         {"qualityValue", ProductSubCategory::QualityValue}}};

    if (!val) {
        return ProductSubCategory::None;
    }

    auto it = map.find(*val);
    if (it != map.end()) {
        return it->second;
    }
    return Error{
        std::string("parseProductSubCategory(") + *val
        + std::string(
            "): Value for productSubCategory does not match on of the following [statisticalOverLatLong, srcsink, "
            "spectraList, None, distribution, optical, opticalSrcsink, spectraFormula, periodRange, qualityValue]")};
}


Result<ForecastSubType> parseForecastSubType(std::optional<std::string> val) noexcept {
    static const std::unordered_map<std::string, ForecastSubType> map{
        {{"clusterStatCircular", ForecastSubType::ClusterStatCircular},
         {"None", ForecastSubType::None},
         {"reforecast", ForecastSubType::Reforecast},
         {"clusterStatRectangular", ForecastSubType::ClusterStatRectangular}}};

    if (!val) {
        return ForecastSubType::None;
    }

    auto it = map.find(*val);
    if (it != map.end()) {
        return it->second;
    }
    return Error{std::string("parseForecastSubType(") + *val
                 + std::string("): Value for forecastSubType does not match on of the following [clusterStatCircular, "
                               "None, reforecast, clusterStatRectangular]")};
}


using DecisionMap = std::unordered_map<
    TimeExtent,
    std::unordered_map<
        TimeFormat,
        std::unordered_map<ForecastType,
                           std::unordered_map<ForecastSubType,
                                              std::unordered_map<ProductCategory, std::unordered_map<ProductSubCategory,
                                                                                                     unsigned int>>>>>>;

template <typename LookupValueAsOptString>
Result<unsigned int> inferProductDefinitionTemplateNumber(LookupValueAsOptString&& lookup) noexcept {
    static const DecisionMap map{
        {{TimeExtent::None,
          {{TimeFormat::None,
            {{ForecastType::None,
              {{ForecastSubType::None,
                {{ProductCategory::CcittIA5, {{ProductSubCategory::None, 254}}},
                 {ProductCategory::Satellite, {{ProductSubCategory::None, 31}, {ProductSubCategory::QualityValue, 35}}},
                 {ProductCategory::Radar, {{ProductSubCategory::None, 20}}}}}}}}}}},
         {TimeExtent::PointInTime,
          {{TimeFormat::None,
            {{ForecastType::Percentile,
              {{ForecastSubType::None, {{ProductCategory::None, {{ProductSubCategory::None, 6}}}}}}},
             {ForecastType::IndividualEnsemble,
              {{ForecastSubType::None,
                {{ProductCategory::PostProcess, {{ProductSubCategory::None, 71}}},
                 {ProductCategory::None, {{ProductSubCategory::None, 1}}},
                 {ProductCategory::Wave,
                  {{ProductSubCategory::PeriodRange, 104},
                   {ProductSubCategory::SpectraFormula, 102},
                   {ProductSubCategory::SpectraList, 100}}},
                 {ProductCategory::Satellite, {{ProductSubCategory::None, 33}}},
                 {ProductCategory::Partitioned, {{ProductSubCategory::None, 54}}},
                 {ProductCategory::Aerosol,
                  {{ProductSubCategory::None, 45},
                   {ProductSubCategory::Optical, 49},
                   {ProductSubCategory::OpticalSrcsink, 81}}},
                 {ProductCategory::SpatioTemporalTile, {{ProductSubCategory::None, 59}}},
                 {ProductCategory::Optical, {{ProductSubCategory::None, 109}}},
                 {ProductCategory::Chemical,
                  {{ProductSubCategory::Srcsink, 77},
                   {ProductSubCategory::None, 41},
                   {ProductSubCategory::Distribution, 58}}}}},
               {ForecastSubType::Reforecast, {{ProductCategory::None, {{ProductSubCategory::None, 60}}}}}}},
             {ForecastType::Quantile,
              {{ForecastSubType::None, {{ProductCategory::None, {{ProductSubCategory::None, 86}}}}}}},
             {ForecastType::None,
              {{ForecastSubType::None,
                {{ProductCategory::PostProcess, {{ProductSubCategory::None, 70}}},
                 {ProductCategory::SpatialStatisticalProcessing, {{ProductSubCategory::None, 15}}},
                 {ProductCategory::None, {{ProductSubCategory::None, 0}}},
                 {ProductCategory::Hovmoeller, {{ProductSubCategory::None, 1100}}},
                 {ProductCategory::Wave,
                  {{ProductSubCategory::PeriodRange, 103},
                   {ProductSubCategory::SpectraFormula, 101},
                   {ProductSubCategory::SpectraList, 99}}},
                 {ProductCategory::Satellite, {{ProductSubCategory::None, 32}}},
                 {ProductCategory::Partitioned, {{ProductSubCategory::None, 53}}},
                 {ProductCategory::Aerosol,
                  {{ProductSubCategory::Optical, 48}, {ProductSubCategory::OpticalSrcsink, 80}}},
                 {ProductCategory::SpatioTemporalTile, {{ProductSubCategory::None, 55}}},
                 {ProductCategory::Optical, {{ProductSubCategory::None, 108}}},
                 {ProductCategory::CrossSect,
                  {{ProductSubCategory::StatisticalOverLatLong, 1002}, {ProductSubCategory::None, 1000}}},
                 {ProductCategory::Chemical,
                  {{ProductSubCategory::Srcsink, 76},
                   {ProductSubCategory::None, 40},
                   {ProductSubCategory::Distribution, 57}}}}}}},
             {ForecastType::DerivedEnsemble,
              {{ForecastSubType::ClusterStatCircular, {{ProductCategory::None, {{ProductSubCategory::None, 4}}}}},
               {ForecastSubType::None, {{ProductCategory::None, {{ProductSubCategory::None, 2}}}}},
               {ForecastSubType::ClusterStatRectangular, {{ProductCategory::None, {{ProductSubCategory::None, 3}}}}}}},
             {ForecastType::Categorial,
              {{ForecastSubType::None, {{ProductCategory::None, {{ProductSubCategory::None, 51}}}}}}},
             {ForecastType::Probability,
              {{ForecastSubType::None, {{ProductCategory::None, {{ProductSubCategory::None, 5}}}}}}}}},
           {TimeFormat::LocalTime,
            {{ForecastType::None,
              {{ForecastSubType::None,
                {{ProductCategory::None, {{ProductSubCategory::None, 88}}},
                 {ProductCategory::PostProcess, {{ProductSubCategory::None, 93}}}}}}},
             {ForecastType::IndividualEnsemble,
              {{ForecastSubType::None,
                {{ProductCategory::None, {{ProductSubCategory::None, 92}}},
                 {ProductCategory::PostProcess, {{ProductSubCategory::None, 94}}}}}}}}}}},
         {TimeExtent::TimeRange,
          {{TimeFormat::None,
            {{ForecastType::Percentile,
              {{ForecastSubType::None, {{ProductCategory::None, {{ProductSubCategory::None, 10}}}}}}},
             {ForecastType::IndividualEnsemble,
              {{ForecastSubType::None,
                {{ProductCategory::PostProcess, {{ProductSubCategory::None, 73}}},
                 {ProductCategory::None, {{ProductSubCategory::None, 11}}},
                 {ProductCategory::ReferencePeriod, {{ProductSubCategory::None, 106}}},
                 {ProductCategory::Satellite, {{ProductSubCategory::None, 34}}},
                 {ProductCategory::Aerosol, {{ProductSubCategory::Srcsink, 84}, {ProductSubCategory::None, 85}}},
                 {ProductCategory::SpatioTemporalTile, {{ProductSubCategory::None, 63}}},
                 {ProductCategory::Optical, {{ProductSubCategory::None, 111}}},
                 {ProductCategory::Chemical,
                  {{ProductSubCategory::Srcsink, 79},
                   {ProductSubCategory::None, 43},
                   {ProductSubCategory::Distribution, 68}}}}},
               {ForecastSubType::Reforecast, {{ProductCategory::None, {{ProductSubCategory::None, 61}}}}}}},
             {ForecastType::Quantile,
              {{ForecastSubType::None, {{ProductCategory::None, {{ProductSubCategory::None, 87}}}}}}},
             {ForecastType::None,
              {{ForecastSubType::None,
                {{ProductCategory::PostProcess, {{ProductSubCategory::None, 72}}},
                 {ProductCategory::Hovmoeller, {{ProductSubCategory::None, 1101}}},
                 {ProductCategory::None, {{ProductSubCategory::None, 8}}},
                 {ProductCategory::ReferencePeriod, {{ProductSubCategory::None, 105}}},
                 {ProductCategory::Aerosol, {{ProductSubCategory::Srcsink, 82}, {ProductSubCategory::None, 46}}},
                 {ProductCategory::SpatioTemporalTile, {{ProductSubCategory::None, 62}}},
                 {ProductCategory::Optical, {{ProductSubCategory::None, 110}}},
                 {ProductCategory::CrossSect, {{ProductSubCategory::None, 1001}}},
                 {ProductCategory::Chemical,
                  {{ProductSubCategory::Srcsink, 78},
                   {ProductSubCategory::None, 42},
                   {ProductSubCategory::Distribution, 67}}}}}}},
             {ForecastType::DerivedEnsemble,
              {{ForecastSubType::ClusterStatCircular, {{ProductCategory::None, {{ProductSubCategory::None, 14}}}}},
               {ForecastSubType::None,
                {{ProductCategory::None, {{ProductSubCategory::None, 12}}},
                 {ProductCategory::ReferencePeriod, {{ProductSubCategory::None, 107}}}}},
               {ForecastSubType::ClusterStatRectangular, {{ProductCategory::None, {{ProductSubCategory::None, 13}}}}}}},
             {ForecastType::Categorial,
              {{ForecastSubType::None, {{ProductCategory::None, {{ProductSubCategory::None, 91}}}}}}},
             {ForecastType::Probability,
              {{ForecastSubType::None,
                {{ProductCategory::None, {{ProductSubCategory::None, 9}}},
                 {ProductCategory::ReferencePeriod, {{ProductSubCategory::None, 112}}}}}}}}},
           {TimeFormat::LocalTime,
            {{ForecastType::None,
              {{ForecastSubType::None,
                {{ProductCategory::None, {{ProductSubCategory::None, 95}}},
                 {ProductCategory::PostProcess, {{ProductSubCategory::None, 97}}}}}}},
             {ForecastType::IndividualEnsemble,
              {{ForecastSubType::None,
                {{ProductCategory::None, {{ProductSubCategory::None, 96}}},
                 {ProductCategory::PostProcess, {{ProductSubCategory::None, 98}}}}}}}}}}}}};


    auto timeExtentStr = lookup("timeExtent");
    auto timeExtent = parseTimeExtent(timeExtentStr);
    if (timeExtent.index() == 1) {
        return std::get<1>(timeExtent);
    }

    auto timeExtentIt = map.find(std::get<0>(timeExtent));

    if (timeExtentIt == map.end()) {
        std::ostringstream oss;
        oss << "No productDefinitionTemplate can be mapped for ";
        oss << "timeExtent: " << (timeExtentStr ? std::string(*timeExtentStr) : std::string("None"));


        return Error{oss.str()};
    }


    auto timeFormatStr = lookup("timeFormat");
    auto timeFormat = parseTimeFormat(timeFormatStr);
    if (timeFormat.index() == 1) {
        return std::get<1>(timeFormat);
    }

    auto timeFormatIt = timeExtentIt->second.find(std::get<0>(timeFormat));

    if (timeFormatIt == timeExtentIt->second.end()) {
        std::ostringstream oss;
        oss << "No productDefinitionTemplate can be mapped for ";
        oss << "timeExtent: " << (timeExtentStr ? std::string(*timeExtentStr) : std::string("None"));
        oss << ", ";
        oss << "timeFormat: " << (timeFormatStr ? std::string(*timeFormatStr) : std::string("None"));


        return Error{oss.str()};
    }


    auto forecastTypeStr = lookup("forecastType");
    auto forecastType = parseForecastType(forecastTypeStr);
    if (forecastType.index() == 1) {
        return std::get<1>(forecastType);
    }

    auto forecastTypeIt = timeFormatIt->second.find(std::get<0>(forecastType));

    if (forecastTypeIt == timeFormatIt->second.end()) {
        std::ostringstream oss;
        oss << "No productDefinitionTemplate can be mapped for ";
        oss << "timeExtent: " << (timeExtentStr ? std::string(*timeExtentStr) : std::string("None"));
        oss << ", ";
        oss << "timeFormat: " << (timeFormatStr ? std::string(*timeFormatStr) : std::string("None"));
        oss << ", ";
        oss << "forecastType: " << (forecastTypeStr ? std::string(*forecastTypeStr) : std::string("None"));


        return Error{oss.str()};
    }


    auto forecastSubTypeStr = lookup("forecastSubType");
    auto forecastSubType = parseForecastSubType(forecastSubTypeStr);
    if (forecastSubType.index() == 1) {
        return std::get<1>(forecastSubType);
    }

    auto forecastSubTypeIt = forecastTypeIt->second.find(std::get<0>(forecastSubType));

    if (forecastSubTypeIt == forecastTypeIt->second.end()) {
        std::ostringstream oss;
        oss << "No productDefinitionTemplate can be mapped for ";
        oss << "timeExtent: " << (timeExtentStr ? std::string(*timeExtentStr) : std::string("None"));
        oss << ", ";
        oss << "timeFormat: " << (timeFormatStr ? std::string(*timeFormatStr) : std::string("None"));
        oss << ", ";
        oss << "forecastType: " << (forecastTypeStr ? std::string(*forecastTypeStr) : std::string("None"));
        oss << ", ";
        oss << "forecastSubType: " << (forecastSubTypeStr ? std::string(*forecastSubTypeStr) : std::string("None"));


        return Error{oss.str()};
    }


    auto productCategoryStr = lookup("productCategory");
    auto productCategory = parseProductCategory(productCategoryStr);
    if (productCategory.index() == 1) {
        return std::get<1>(productCategory);
    }

    auto productCategoryIt = forecastSubTypeIt->second.find(std::get<0>(productCategory));

    if (productCategoryIt == forecastSubTypeIt->second.end()) {
        std::ostringstream oss;
        oss << "No productDefinitionTemplate can be mapped for ";
        oss << "timeExtent: " << (timeExtentStr ? std::string(*timeExtentStr) : std::string("None"));
        oss << ", ";
        oss << "timeFormat: " << (timeFormatStr ? std::string(*timeFormatStr) : std::string("None"));
        oss << ", ";
        oss << "forecastType: " << (forecastTypeStr ? std::string(*forecastTypeStr) : std::string("None"));
        oss << ", ";
        oss << "forecastSubType: " << (forecastSubTypeStr ? std::string(*forecastSubTypeStr) : std::string("None"));
        oss << ", ";
        oss << "productCategory: " << (productCategoryStr ? std::string(*productCategoryStr) : std::string("None"));


        return Error{oss.str()};
    }


    auto productSubCategoryStr = lookup("productSubCategory");
    auto productSubCategory = parseProductSubCategory(productSubCategoryStr);
    if (productSubCategory.index() == 1) {
        return std::get<1>(productSubCategory);
    }

    auto productSubCategoryIt = productCategoryIt->second.find(std::get<0>(productSubCategory));

    if (productSubCategoryIt == productCategoryIt->second.end()) {
        std::ostringstream oss;
        oss << "No productDefinitionTemplate can be mapped for ";
        oss << "timeExtent: " << (timeExtentStr ? std::string(*timeExtentStr) : std::string("None"));
        oss << ", ";
        oss << "timeFormat: " << (timeFormatStr ? std::string(*timeFormatStr) : std::string("None"));
        oss << ", ";
        oss << "forecastType: " << (forecastTypeStr ? std::string(*forecastTypeStr) : std::string("None"));
        oss << ", ";
        oss << "forecastSubType: " << (forecastSubTypeStr ? std::string(*forecastSubTypeStr) : std::string("None"));
        oss << ", ";
        oss << "productCategory: " << (productCategoryStr ? std::string(*productCategoryStr) : std::string("None"));
        oss << ", ";
        oss << "productSubCategory: "
            << (productSubCategoryStr ? std::string(*productSubCategoryStr) : std::string("None"));


        return Error{oss.str()};
    }

    return productSubCategoryIt->second;
}


Result<std::reference_wrapper<const KeyList>> keysForPdt(unsigned int pdt) noexcept {
    static const PdtKeyMap map{
        {{0,
          {{"paramId", "typeOfGeneratingProcess", "backgroundProcess", "generatingProcessIdentifier",
            "hoursAfterDataCutoff", "minutesAfterDataCutoff", "startStep", "forecastTime", "typeOfLevel"}}},
         {1,
          {{"paramId", "typeOfGeneratingProcess", "backgroundProcess", "generatingProcessIdentifier",
            "hoursAfterDataCutoff", "minutesAfterDataCutoff", "startStep", "forecastTime", "typeOfLevel",
            "typeOfEnsembleForecast", "perturbationNumber", "numberOfForecastsInEnsemble"}}},
         {2,
          {{"paramId", "typeOfGeneratingProcess", "backgroundProcess", "generatingProcessIdentifier",
            "hoursAfterDataCutoff", "minutesAfterDataCutoff", "startStep", "forecastTime", "typeOfLevel",
            "derivedForecast", "numberOfForecastsInEnsemble"}}},
         {3,
          {{"paramId",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "hoursAfterDataCutoff",
            "minutesAfterDataCutoff",
            "startStep",
            "forecastTime",
            "typeOfLevel",
            "derivedForecast",
            "numberOfForecastsInEnsemble",
            "clusterIdentifier",
            "NH",
            "NL",
            "totalNumberOfClusters",
            "clusteringMethod",
            "northernLatitudeOfClusterDomain",
            "southernLatitudeOfClusterDomain",
            "easternLongitudeOfClusterDomain",
            "westernLongitudeOfClusterDomain",
            "numberOfForecastsInTheCluster",
            "scaleFactorOfStandardDeviation",
            "scaledValueOfStandardDeviation",
            "scaleFactorOfDistanceFromEnsembleMean",
            "scaledValueOfDistanceFromEnsembleMean",
            "ensembleForecastNumbers"}}},
         {4,
          {{"paramId",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "hoursAfterDataCutoff",
            "minutesAfterDataCutoff",
            "startStep",
            "forecastTime",
            "typeOfLevel",
            "derivedForecast",
            "numberOfForecastsInEnsemble",
            "clusterIdentifier",
            "NH",
            "NL",
            "totalNumberOfClusters",
            "clusteringMethod",
            "latitudeOfCentralPointInClusterDomain",
            "longitudeOfCentralPointInClusterDomain",
            "radiusOfClusterDomain",
            "numberOfForecastsInTheCluster",
            "scaleFactorOfStandardDeviation",
            "scaledValueOfStandardDeviation",
            "scaleFactorOfDistanceFromEnsembleMean",
            "scaledValueOfDistanceFromEnsembleMean",
            "ensembleForecastNumbers"}}},
         {5,
          {{"paramId", "typeOfGeneratingProcess", "backgroundProcess", "generatingProcessIdentifier",
            "hoursAfterDataCutoff", "minutesAfterDataCutoff", "startStep", "forecastTime", "typeOfLevel",
            "forecastProbabilityNumber", "totalNumberOfForecastProbabilities", "probabilityType", "lowerLimit",
            "upperLimit"}}},
         {6,
          {{"paramId", "typeOfGeneratingProcess", "backgroundProcess", "generatingProcessIdentifier",
            "hoursAfterDataCutoff", "minutesAfterDataCutoff", "startStep", "forecastTime", "typeOfLevel",
            "percentileValue"}}},
         {8,
          {{"paramId", "typeOfGeneratingProcess", "backgroundProcess", "generatingProcessIdentifier",
            "hoursAfterDataCutoff", "minutesAfterDataCutoff", "startStep", "forecastTime", "typeOfLevel", "endStep",
            "numberOfTimeRange", "numberOfMissingInStatisticalProcess", "typeOfStatisticalProcessing",
            "typeOfTimeIncrement", "indicatorOfUnitForTimeRange", "indicatorOfUnitForTimeIncrement", "timeIncrement"}}},
         {9,
          {{"paramId",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "hoursAfterDataCutoff",
            "minutesAfterDataCutoff",
            "startStep",
            "forecastTime",
            "typeOfLevel",
            "forecastProbabilityNumber",
            "totalNumberOfForecastProbabilities",
            "probabilityType",
            "lowerLimit",
            "upperLimit",
            "endStep",
            "numberOfTimeRange",
            "numberOfMissingInStatisticalProcess",
            "typeOfStatisticalProcessing",
            "typeOfTimeIncrement",
            "indicatorOfUnitForTimeRange",
            "indicatorOfUnitForTimeIncrement",
            "timeIncrement"}}},
         {10,
          {{"paramId", "typeOfGeneratingProcess", "backgroundProcess", "generatingProcessIdentifier",
            "hoursAfterDataCutoff", "minutesAfterDataCutoff", "startStep", "forecastTime", "typeOfLevel",
            "percentileValue", "endStep", "numberOfTimeRange", "numberOfMissingInStatisticalProcess",
            "typeOfStatisticalProcessing", "typeOfTimeIncrement", "indicatorOfUnitForTimeRange",
            "indicatorOfUnitForTimeIncrement", "timeIncrement"}}},
         {11,
          {{"paramId",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "hoursAfterDataCutoff",
            "minutesAfterDataCutoff",
            "startStep",
            "forecastTime",
            "typeOfLevel",
            "typeOfEnsembleForecast",
            "perturbationNumber",
            "numberOfForecastsInEnsemble",
            "endStep",
            "numberOfTimeRange",
            "numberOfMissingInStatisticalProcess",
            "typeOfStatisticalProcessing",
            "typeOfTimeIncrement",
            "indicatorOfUnitForTimeRange",
            "indicatorOfUnitForTimeIncrement",
            "timeIncrement"}}},
         {12,
          {{"paramId", "typeOfGeneratingProcess", "backgroundProcess", "generatingProcessIdentifier",
            "hoursAfterDataCutoff", "minutesAfterDataCutoff", "startStep", "forecastTime", "typeOfLevel",
            "derivedForecast", "numberOfForecastsInEnsemble", "endStep", "numberOfTimeRange",
            "numberOfMissingInStatisticalProcess", "typeOfStatisticalProcessing", "typeOfTimeIncrement",
            "indicatorOfUnitForTimeRange", "indicatorOfUnitForTimeIncrement", "timeIncrement"}}},
         {13,
          {{"paramId",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "hoursAfterDataCutoff",
            "minutesAfterDataCutoff",
            "startStep",
            "forecastTime",
            "typeOfLevel",
            "derivedForecast",
            "numberOfForecastsInEnsemble",
            "clusterIdentifier",
            "NH",
            "NL",
            "totalNumberOfClusters",
            "clusteringMethod",
            "northernLatitudeOfClusterDomain",
            "southernLatitudeOfClusterDomain",
            "easternLongitudeOfClusterDomain",
            "westernLongitudeOfClusterDomain",
            "numberOfForecastsInTheCluster",
            "scaleFactorOfStandardDeviation",
            "scaledValueOfStandardDeviation",
            "scaleFactorOfDistanceFromEnsembleMean",
            "scaledValueOfDistanceFromEnsembleMean",
            "ensembleForecastNumbers",
            "endStep",
            "numberOfTimeRange",
            "numberOfMissingInStatisticalProcess",
            "typeOfStatisticalProcessing",
            "typeOfTimeIncrement",
            "indicatorOfUnitForTimeRange",
            "indicatorOfUnitForTimeIncrement",
            "timeIncrement"}}},
         {14,
          {{"paramId",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "hoursAfterDataCutoff",
            "minutesAfterDataCutoff",
            "startStep",
            "forecastTime",
            "typeOfLevel",
            "derivedForecast",
            "numberOfForecastsInEnsemble",
            "clusterIdentifier",
            "NH",
            "NL",
            "totalNumberOfClusters",
            "clusteringMethod",
            "latitudeOfCentralPointInClusterDomain",
            "longitudeOfCentralPointInClusterDomain",
            "radiusOfClusterDomain",
            "numberOfForecastsInTheCluster",
            "scaleFactorOfStandardDeviation",
            "scaledValueOfStandardDeviation",
            "scaleFactorOfDistanceFromEnsembleMean",
            "scaledValueOfDistanceFromEnsembleMean",
            "ensembleForecastNumbers",
            "endStep",
            "numberOfTimeRange",
            "numberOfMissingInStatisticalProcess",
            "typeOfStatisticalProcessing",
            "typeOfTimeIncrement",
            "indicatorOfUnitForTimeRange",
            "indicatorOfUnitForTimeIncrement",
            "timeIncrement"}}},
         {15,
          {{"paramId", "typeOfGeneratingProcess", "backgroundProcess", "generatingProcessIdentifier",
            "hoursAfterDataCutoff", "minutesAfterDataCutoff", "startStep", "forecastTime", "typeOfLevel",
            "statisticalProcess", "spatialProcessing", "numberOfPointsUsed"}}},
         {20,
          {{"paramId", "typeOfGeneratingProcess", "numberOfRadarSitesUsed", "startStep", "siteLatitude",
            "siteLongitude", "siteElevation", "siteId", "operatingMode", "reflectivityCalibrationConstant",
            "qualityControlIndicator", "clutterFilterIndicator", "constantAntennaElevationAngle",
            "accumulationInterval", "referenceReflectivityForEchoTop", "rangeBinSpacing", "radialAngularSpacing"}}},
         {31,
          {{"paramId", "typeOfGeneratingProcess", "observationGeneratingProcessIdentifier",
            "numberOfContributingSpectralBands", "satelliteSeries", "satelliteNumber", "instrumentType",
            "scaleFactorOfCentralWaveNumber", "scaledValueOfCentralWaveNumber"}}},
         {32,
          {{"paramId", "typeOfGeneratingProcess", "backgroundProcess", "generatingProcessIdentifier",
            "hoursAfterDataCutoff", "minutesAfterDataCutoff", "startStep", "forecastTime",
            "numberOfContributingSpectralBands", "satelliteSeries", "satelliteNumber", "instrumentType",
            "scaleFactorOfCentralWaveNumber", "scaledValueOfCentralWaveNumber"}}},
         {33,
          {{"paramId", "typeOfGeneratingProcess", "backgroundProcess", "generatingProcessIdentifier",
            "hoursAfterDataCutoff", "minutesAfterDataCutoff", "startStep", "forecastTime",
            "numberOfContributingSpectralBands", "satelliteSeries", "satelliteNumber", "instrumentType",
            "scaleFactorOfCentralWaveNumber", "scaledValueOfCentralWaveNumber", "typeOfEnsembleForecast",
            "perturbationNumber", "numberOfForecastsInEnsemble"}}},
         {34,
          {{"paramId",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "hoursAfterDataCutoff",
            "minutesAfterDataCutoff",
            "startStep",
            "forecastTime",
            "numberOfContributingSpectralBands",
            "satelliteSeries",
            "satelliteNumber",
            "instrumentType",
            "scaleFactorOfCentralWaveNumber",
            "scaledValueOfCentralWaveNumber",
            "typeOfEnsembleForecast",
            "perturbationNumber",
            "numberOfForecastsInEnsemble",
            "endStep",
            "numberOfTimeRange",
            "numberOfMissingInStatisticalProcess",
            "typeOfStatisticalProcessing",
            "typeOfTimeIncrement",
            "indicatorOfUnitForTimeRange",
            "indicatorOfUnitForTimeIncrement",
            "timeIncrement"}}},
         {35,
          {{"paramId", "typeOfGeneratingProcess", "observationGeneratingProcessIdentifier",
            "qualityValueAssociatedWithParameter", "numberOfContributingSpectralBands", "satelliteSeries",
            "satelliteNumber", "instrumentType", "scaleFactorOfCentralWaveNumber", "scaledValueOfCentralWaveNumber"}}},
         {40,
          {{"paramId", "constituentType", "typeOfGeneratingProcess", "backgroundProcess", "generatingProcessIdentifier",
            "hoursAfterDataCutoff", "minutesAfterDataCutoff", "startStep", "forecastTime", "typeOfLevel"}}},
         {41,
          {{"paramId", "constituentType", "typeOfGeneratingProcess", "backgroundProcess", "generatingProcessIdentifier",
            "hoursAfterDataCutoff", "minutesAfterDataCutoff", "startStep", "forecastTime", "typeOfLevel",
            "typeOfEnsembleForecast", "perturbationNumber", "numberOfForecastsInEnsemble"}}},
         {42,
          {{"paramId", "constituentType", "typeOfGeneratingProcess", "backgroundProcess", "generatingProcessIdentifier",
            "hoursAfterDataCutoff", "minutesAfterDataCutoff", "startStep", "forecastTime", "typeOfLevel", "endStep",
            "numberOfTimeRange", "numberOfMissingInStatisticalProcess", "typeOfStatisticalProcessing",
            "typeOfTimeIncrement", "indicatorOfUnitForTimeRange", "indicatorOfUnitForTimeIncrement", "timeIncrement"}}},
         {43,
          {{"paramId",
            "constituentType",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "hoursAfterDataCutoff",
            "minutesAfterDataCutoff",
            "startStep",
            "forecastTime",
            "typeOfLevel",
            "typeOfEnsembleForecast",
            "perturbationNumber",
            "numberOfForecastsInEnsemble",
            "endStep",
            "numberOfTimeRange",
            "numberOfMissingInStatisticalProcess",
            "typeOfStatisticalProcessing",
            "typeOfTimeIncrement",
            "indicatorOfUnitForTimeRange",
            "indicatorOfUnitForTimeIncrement",
            "timeIncrement"}}},
         {45,
          {{"paramId", "aerosolType", "typeOfSizeInterval", "scaleFactorOfFirstSize", "scaledValueOfFirstSize",
            "scaleFactorOfSecondSize", "scaledValueOfSecondSize", "typeOfGeneratingProcess", "backgroundProcess",
            "generatingProcessIdentifier", "hoursAfterDataCutoff", "minutesAfterDataCutoff", "startStep",
            "forecastTime", "typeOfLevel", "typeOfEnsembleForecast", "perturbationNumber",
            "numberOfForecastsInEnsemble"}}},
         {46,
          {{"paramId",
            "aerosolType",
            "typeOfSizeInterval",
            "scaleFactorOfFirstSize",
            "scaledValueOfFirstSize",
            "scaleFactorOfSecondSize",
            "scaledValueOfSecondSize",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "hoursAfterDataCutoff",
            "minutesAfterDataCutoff",
            "startStep",
            "forecastTime",
            "typeOfLevel",
            "endStep",
            "numberOfTimeRange",
            "numberOfMissingInStatisticalProcess",
            "typeOfStatisticalProcessing",
            "typeOfTimeIncrement",
            "indicatorOfUnitForTimeRange",
            "indicatorOfUnitForTimeIncrement",
            "timeIncrement"}}},
         {48,
          {{"paramId",
            "aerosolType",
            "typeOfSizeInterval",
            "scaleFactorOfFirstSize",
            "scaledValueOfFirstSize",
            "scaleFactorOfSecondSize",
            "scaledValueOfSecondSize",
            "typeOfWavelengthInterval",
            "scaleFactorOfFirstWavelength",
            "scaledValueOfFirstWavelength",
            "scaleFactorOfSecondWavelength",
            "scaledValueOfSecondWavelength",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "hoursAfterDataCutoff",
            "minutesAfterDataCutoff",
            "startStep",
            "forecastTime",
            "typeOfLevel"}}},
         {49,
          {{"paramId",
            "aerosolType",
            "typeOfSizeInterval",
            "scaleFactorOfFirstSize",
            "scaledValueOfFirstSize",
            "scaleFactorOfSecondSize",
            "scaledValueOfSecondSize",
            "typeOfWavelengthInterval",
            "scaleFactorOfFirstWavelength",
            "scaledValueOfFirstWavelength",
            "scaleFactorOfSecondWavelength",
            "scaledValueOfSecondWavelength",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "hoursAfterDataCutoff",
            "minutesAfterDataCutoff",
            "startStep",
            "forecastTime",
            "typeOfLevel",
            "typeOfEnsembleForecast",
            "perturbationNumber",
            "numberOfForecastsInEnsemble"}}},
         {51,
          {{"paramId", "typeOfGeneratingProcess", "backgroundProcess", "generatingProcessIdentifier",
            "hoursAfterDataCutoff", "minutesAfterDataCutoff", "startStep", "forecastTime", "typeOfLevel",
            "numberOfCategories", "codeFigure", "categoryType", "lowerLimit", "upperLimit"}}},
         {53,
          {{"paramId", "partitionTable", "numberOfPartitions", "partitionItems", "partitionNumber",
            "typeOfGeneratingProcess", "backgroundProcess", "generatingProcessIdentifier", "hoursAfterDataCutoff",
            "minutesAfterDataCutoff", "startStep", "forecastTime", "typeOfLevel"}}},
         {54,
          {{"paramId", "partitionTable", "numberOfPartitions", "partitionItems", "partitionNumber",
            "typeOfGeneratingProcess", "backgroundProcess", "generatingProcessIdentifier", "hoursAfterDataCutoff",
            "minutesAfterDataCutoff", "startStep", "forecastTime", "typeOfLevel", "typeOfEnsembleForecast",
            "perturbationNumber", "numberOfForecastsInEnsemble"}}},
         {55,
          {{"paramId", "tileClassification", "totalNumberOfTileAttributePairs", "numberOfUsedSpatialTiles", "tileIndex",
            "numberOfUsedTileAttributes", "attributeOfTile", "typeOfGeneratingProcess", "backgroundProcess",
            "generatingProcessIdentifier", "hoursAfterDataCutoff", "minutesAfterDataCutoff", "startStep",
            "forecastTime", "typeOfLevel"}}},
         {57,
          {{"paramId", "constituentType", "numberOfModeOfDistribution", "modeNumber", "typeOfDistributionFunction",
            "numberOfDistributionFunctionParameters", "scaleFactorOfDistributionFunctionParameter",
            "scaledValueOfDistributionFunctionParameter", "typeOfGeneratingProcess", "backgroundProcess",
            "generatingProcessIdentifier", "hoursAfterDataCutoff", "minutesAfterDataCutoff", "startStep",
            "forecastTime", "typeOfLevel"}}},
         {58,
          {{"paramId", "constituentType", "numberOfModeOfDistribution", "modeNumber", "typeOfDistributionFunction",
            "numberOfDistributionFunctionParameters", "scaleFactorOfDistributionFunctionParameter",
            "scaledValueOfDistributionFunctionParameter", "typeOfGeneratingProcess", "backgroundProcess",
            "generatingProcessIdentifier", "hoursAfterDataCutoff", "minutesAfterDataCutoff", "startStep",
            "forecastTime", "typeOfLevel", "typeOfEnsembleForecast", "perturbationNumber",
            "numberOfForecastsInEnsemble"}}},
         {59,
          {{"paramId", "tileClassification", "totalNumberOfTileAttributePairs", "numberOfUsedSpatialTiles", "tileIndex",
            "numberOfUsedTileAttributes", "attributeOfTile", "typeOfGeneratingProcess", "backgroundProcess",
            "generatingProcessIdentifier", "hoursAfterDataCutoff", "minutesAfterDataCutoff", "startStep",
            "forecastTime", "typeOfLevel", "typeOfEnsembleForecast", "perturbationNumber",
            "numberOfForecastsInEnsemble"}}},
         {60,
          {{"paramId", "typeOfGeneratingProcess", "backgroundProcess", "generatingProcessIdentifier",
            "hoursAfterDataCutoff", "minutesAfterDataCutoff", "startStep", "forecastTime", "typeOfLevel",
            "typeOfEnsembleForecast", "perturbationNumber", "numberOfForecastsInEnsemble", "YearOfModelVersion",
            "MonthOfModelVersion", "DayOfModelVersion", "HourOfModelVersion", "MinuteOfModelVersion",
            "SecondOfModelVersion"}}},
         {61,
          {{"paramId",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "hoursAfterDataCutoff",
            "minutesAfterDataCutoff",
            "startStep",
            "forecastTime",
            "typeOfLevel",
            "typeOfEnsembleForecast",
            "perturbationNumber",
            "numberOfForecastsInEnsemble",
            "YearOfModelVersion",
            "MonthOfModelVersion",
            "DayOfModelVersion",
            "HourOfModelVersion",
            "MinuteOfModelVersion",
            "SecondOfModelVersion",
            "endStep",
            "numberOfTimeRange",
            "numberOfMissingInStatisticalProcess",
            "typeOfStatisticalProcessing",
            "typeOfTimeIncrement",
            "indicatorOfUnitForTimeRange",
            "indicatorOfUnitForTimeIncrement",
            "timeIncrement"}}},
         {62,
          {{"paramId",
            "tileClassification",
            "totalNumberOfTileAttributePairs",
            "numberOfUsedSpatialTiles",
            "tileIndex",
            "numberOfUsedTileAttributes",
            "attributeOfTile",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "hoursAfterDataCutoff",
            "minutesAfterDataCutoff",
            "startStep",
            "forecastTime",
            "typeOfLevel",
            "endStep",
            "numberOfTimeRange",
            "numberOfMissingInStatisticalProcess",
            "typeOfStatisticalProcessing",
            "typeOfTimeIncrement",
            "indicatorOfUnitForTimeRange",
            "indicatorOfUnitForTimeIncrement",
            "timeIncrement"}}},
         {63,
          {{"paramId",
            "tileClassification",
            "totalNumberOfTileAttributePairs",
            "numberOfUsedSpatialTiles",
            "tileIndex",
            "numberOfUsedTileAttributes",
            "attributeOfTile",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "hoursAfterDataCutoff",
            "minutesAfterDataCutoff",
            "startStep",
            "forecastTime",
            "typeOfLevel",
            "typeOfEnsembleForecast",
            "perturbationNumber",
            "numberOfForecastsInEnsemble",
            "endStep",
            "numberOfTimeRange",
            "numberOfMissingInStatisticalProcess",
            "typeOfStatisticalProcessing",
            "typeOfTimeIncrement",
            "indicatorOfUnitForTimeRange",
            "indicatorOfUnitForTimeIncrement",
            "timeIncrement"}}},
         {67,
          {{"paramId",
            "constituentType",
            "numberOfModeOfDistribution",
            "modeNumber",
            "typeOfDistributionFunction",
            "numberOfDistributionFunctionParameters",
            "scaleFactorOfDistributionFunctionParameter",
            "scaledValueOfDistributionFunctionParameter",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "hoursAfterDataCutoff",
            "minutesAfterDataCutoff",
            "startStep",
            "forecastTime",
            "typeOfLevel",
            "endStep",
            "numberOfTimeRange",
            "numberOfMissingInStatisticalProcess",
            "typeOfStatisticalProcessing",
            "typeOfTimeIncrement",
            "indicatorOfUnitForTimeRange",
            "indicatorOfUnitForTimeIncrement",
            "timeIncrement"}}},
         {68,
          {{"paramId",
            "constituentType",
            "numberOfModeOfDistribution",
            "modeNumber",
            "typeOfDistributionFunction",
            "numberOfDistributionFunctionParameters",
            "scaleFactorOfDistributionFunctionParameter",
            "scaledValueOfDistributionFunctionParameter",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "hoursAfterDataCutoff",
            "minutesAfterDataCutoff",
            "startStep",
            "forecastTime",
            "typeOfLevel",
            "typeOfEnsembleForecast",
            "perturbationNumber",
            "numberOfForecastsInEnsemble",
            "endStep",
            "numberOfTimeRange",
            "numberOfMissingInStatisticalProcess",
            "typeOfStatisticalProcessing",
            "typeOfTimeIncrement",
            "indicatorOfUnitForTimeRange",
            "indicatorOfUnitForTimeIncrement",
            "timeIncrement"}}},
         {70,
          {{"paramId", "inputProcessIdentifier", "inputOriginatingCentre", "typeOfPostProcessing",
            "typeOfGeneratingProcess", "backgroundProcess", "generatingProcessIdentifier", "hoursAfterDataCutoff",
            "minutesAfterDataCutoff", "startStep", "forecastTime", "typeOfLevel"}}},
         {71,
          {{"paramId", "inputProcessIdentifier", "inputOriginatingCentre", "typeOfPostProcessing",
            "typeOfGeneratingProcess", "backgroundProcess", "generatingProcessIdentifier", "hoursAfterDataCutoff",
            "minutesAfterDataCutoff", "startStep", "forecastTime", "typeOfLevel", "typeOfEnsembleForecast",
            "perturbationNumber", "numberOfForecastsInEnsemble"}}},
         {72,
          {{"paramId",
            "inputProcessIdentifier",
            "inputOriginatingCentre",
            "typeOfPostProcessing",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "hoursAfterDataCutoff",
            "minutesAfterDataCutoff",
            "startStep",
            "forecastTime",
            "typeOfLevel",
            "endStep",
            "numberOfTimeRange",
            "numberOfMissingInStatisticalProcess",
            "typeOfStatisticalProcessing",
            "typeOfTimeIncrement",
            "indicatorOfUnitForTimeRange",
            "indicatorOfUnitForTimeIncrement",
            "timeIncrement"}}},
         {73,
          {{"paramId",
            "inputProcessIdentifier",
            "inputOriginatingCentre",
            "typeOfPostProcessing",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "hoursAfterDataCutoff",
            "minutesAfterDataCutoff",
            "startStep",
            "forecastTime",
            "typeOfLevel",
            "typeOfEnsembleForecast",
            "perturbationNumber",
            "numberOfForecastsInEnsemble",
            "endStep",
            "numberOfTimeRange",
            "numberOfMissingInStatisticalProcess",
            "typeOfStatisticalProcessing",
            "typeOfTimeIncrement",
            "indicatorOfUnitForTimeRange",
            "indicatorOfUnitForTimeIncrement",
            "timeIncrement"}}},
         {76,
          {{"paramId", "constituentType", "sourceSinkChemicalPhysicalProcess", "typeOfGeneratingProcess",
            "backgroundProcess", "generatingProcessIdentifier", "hoursAfterDataCutoff", "minutesAfterDataCutoff",
            "startStep", "forecastTime", "typeOfLevel"}}},
         {77,
          {{"paramId", "constituentType", "sourceSinkChemicalPhysicalProcess", "typeOfGeneratingProcess",
            "backgroundProcess", "generatingProcessIdentifier", "hoursAfterDataCutoff", "minutesAfterDataCutoff",
            "startStep", "forecastTime", "typeOfLevel", "typeOfEnsembleForecast", "perturbationNumber",
            "numberOfForecastsInEnsemble"}}},
         {78,
          {{"paramId", "constituentType", "sourceSinkChemicalPhysicalProcess", "typeOfGeneratingProcess",
            "backgroundProcess", "generatingProcessIdentifier", "hoursAfterDataCutoff", "minutesAfterDataCutoff",
            "startStep", "forecastTime", "typeOfLevel", "endStep", "numberOfTimeRange",
            "numberOfMissingInStatisticalProcess", "typeOfStatisticalProcessing", "typeOfTimeIncrement",
            "indicatorOfUnitForTimeRange", "indicatorOfUnitForTimeIncrement", "timeIncrement"}}},
         {79,
          {{"paramId",
            "constituentType",
            "sourceSinkChemicalPhysicalProcess",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "hoursAfterDataCutoff",
            "minutesAfterDataCutoff",
            "startStep",
            "forecastTime",
            "typeOfLevel",
            "typeOfEnsembleForecast",
            "perturbationNumber",
            "numberOfForecastsInEnsemble",
            "endStep",
            "numberOfTimeRange",
            "numberOfMissingInStatisticalProcess",
            "typeOfStatisticalProcessing",
            "typeOfTimeIncrement",
            "indicatorOfUnitForTimeRange",
            "indicatorOfUnitForTimeIncrement",
            "timeIncrement"}}},
         {80,
          {{"paramId",
            "aerosolType",
            "sourceSinkChemicalPhysicalProcess",
            "typeOfSizeInterval",
            "scaleFactorOfFirstSize",
            "scaledValueOfFirstSize",
            "scaleFactorOfSecondSize",
            "scaledValueOfSecondSize",
            "typeOfWavelengthInterval",
            "scaleFactorOfFirstWavelength",
            "scaledValueOfFirstWavelength",
            "scaleFactorOfSecondWavelength",
            "scaledValueOfSecondWavelength",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "hoursAfterDataCutoff",
            "minutesAfterDataCutoff",
            "startStep",
            "forecastTime",
            "typeOfLevel"}}},
         {81,
          {{"paramId",
            "aerosolType",
            "sourceSinkChemicalPhysicalProcess",
            "typeOfSizeInterval",
            "scaleFactorOfFirstSize",
            "scaledValueOfFirstSize",
            "scaleFactorOfSecondSize",
            "scaledValueOfSecondSize",
            "typeOfWavelengthInterval",
            "scaleFactorOfFirstWavelength",
            "scaledValueOfFirstWavelength",
            "scaleFactorOfSecondWavelength",
            "scaledValueOfSecondWavelength",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "hoursAfterDataCutoff",
            "minutesAfterDataCutoff",
            "startStep",
            "forecastTime",
            "typeOfLevel",
            "typeOfEnsembleForecast",
            "perturbationNumber",
            "numberOfForecastsInEnsemble"}}},
         {82,
          {{"paramId",
            "aerosolType",
            "sourceSinkChemicalPhysicalProcess",
            "typeOfSizeInterval",
            "scaleFactorOfFirstSize",
            "scaledValueOfFirstSize",
            "scaleFactorOfSecondSize",
            "scaledValueOfSecondSize",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "hoursAfterDataCutoff",
            "minutesAfterDataCutoff",
            "startStep",
            "forecastTime",
            "typeOfLevel",
            "endStep",
            "numberOfTimeRange",
            "numberOfMissingInStatisticalProcess",
            "typeOfStatisticalProcessing",
            "typeOfTimeIncrement",
            "indicatorOfUnitForTimeRange",
            "indicatorOfUnitForTimeIncrement",
            "timeIncrement"}}},
         {84,
          {{"paramId",
            "aerosolType",
            "sourceSinkChemicalPhysicalProcess",
            "typeOfSizeInterval",
            "scaleFactorOfFirstSize",
            "scaledValueOfFirstSize",
            "scaleFactorOfSecondSize",
            "scaledValueOfSecondSize",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "hoursAfterDataCutoff",
            "minutesAfterDataCutoff",
            "startStep",
            "forecastTime",
            "typeOfLevel",
            "typeOfEnsembleForecast",
            "perturbationNumber",
            "numberOfForecastsInEnsemble",
            "endStep",
            "numberOfTimeRange",
            "numberOfMissingInStatisticalProcess",
            "typeOfStatisticalProcessing",
            "typeOfTimeIncrement",
            "indicatorOfUnitForTimeRange",
            "indicatorOfUnitForTimeIncrement",
            "timeIncrement"}}},
         {85,
          {{"paramId",
            "aerosolType",
            "typeOfSizeInterval",
            "scaleFactorOfFirstSize",
            "scaledValueOfFirstSize",
            "scaleFactorOfSecondSize",
            "scaledValueOfSecondSize",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "hoursAfterDataCutoff",
            "minutesAfterDataCutoff",
            "startStep",
            "forecastTime",
            "typeOfLevel",
            "typeOfEnsembleForecast",
            "perturbationNumber",
            "numberOfForecastsInEnsemble",
            "endStep",
            "numberOfTimeRange",
            "numberOfMissingInStatisticalProcess",
            "typeOfStatisticalProcessing",
            "typeOfTimeIncrement",
            "indicatorOfUnitForTimeRange",
            "indicatorOfUnitForTimeIncrement",
            "timeIncrement"}}},
         {86,
          {{"paramId", "typeOfGeneratingProcess", "backgroundProcess", "generatingProcessIdentifier",
            "hoursAfterDataCutoff", "minutesAfterDataCutoff", "startStep", "forecastTime", "typeOfLevel",
            "totalNumberOfQuantiles", "quantileValue"}}},
         {87,
          {{"paramId", "typeOfGeneratingProcess", "backgroundProcess", "generatingProcessIdentifier",
            "hoursAfterDataCutoff", "minutesAfterDataCutoff", "startStep", "forecastTime", "typeOfLevel",
            "totalNumberOfQuantiles", "quantileValue", "endStep", "numberOfTimeRange",
            "numberOfMissingInStatisticalProcess", "typeOfStatisticalProcessing", "typeOfTimeIncrement",
            "indicatorOfUnitForTimeRange", "indicatorOfUnitForTimeIncrement", "timeIncrement"}}},
         {88,
          {{"paramId", "typeOfGeneratingProcess", "backgroundProcess", "generatingProcessIdentifier", "typeOfLevel",
            "localTimeMethod", "numberOfForecastsUsedinLocalTime", "yearOfForecastUsedInLocalTime",
            "monthOfForecastUsedInLocalTime", "dayOfForecastUsedInLocalTime", "hourOfForecastUsedInLocalTime",
            "minuteOfForecastUsedInLocalTime", "secondOfForecastUsedInLocalTime", "indicatorOfUnitForForecastTime",
            "forecastTime", "numberOfTimeIncrementsOfForecastsUsedInLocalTime", "indicatorOfUnitForTimeIncrement",
            "timeIncrement"}}},
         {91,
          {{"paramId",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "hoursAfterDataCutoff",
            "minutesAfterDataCutoff",
            "startStep",
            "forecastTime",
            "typeOfLevel",
            "numberOfCategories",
            "codeFigure",
            "categoryType",
            "lowerLimit",
            "upperLimit",
            "endStep",
            "numberOfTimeRange",
            "numberOfMissingInStatisticalProcess",
            "typeOfStatisticalProcessing",
            "typeOfTimeIncrement",
            "indicatorOfUnitForTimeRange",
            "indicatorOfUnitForTimeIncrement",
            "timeIncrement"}}},
         {92,
          {{"paramId",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "typeOfLevel",
            "typeOfEnsembleForecast",
            "perturbationNumber",
            "numberOfForecastsInEnsemble",
            "localTimeMethod",
            "numberOfForecastsUsedinLocalTime",
            "yearOfForecastUsedInLocalTime",
            "monthOfForecastUsedInLocalTime",
            "dayOfForecastUsedInLocalTime",
            "hourOfForecastUsedInLocalTime",
            "minuteOfForecastUsedInLocalTime",
            "secondOfForecastUsedInLocalTime",
            "indicatorOfUnitForForecastTime",
            "forecastTime",
            "numberOfTimeIncrementsOfForecastsUsedInLocalTime",
            "indicatorOfUnitForTimeIncrement",
            "timeIncrement"}}},
         {93,
          {{"paramId",
            "inputProcessIdentifier",
            "inputOriginatingCentre",
            "typeOfPostProcessing",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "typeOfLevel",
            "localTimeMethod",
            "numberOfForecastsUsedinLocalTime",
            "yearOfForecastUsedInLocalTime",
            "monthOfForecastUsedInLocalTime",
            "dayOfForecastUsedInLocalTime",
            "hourOfForecastUsedInLocalTime",
            "minuteOfForecastUsedInLocalTime",
            "secondOfForecastUsedInLocalTime",
            "indicatorOfUnitForForecastTime",
            "forecastTime",
            "numberOfTimeIncrementsOfForecastsUsedInLocalTime",
            "indicatorOfUnitForTimeIncrement",
            "timeIncrement"}}},
         {94,
          {{"paramId",
            "inputProcessIdentifier",
            "inputOriginatingCentre",
            "typeOfPostProcessing",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "typeOfLevel",
            "typeOfEnsembleForecast",
            "perturbationNumber",
            "numberOfForecastsInEnsemble",
            "localTimeMethod",
            "numberOfForecastsUsedinLocalTime",
            "yearOfForecastUsedInLocalTime",
            "monthOfForecastUsedInLocalTime",
            "dayOfForecastUsedInLocalTime",
            "hourOfForecastUsedInLocalTime",
            "minuteOfForecastUsedInLocalTime",
            "secondOfForecastUsedInLocalTime",
            "indicatorOfUnitForForecastTime",
            "forecastTime",
            "numberOfTimeIncrementsOfForecastsUsedInLocalTime",
            "indicatorOfUnitForTimeIncrement",
            "timeIncrement"}}},
         {95,
          {{"paramId",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "typeOfLevel",
            "typeOfStatisticalProcessing",
            "indicatorOfUnitForTimeRange",
            "endStep",
            "numberOfStatisticallyProcessedFieldsForLocalTime",
            "localTimeMethod",
            "numberOfForecastsUsedinLocalTime",
            "yearOfForecastUsedInLocalTime",
            "monthOfForecastUsedInLocalTime",
            "dayOfForecastUsedInLocalTime",
            "hourOfForecastUsedInLocalTime",
            "minuteOfForecastUsedInLocalTime",
            "secondOfForecastUsedInLocalTime",
            "indicatorOfUnitForForecastTime",
            "forecastTime",
            "numberOfTimeIncrementsOfForecastsUsedInLocalTime",
            "indicatorOfUnitForTimeIncrement",
            "timeIncrement"}}},
         {96,
          {{"paramId",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "typeOfLevel",
            "typeOfEnsembleForecast",
            "perturbationNumber",
            "numberOfForecastsInEnsemble",
            "typeOfStatisticalProcessing",
            "indicatorOfUnitForTimeRange",
            "endStep",
            "numberOfStatisticallyProcessedFieldsForLocalTime",
            "localTimeMethod",
            "numberOfForecastsUsedinLocalTime",
            "yearOfForecastUsedInLocalTime",
            "monthOfForecastUsedInLocalTime",
            "dayOfForecastUsedInLocalTime",
            "hourOfForecastUsedInLocalTime",
            "minuteOfForecastUsedInLocalTime",
            "secondOfForecastUsedInLocalTime",
            "indicatorOfUnitForForecastTime",
            "forecastTime",
            "numberOfTimeIncrementsOfForecastsUsedInLocalTime",
            "indicatorOfUnitForTimeIncrement",
            "timeIncrement"}}},
         {97,
          {{"paramId",
            "inputProcessIdentifier",
            "inputOriginatingCentre",
            "typeOfPostProcessing",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "typeOfLevel",
            "typeOfStatisticalProcessing",
            "indicatorOfUnitForTimeRange",
            "endStep",
            "numberOfStatisticallyProcessedFieldsForLocalTime",
            "localTimeMethod",
            "numberOfForecastsUsedinLocalTime",
            "yearOfForecastUsedInLocalTime",
            "monthOfForecastUsedInLocalTime",
            "dayOfForecastUsedInLocalTime",
            "hourOfForecastUsedInLocalTime",
            "minuteOfForecastUsedInLocalTime",
            "secondOfForecastUsedInLocalTime",
            "indicatorOfUnitForForecastTime",
            "forecastTime",
            "numberOfTimeIncrementsOfForecastsUsedInLocalTime",
            "indicatorOfUnitForTimeIncrement",
            "timeIncrement"}}},
         {98,
          {{"paramId",
            "inputProcessIdentifier",
            "inputOriginatingCentre",
            "typeOfPostProcessing",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "typeOfLevel",
            "typeOfEnsembleForecast",
            "perturbationNumber",
            "numberOfForecastsInEnsemble",
            "typeOfStatisticalProcessing",
            "indicatorOfUnitForTimeRange",
            "endStep",
            "numberOfStatisticallyProcessedFieldsForLocalTime",
            "localTimeMethod",
            "numberOfForecastsUsedinLocalTime",
            "yearOfForecastUsedInLocalTime",
            "monthOfForecastUsedInLocalTime",
            "dayOfForecastUsedInLocalTime",
            "hourOfForecastUsedInLocalTime",
            "minuteOfForecastUsedInLocalTime",
            "secondOfForecastUsedInLocalTime",
            "indicatorOfUnitForForecastTime",
            "forecastTime",
            "numberOfTimeIncrementsOfForecastsUsedInLocalTime",
            "indicatorOfUnitForTimeIncrement",
            "timeIncrement"}}},
         {99,
          {{"paramId", "waveDirectionNumber", "numberOfWaveDirections", "waveFrequencyNumber",
            "numberOfWaveFrequencies", "typeOfGeneratingProcess", "backgroundProcess", "generatingProcessIdentifier",
            "hoursAfterDataCutoff", "minutesAfterDataCutoff", "startStep", "forecastTime",
            "scaleFactorOfWaveDirections", "scaledValueOfWaveDirections", "scaleFactorOfWaveFrequencies",
            "scaledValueOfWaveFrequencies"}}},
         {100,
          {{"paramId", "waveDirectionNumber", "numberOfWaveDirections", "waveFrequencyNumber",
            "numberOfWaveFrequencies", "typeOfGeneratingProcess", "backgroundProcess", "generatingProcessIdentifier",
            "hoursAfterDataCutoff", "minutesAfterDataCutoff", "startStep", "forecastTime", "typeOfEnsembleForecast",
            "perturbationNumber", "numberOfForecastsInEnsemble", "scaleFactorOfWaveDirections",
            "scaledValueOfWaveDirections", "scaleFactorOfWaveFrequencies", "scaledValueOfWaveFrequencies"}}},
         {101,
          {{"paramId",
            "waveDirectionNumber",
            "numberOfWaveDirections",
            "waveFrequencyNumber",
            "numberOfWaveFrequencies",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "hoursAfterDataCutoff",
            "minutesAfterDataCutoff",
            "startStep",
            "forecastTime",
            "typeOfWaveDirectionSequence",
            "numberOfWaveDirectionSequenceParameters",
            "scaleFactorOfWaveDirectionSequenceParameter",
            "scaledValueOfWaveDirectionSequenceParameter",
            "typeOfWaveFrequencySequence",
            "numberOfWaveFrequencySequenceParameters",
            "scaleFactorOfWaveFrequencySequenceParameter",
            "scaledValueOfWaveFrequencySequenceParameter"}}},
         {102,
          {{"paramId",
            "waveDirectionNumber",
            "numberOfWaveDirections",
            "waveFrequencyNumber",
            "numberOfWaveFrequencies",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "hoursAfterDataCutoff",
            "minutesAfterDataCutoff",
            "startStep",
            "forecastTime",
            "typeOfEnsembleForecast",
            "perturbationNumber",
            "numberOfForecastsInEnsemble",
            "typeOfWaveDirectionSequence",
            "numberOfWaveDirectionSequenceParameters",
            "scaleFactorOfWaveDirectionSequenceParameter",
            "scaledValueOfWaveDirectionSequenceParameter",
            "typeOfWaveFrequencySequence",
            "numberOfWaveFrequencySequenceParameters",
            "scaleFactorOfWaveFrequencySequenceParameter",
            "scaledValueOfWaveFrequencySequenceParameter"}}},
         {103,
          {{"paramId", "typeOfWavePeriodInterval", "scaleFactorOfLowerWavePeriodLimit",
            "scaledValueOfLowerWavePeriodLimit", "scaleFactorOfUpperWavePeriodLimit",
            "scaledValueOfUpperWavePeriodLimit", "typeOfGeneratingProcess", "backgroundProcess",
            "generatingProcessIdentifier", "hoursAfterDataCutoff", "minutesAfterDataCutoff", "startStep",
            "forecastTime", "typeOfLevel"}}},
         {104,
          {{"paramId", "typeOfWavePeriodInterval", "scaleFactorOfLowerWavePeriodLimit",
            "scaledValueOfLowerWavePeriodLimit", "scaleFactorOfUpperWavePeriodLimit",
            "scaledValueOfUpperWavePeriodLimit", "typeOfGeneratingProcess", "backgroundProcess",
            "generatingProcessIdentifier", "hoursAfterDataCutoff", "minutesAfterDataCutoff", "startStep",
            "forecastTime", "typeOfLevel", "typeOfEnsembleForecast", "perturbationNumber",
            "numberOfForecastsInEnsemble"}}},
         {105,
          {{"paramId",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "hoursAfterDataCutoff",
            "minutesAfterDataCutoff",
            "startStep",
            "forecastTime",
            "typeOfLevel",
            "endStep",
            "numberOfTimeRange",
            "numberOfMissingInStatisticalProcess",
            "typeOfStatisticalProcessing",
            "typeOfTimeIncrement",
            "indicatorOfUnitForTimeRange",
            "indicatorOfUnitForTimeIncrement",
            "timeIncrement",
            "typeOfReferenceDataset",
            "typeOfRelationToReferenceDataset",
            "numberOfAdditionalParameterForReferencePeriod",
            "scaleFactorOfAdditionalParameterForReferencePeriod",
            "scaledValueOfAdditionalParameterForReferencePeriod",
            "yearOfStartOfReferencePeriod",
            "monthOfStartOfReferencePeriod",
            "dayOfStartOfReferencePeriod",
            "hourOfStartOfReferencePeriod",
            "minuteOfStartOfReferencePeriod",
            "secondOfStartOfReferencePeriod",
            "sampleSizeOfReferencePeriod",
            "numberOfReferencePeriodTimeRanges",
            "typeOfStatisticalProcessingForTimeRangeForReferencePeriod",
            "indicatorOfUnitForTimeRangeForReferencePeriod",
            "lengthOfTimeRangeForReferencePeriod"}}},
         {106,
          {{"paramId",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "hoursAfterDataCutoff",
            "minutesAfterDataCutoff",
            "startStep",
            "forecastTime",
            "typeOfLevel",
            "endStep",
            "numberOfTimeRange",
            "numberOfMissingInStatisticalProcess",
            "typeOfStatisticalProcessing",
            "typeOfTimeIncrement",
            "indicatorOfUnitForTimeRange",
            "indicatorOfUnitForTimeIncrement",
            "timeIncrement",
            "typeOfEnsembleForecast",
            "perturbationNumber",
            "numberOfForecastsInEnsemble",
            "typeOfReferenceDataset",
            "typeOfRelationToReferenceDataset",
            "numberOfAdditionalParameterForReferencePeriod",
            "scaleFactorOfAdditionalParameterForReferencePeriod",
            "scaledValueOfAdditionalParameterForReferencePeriod",
            "yearOfStartOfReferencePeriod",
            "monthOfStartOfReferencePeriod",
            "dayOfStartOfReferencePeriod",
            "hourOfStartOfReferencePeriod",
            "minuteOfStartOfReferencePeriod",
            "secondOfStartOfReferencePeriod",
            "sampleSizeOfReferencePeriod",
            "numberOfReferencePeriodTimeRanges",
            "typeOfStatisticalProcessingForTimeRangeForReferencePeriod",
            "indicatorOfUnitForTimeRangeForReferencePeriod",
            "lengthOfTimeRangeForReferencePeriod"}}},
         {107,
          {{"paramId",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "hoursAfterDataCutoff",
            "minutesAfterDataCutoff",
            "startStep",
            "forecastTime",
            "typeOfLevel",
            "endStep",
            "numberOfTimeRange",
            "numberOfMissingInStatisticalProcess",
            "typeOfStatisticalProcessing",
            "typeOfTimeIncrement",
            "indicatorOfUnitForTimeRange",
            "indicatorOfUnitForTimeIncrement",
            "timeIncrement",
            "derivedForecast",
            "numberOfForecastsInEnsemble",
            "typeOfReferenceDataset",
            "typeOfRelationToReferenceDataset",
            "numberOfAdditionalParameterForReferencePeriod",
            "scaleFactorOfAdditionalParameterForReferencePeriod",
            "scaledValueOfAdditionalParameterForReferencePeriod",
            "yearOfStartOfReferencePeriod",
            "monthOfStartOfReferencePeriod",
            "dayOfStartOfReferencePeriod",
            "hourOfStartOfReferencePeriod",
            "minuteOfStartOfReferencePeriod",
            "secondOfStartOfReferencePeriod",
            "sampleSizeOfReferencePeriod",
            "numberOfReferencePeriodTimeRanges",
            "typeOfStatisticalProcessingForTimeRangeForReferencePeriod",
            "indicatorOfUnitForTimeRangeForReferencePeriod",
            "lengthOfTimeRangeForReferencePeriod"}}},
         {108,
          {{"paramId", "typeOfWavelengthInterval", "scaleFactorOfFirstWavelength", "scaledValueOfFirstWavelength",
            "scaleFactorOfSecondWavelength", "scaledValueOfSecondWavelength", "typeOfGeneratingProcess",
            "backgroundProcess", "generatingProcessIdentifier", "hoursAfterDataCutoff", "minutesAfterDataCutoff",
            "startStep", "forecastTime", "typeOfLevel"}}},
         {109,
          {{"paramId", "typeOfWavelengthInterval", "scaleFactorOfFirstWavelength", "scaledValueOfFirstWavelength",
            "scaleFactorOfSecondWavelength", "scaledValueOfSecondWavelength", "typeOfGeneratingProcess",
            "backgroundProcess", "generatingProcessIdentifier", "hoursAfterDataCutoff", "minutesAfterDataCutoff",
            "startStep", "forecastTime", "typeOfLevel", "typeOfEnsembleForecast", "perturbationNumber",
            "numberOfForecastsInEnsemble"}}},
         {110,
          {{"paramId",
            "typeOfWavelengthInterval",
            "scaleFactorOfFirstWavelength",
            "scaledValueOfFirstWavelength",
            "scaleFactorOfSecondWavelength",
            "scaledValueOfSecondWavelength",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "hoursAfterDataCutoff",
            "minutesAfterDataCutoff",
            "startStep",
            "forecastTime",
            "typeOfLevel",
            "endStep",
            "numberOfTimeRange",
            "numberOfMissingInStatisticalProcess",
            "typeOfStatisticalProcessing",
            "typeOfTimeIncrement",
            "indicatorOfUnitForTimeRange",
            "indicatorOfUnitForTimeIncrement",
            "timeIncrement"}}},
         {111,
          {{"paramId",
            "typeOfWavelengthInterval",
            "scaleFactorOfFirstWavelength",
            "scaledValueOfFirstWavelength",
            "scaleFactorOfSecondWavelength",
            "scaledValueOfSecondWavelength",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "hoursAfterDataCutoff",
            "minutesAfterDataCutoff",
            "startStep",
            "forecastTime",
            "typeOfLevel",
            "typeOfEnsembleForecast",
            "perturbationNumber",
            "numberOfForecastsInEnsemble",
            "endStep",
            "numberOfTimeRange",
            "numberOfMissingInStatisticalProcess",
            "typeOfStatisticalProcessing",
            "typeOfTimeIncrement",
            "indicatorOfUnitForTimeRange",
            "indicatorOfUnitForTimeIncrement",
            "timeIncrement"}}},
         {112,
          {{"paramId",
            "typeOfGeneratingProcess",
            "backgroundProcess",
            "generatingProcessIdentifier",
            "hoursAfterDataCutoff",
            "minutesAfterDataCutoff",
            "startStep",
            "forecastTime",
            "typeOfLevel",
            "endStep",
            "numberOfTimeRange",
            "numberOfMissingInStatisticalProcess",
            "typeOfStatisticalProcessing",
            "typeOfTimeIncrement",
            "indicatorOfUnitForTimeRange",
            "indicatorOfUnitForTimeIncrement",
            "timeIncrement",
            "forecastProbabilityNumber",
            "totalNumberOfForecastProbabilities",
            "probabilityType",
            "lowerLimit",
            "upperLimit",
            "typeOfReferenceDataset",
            "typeOfRelationToReferenceDataset",
            "numberOfAdditionalParameterForReferencePeriod",
            "scaleFactorOfAdditionalParameterForReferencePeriod",
            "scaledValueOfAdditionalParameterForReferencePeriod",
            "yearOfStartOfReferencePeriod",
            "monthOfStartOfReferencePeriod",
            "dayOfStartOfReferencePeriod",
            "hourOfStartOfReferencePeriod",
            "minuteOfStartOfReferencePeriod",
            "secondOfStartOfReferencePeriod",
            "sampleSizeOfReferencePeriod",
            "numberOfReferencePeriodTimeRanges",
            "typeOfStatisticalProcessingForTimeRangeForReferencePeriod",
            "indicatorOfUnitForTimeRangeForReferencePeriod",
            "lengthOfTimeRangeForReferencePeriod"}}},
         {254, {{"paramId", "numberOfCharacters"}}},
         {1000,
          {{"paramId", "typeOfGeneratingProcess", "backgroundProcess", "generatingProcessIdentifier",
            "hoursAfterDataCutoff", "minutesAfterDataCutoff", "startStep", "forecastTime"}}},
         {1001,
          {{"paramId", "typeOfGeneratingProcess", "backgroundProcess", "generatingProcessIdentifier",
            "hoursAfterDataCutoff", "minutesAfterDataCutoff", "startStep", "forecastTime",
            "numberOfMissingInStatisticalProcess", "typeOfStatisticalProcessing", "typeOfTimeIncrement",
            "indicatorOfUnitForTimeRange", "endStep", "indicatorOfUnitForTimeIncrement", "timeIncrement"}}},
         {1002,
          {{"paramId", "typeOfGeneratingProcess", "backgroundProcess", "generatingProcessIdentifier",
            "hoursAfterDataCutoff", "minutesAfterDataCutoff", "startStep", "forecastTime",
            "horizontalDimensionProcessed", "treatmentOfMissingData", "typeOfStatisticalProcessing", "startOfRange",
            "endOfRange", "numberOfDataValues"}}},
         {1100,
          {{"paramId", "typeOfGeneratingProcess", "backgroundProcess", "generatingProcessIdentifier",
            "hoursAfterDataCutoff", "minutesAfterDataCutoff", "startStep", "forecastTime", "typeOfLevel"}}},
         {1101,
          {{"paramId", "typeOfGeneratingProcess", "backgroundProcess", "generatingProcessIdentifier",
            "hoursAfterDataCutoff", "minutesAfterDataCutoff", "startStep", "forecastTime", "typeOfLevel", "endStep",
            "numberOfTimeRange", "numberOfMissingInStatisticalProcess", "typeOfStatisticalProcessing",
            "typeOfTimeIncrement", "indicatorOfUnitForTimeRange", "indicatorOfUnitForTimeIncrement",
            "timeIncrement"}}}}};

    if (auto search = map.find(pdt); search != map.end()) {
        return std::cref(search->second);
    }

    std::ostringstream oss;
    oss << "Unknown ProductDefinitionTemplate " << pdt;
    return Error{oss.str()};
}

template <typename LookupValueAsOptString>
Result<std::reference_wrapper<const KeyInfo>> keyInfoForKey(const Key& k) noexcept {
    static const KeyInfoMap map{
        {{"paramId", {{KeyType::IntType}, {{"parameterCategory", "parameterNumber"}}}},
         {"parameterCategory", {{KeyType::IntType}, {{}}}},
         {"parameterNumber", {{KeyType::IntType}, {{}}}},
         {"startStep", {{KeyType::IntType, KeyType::StringType}, {{"indicatorOfUnitOfTimeRange"}}}},
         {"endStep",
          {{KeyType::IntType, KeyType::StringType},
           {{"yearOfEndOfOverallTimeInterval", "monthOfEndOfOverallTimeInterval", "dayOfEndOfOverallTimeInterval",
             "hourOfEndOfOverallTimeInterval", "minuteOfEndOfOverallTimeInterval", "secondOfEndOfOverallTimeInterval",
             "lengthOfTimeRange"}}}},
         {"hoursAfterDataCutoff", {{KeyType::IntType}, {{}}}},
         {"minutesAfterDataCutoff", {{KeyType::IntType}, {{}}}},
         {"indicatorOfUnitOfTimeRange", {{KeyType::IntType}, {{}}}},
         {"forecastTime", {{KeyType::IntType, KeyType::IntArrayType}, {{}}}},
         {"lengthOfTimeRange", {{KeyType::IntType, KeyType::IntArrayType}, {{}}}},
         {"typeOfStatisticalProcessing", {{KeyType::IntType, KeyType::IntArrayType}, {{}}}},
         {"yearOfEndOfOverallTimeInterval", {{KeyType::IntType}, {{}}}},
         {"monthOfEndOfOverallTimeInterval", {{KeyType::IntType}, {{}}}},
         {"dayOfEndOfOverallTimeInterval", {{KeyType::IntType}, {{}}}},
         {"hourOfEndOfOverallTimeInterval", {{KeyType::IntType}, {{}}}},
         {"minuteOfEndOfOverallTimeInterval", {{KeyType::IntType}, {{}}}},
         {"secondOfEndOfOverallTimeInterval", {{KeyType::IntType}, {{}}}},
         {"numberOfTimeRange", {{KeyType::IntType}, {{}}}},
         {"numberOfMissingInStatisticalProcess", {{KeyType::IntType, KeyType::IntArrayType}, {{}}}},
         {"typeOfTimeIncrement", {{KeyType::IntType, KeyType::IntArrayType}, {{}}}},
         {"indicatorOfUnitForTimeIncrement", {{KeyType::IntType, KeyType::IntArrayType}, {{}}}},
         {"timeIncrement", {{KeyType::IntType, KeyType::IntArrayType}, {{}}}},
         {"typeOfLevel",
          {{KeyType::StringType},
           {{"typeOfFirstFixedSurface", "scaleFactorOfFirstFixedSurface", "scaledValueOfFirstFixedSurface",
             "scaleFactorOfSecondFixedSurface", "scaledValueOfSecondFixedSurface", "typeOfSecondFixedSurface",
             "pressureUnits", "genVertHeightCoords"}}}},
         {"typeOfFirstFixedSurface", {{KeyType::IntType}, {{}}}},
         {"typeOfSecondFixedSurface", {{KeyType::IntType}, {{}}}},
         {"scaleFactorOfFirstFixedSurface", {{KeyType::IntType}, {{}}}},
         {"scaledValueOfFirstFixedSurface", {{KeyType::IntType}, {{}}}},
         {"scaleFactorOfSecondFixedSurface", {{KeyType::IntType}, {{}}}},
         {"scaledValueOfSecondFixedSurface", {{KeyType::IntType}, {{}}}},
         {"scaleFactorOfLowerLimit", {{KeyType::IntArrayType}, {{}}}},
         {"scaledValueOfLowerLimit", {{KeyType::IntArrayType}, {{}}}},
         {"scaleFactorOfUpperLimit", {{KeyType::IntArrayType}, {{}}}},
         {"scaledValueOfUpperLimit", {{KeyType::IntArrayType}, {{}}}},
         {"probabilityType", {{KeyType::IntType}, {{}}}},
         {"forecastProbabilityNumber", {{KeyType::IntType}, {{}}}},
         {"totalNumberOfForecastProbabilities", {{KeyType::IntType}, {{}}}},
         {"percentileValue", {{KeyType::IntType}, {{}}}},
         {"statisticalProcess", {{KeyType::IntType}, {{}}}},
         {"spatialProcessing", {{KeyType::IntType}, {{}}}},
         {"numberOfPointsUsed", {{KeyType::IntType}, {{}}}},
         {"typeOfGeneratingProcess", {{KeyType::IntType}, {{}}}},
         {"backgroundProcess", {{KeyType::IntType}, {{}}}},
         {"generatingProcessIdentifier", {{KeyType::IntType}, {{}}}},
         {"numberOfRadarSitesUsed", {{KeyType::IntType}, {{}}}},
         {"siteLatitude", {{KeyType::IntType}, {{}}}},
         {"siteLongitude", {{KeyType::IntType}, {{}}}},
         {"siteElevation", {{KeyType::IntType}, {{}}}},
         {"siteId", {{KeyType::IntType}, {{}}}},
         {"operatingMode", {{KeyType::IntType}, {{}}}},
         {"reflectivityCalibrationConstant", {{KeyType::IntType}, {{}}}},
         {"qualityControlIndicator", {{KeyType::IntType}, {{}}}},
         {"clutterFilterIndicator", {{KeyType::IntType}, {{}}}},
         {"constantAntennaElevationAngle", {{KeyType::IntType}, {{}}}},
         {"accumulationInterval", {{KeyType::IntType}, {{}}}},
         {"referenceReflectivityForEchoTop", {{KeyType::IntType}, {{}}}},
         {"rangeBinSpacing", {{KeyType::IntType}, {{}}}},
         {"radialAngularSpacing", {{KeyType::IntType}, {{}}}},
         {"observationGeneratingProcessIdentifier", {{KeyType::IntType}, {{}}}},
         {"numberOfContributingSpectralBands", {{KeyType::IntType}, {{}}}},
         {"satelliteSeries", {{KeyType::IntArrayType}, {{}}}},
         {"satelliteNumber", {{KeyType::IntArrayType}, {{}}}},
         {"instrumentType", {{KeyType::IntArrayType}, {{}}}},
         {"scaleFactorOfCentralWaveNumber", {{KeyType::IntArrayType}, {{}}}},
         {"scaledValueOfCentralWaveNumber", {{KeyType::IntArrayType}, {{}}}},
         {"qualityValueAssociatedWithParameter", {{KeyType::IntType}, {{}}}},
         {"constituentType", {{KeyType::IntType}, {{}}}},
         {"sourceSinkChemicalPhysicalProcess", {{KeyType::IntType}, {{}}}},
         {"numberOfModeOfDistribution", {{KeyType::IntType}, {{}}}},
         {"modeNumber", {{KeyType::IntType}, {{}}}},
         {"typeOfDistributionFunction", {{KeyType::IntType}, {{}}}},
         {"numberOfDistributionFunctionParameters", {{KeyType::IntType}, {{}}}},
         {"scaleFactorOfDistributionFunctionParameter", {{KeyType::IntArrayType}, {{}}}},
         {"scaledValueOfDistributionFunctionParameter", {{KeyType::IntArrayType}, {{}}}},
         {"aerosolType", {{KeyType::IntType}, {{}}}},
         {"typeOfSizeInterval", {{KeyType::IntType}, {{}}}},
         {"scaleFactorOfFirstSize", {{KeyType::IntType}, {{}}}},
         {"scaledValueOfFirstSize", {{KeyType::IntType}, {{}}}},
         {"scaleFactorOfSecondSize", {{KeyType::IntType}, {{}}}},
         {"scaledValueOfSecondSize", {{KeyType::IntType}, {{}}}},
         {"typeOfWavelengthInterval", {{KeyType::IntType}, {{}}}},
         {"scaleFactorOfFirstWavelength", {{KeyType::IntType}, {{}}}},
         {"scaledValueOfFirstWavelength", {{KeyType::IntType}, {{}}}},
         {"scaleFactorOfSecondWavelength", {{KeyType::IntType}, {{}}}},
         {"scaledValueOfSecondWavelength", {{KeyType::IntType}, {{}}}},
         {"numberOfForecastsInEnsemble", {{KeyType::IntType}, {{}}}},
         {"perturbationNumber", {{KeyType::IntType}, {{}}}},
         {"typeOfEnsembleForecast", {{KeyType::IntType}, {{}}}},
         {"derivedForecast", {{KeyType::IntType}, {{}}}},
         {"numberOfCategories", {{KeyType::IntType}, {{}}}},
         {"codeFigure", {{KeyType::IntArrayType}, {{}}}},
         {"categoryType", {{KeyType::IntArrayType}, {{}}}},
         {"partitionTable", {{KeyType::IntType}, {{}}}},
         {"numberOfPartitions", {{KeyType::IntType}, {{}}}},
         {"partitionItems", {{KeyType::IntArrayType}, {{}}}},
         {"partitionNumber", {{KeyType::IntArrayType}, {{}}}},
         {"clusterIdentifier", {{KeyType::IntType}, {{}}}},
         {"NH", {{KeyType::IntType}, {{}}}},
         {"NL", {{KeyType::IntType}, {{}}}},
         {"totalNumberOfClusters", {{KeyType::IntType}, {{}}}},
         {"clusteringMethod", {{KeyType::IntType}, {{}}}},
         {"numberOfForecastsInTheCluster", {{KeyType::IntType}, {{}}}},
         {"scaleFactorOfStandardDeviation", {{KeyType::IntType}, {{}}}},
         {"scaledValueOfStandardDeviation", {{KeyType::IntType}, {{}}}},
         {"scaleFactorOfDistanceFromEnsembleMean", {{KeyType::IntType}, {{}}}},
         {"scaledValueOfDistanceFromEnsembleMean", {{KeyType::IntType}, {{}}}},
         {"ensembleForecastNumbers", {{KeyType::IntType}, {{}}}},
         {"northernLatitudeOfClusterDomain", {{KeyType::IntType}, {{}}}},
         {"southernLatitudeOfClusterDomain", {{KeyType::IntType}, {{}}}},
         {"easternLongitudeOfClusterDomain", {{KeyType::IntType}, {{}}}},
         {"westernLongitudeOfClusterDomain", {{KeyType::IntType}, {{}}}},
         {"latitudeOfCentralPointInClusterDomain", {{KeyType::IntType}, {{}}}},
         {"longitudeOfCentralPointInClusterDomain", {{KeyType::IntType}, {{}}}},
         {"radiusOfClusterDomain", {{KeyType::IntType}, {{}}}},
         {"YearOfModelVersion", {{KeyType::IntType}, {{}}}},
         {"MonthOfModelVersion", {{KeyType::IntType}, {{}}}},
         {"DayOfModelVersion", {{KeyType::IntType}, {{}}}},
         {"HourOfModelVersion", {{KeyType::IntType}, {{}}}},
         {"MinuteOfModelVersion", {{KeyType::IntType}, {{}}}},
         {"SecondOfModelVersion", {{KeyType::IntType}, {{}}}},
         {"inputProcessIdentifier", {{KeyType::IntType}, {{}}}},
         {"inputOriginatingCentre", {{KeyType::IntType}, {{}}}},
         {"typeOfPostProcessing", {{KeyType::IntType}, {{}}}},
         {"tileClassification", {{KeyType::IntType}, {{}}}},
         {"totalNumberOfTileAttributePairs", {{KeyType::IntType}, {{}}}},
         {"numberOfUsedSpatialTiles", {{KeyType::IntType}, {{}}}},
         {"tileIndex", {{KeyType::IntType}, {{}}}},
         {"numberOfUsedTileAttributes", {{KeyType::IntType}, {{}}}},
         {"attributeOfTile", {{KeyType::IntType}, {{}}}},
         {"totalNumberOfQuantiles", {{KeyType::IntType}, {{}}}},
         {"quantileValue", {{KeyType::IntType}, {{}}}},
         {"localTimeMethod", {{KeyType::IntType}, {{}}}},
         {"numberOfForecastsUsedinLocalTime", {{KeyType::IntType}, {{}}}},
         {"yearOfForecastUsedInLocalTime", {{KeyType::IntType, KeyType::IntArrayType}, {{}}}},
         {"monthOfForecastUsedInLocalTime", {{KeyType::IntType, KeyType::IntArrayType}, {{}}}},
         {"dayOfForecastUsedInLocalTime", {{KeyType::IntType, KeyType::IntArrayType}, {{}}}},
         {"hourOfForecastUsedInLocalTime", {{KeyType::IntType, KeyType::IntArrayType}, {{}}}},
         {"minuteOfForecastUsedInLocalTime", {{KeyType::IntType, KeyType::IntArrayType}, {{}}}},
         {"secondOfForecastUsedInLocalTime", {{KeyType::IntType, KeyType::IntArrayType}, {{}}}},
         {"indicatorOfUnitForForecastTime", {{KeyType::IntType, KeyType::IntArrayType}, {{}}}},
         {"numberOfTimeIncrementsOfForecastsUsedInLocalTime", {{KeyType::IntType, KeyType::IntArrayType}, {{}}}},
         {"numberOfStatisticallyProcessedFieldsForLocalTime", {{KeyType::IntType}, {{}}}},
         {"horizontalDimensionProcessed", {{KeyType::IntType}, {{}}}},
         {"treatmentOfMissingData", {{KeyType::IntType}, {{}}}},
         {"startOfRange", {{KeyType::IntType}, {{}}}},
         {"endOfRange", {{KeyType::IntType}, {{}}}},
         {"numberOfDataValues", {{KeyType::IntType}, {{}}}},
         {"waveDirectionNumber", {{KeyType::IntType}, {{}}}},
         {"numberOfWaveDirections", {{KeyType::IntType}, {{}}}},
         {"waveFrequencyNumber", {{KeyType::IntType}, {{}}}},
         {"numberOfWaveFrequencies", {{KeyType::IntType}, {{}}}},
         {"scaleFactorOfWaveDirections", {{KeyType::IntType}, {{}}}},
         {"scaledValueOfWaveDirections", {{KeyType::IntType, KeyType::IntArrayType}, {{}}}},
         {"scaleFactorOfWaveFrequencies", {{KeyType::IntType}, {{}}}},
         {"scaledValueOfWaveFrequencies", {{KeyType::IntType, KeyType::IntArrayType}, {{}}}},
         {"typeOfWaveDirectionSequence", {{KeyType::IntType}, {{}}}},
         {"numberOfWaveDirectionSequenceParameters", {{KeyType::IntType}, {{}}}},
         {"scaleFactorOfWaveDirectionSequenceParameter", {{KeyType::IntType, KeyType::IntArrayType}, {{}}}},
         {"scaledValueOfWaveDirectionSequenceParameter", {{KeyType::IntType, KeyType::IntArrayType}, {{}}}},
         {"typeOfWaveFrequencySequence", {{KeyType::IntType}, {{}}}},
         {"numberOfWaveFrequencySequenceParameters", {{KeyType::IntType}, {{}}}},
         {"scaleFactorOfWaveFrequencySequenceParameter", {{KeyType::IntType, KeyType::IntArrayType}, {{}}}},
         {"scaledValueOfWaveFrequencySequenceParameter", {{KeyType::IntType, KeyType::IntArrayType}, {{}}}},
         {"typeOfWavePeriodInterval", {{KeyType::IntType}, {{}}}},
         {"scaleFactorOfLowerWavePeriodLimit", {{KeyType::IntType}, {{}}}},
         {"scaledValueOfLowerWavePeriodLimit", {{KeyType::IntType}, {{}}}},
         {"scaleFactorOfUpperWavePeriodLimit", {{KeyType::IntType}, {{}}}},
         {"scaledValueOfUpperWavePeriodLimit", {{KeyType::IntType}, {{}}}},
         {"typeOfReferenceDataset", {{KeyType::IntType}, {{}}}},
         {"typeOfRelationToReferenceDataset", {{KeyType::IntType}, {{}}}},
         {"numberOfAdditionalParameterForReferencePeriod", {{KeyType::IntType}, {{}}}},
         {"scaleFactorOfAdditionalParameterForReferencePeriod", {{KeyType::IntType, KeyType::IntArrayType}, {{}}}},
         {"scaledValueOfAdditionalParameterForReferencePeriod", {{KeyType::IntType, KeyType::IntArrayType}, {{}}}},
         {"yearOfStartOfReferencePeriod", {{KeyType::IntType}, {{}}}},
         {"monthOfStartOfReferencePeriod", {{KeyType::IntType}, {{}}}},
         {"dayOfStartOfReferencePeriod", {{KeyType::IntType}, {{}}}},
         {"hourOfStartOfReferencePeriod", {{KeyType::IntType}, {{}}}},
         {"minuteOfStartOfReferencePeriod", {{KeyType::IntType}, {{}}}},
         {"secondOfStartOfReferencePeriod", {{KeyType::IntType}, {{}}}},
         {"sampleSizeOfReferencePeriod", {{KeyType::IntType}, {{}}}},
         {"numberOfReferencePeriodTimeRanges", {{KeyType::IntType}, {{}}}},
         {"typeOfStatisticalProcessingForTimeRangeForReferencePeriod",
          {{KeyType::IntType, KeyType::IntArrayType}, {{}}}},
         {"indicatorOfUnitForTimeRangeForReferencePeriod", {{KeyType::IntType, KeyType::IntArrayType}, {{}}}},
         {"lengthOfTimeRangeForReferencePeriod", {{KeyType::IntType, KeyType::IntArrayType}, {{}}}}}};

    if (auto search = map.find(k); search != map.end()) {
        return std::cref(search->second);
    }

    std::ostringstream oss;
    oss << "Unknown key " << k;
    return Error{oss.str()};
}

}  // namespace multio::grib2
