#include "output_manager_preprocessor_utils.h"
#include "output_manager_preprocessor_trace_utils.h"
#include "output_manager_preprocessor_logging_utils.h"
#include "output_manager_preprocessor_errhdl_utils.h"


#define PP_FILE_NAME 'encoders_utils_mod.F90'
#define PP_SECTION_TYPE 'MODULE'
#define PP_SECTION_NAME 'ENCODERS_UTILS_MOD'
MODULE ENCODERS_UTILS_MOD

  ! Symbols imported from other modules within the project (preset).
  USE :: GENERAL_PRESET_UTILS_MOD,     ONLY: LATEST_TABLE_VERSION
  USE :: GENERAL_PRESET_UTILS_MOD,     ONLY: GENERATING_PROCESS_IDENTIFIER_PRESET
  USE :: TIME_PRESET_UTILS_MOD,        ONLY: TIME_PRESET_GRIBX_ATM
  USE :: GEOMETRY_PRESET_UTILS_MOD,    ONLY: GG_GEOMETRY_PRESET_GRIB2_WAM_S
  USE :: GEOMETRY_PRESET_UTILS_MOD,    ONLY: GG_GEOMETRY_PRESET_GRIBX_ATM
  USE :: GEOMETRY_PRESET_UTILS_MOD,    ONLY: SH_GEOMETRY_PRESET_GRIBX_ATM
  USE :: GEOMETRY_PRESET_UTILS_MOD,    ONLY: VERTICAL_LEVELS_PRESET_GRIBX_ATM
  USE :: MARS_PRESET_UTILS_MOD,        ONLY: MARS_PRESET_GRIB2_WAM_S
  USE :: MARS_PRESET_UTILS_MOD,        ONLY: MARS_PRESET_GRIB2_WAM_I
  USE :: MARS_PRESET_UTILS_MOD,        ONLY: MARS_LSSI_PRESET_GRIBX_ATM
  USE :: MARS_PRESET_UTILS_MOD,        ONLY: MARS_PRESET_GRIBX_ATM

  ! Symbols imported from other modules within the project (runtime).
  USE :: PACKAGING_RUNTIME_UTILS_MOD,  ONLY: SET_MISSING_VALUE_GG_GRIBX_ATM
  USE :: PACKAGING_RUNTIME_UTILS_MOD,  ONLY: SET_BITS_PER_VALUE_GG_GRIBX_ATM
  USE :: PACKAGING_RUNTIME_UTILS_MOD,  ONLY: SET_PACKING_SH_GRIBX_ATM
  USE :: LEVELS_RUNTIME_UTILS_MOD,     ONLY: SET_SURFACE_LEVEL_GRIBX_ATM
  USE :: LEVELS_RUNTIME_UTILS_MOD,     ONLY: SET_MODEL_LEVEL_GRIBX_ATM
  USE :: LEVELS_RUNTIME_UTILS_MOD,     ONLY: SET_PRESSURE_LEVEL_GRIBX_ATM
  USE :: LEVELS_RUNTIME_UTILS_MOD,     ONLY: SET_VORTICITY_LEVEL_GRIBX_ATM
  USE :: LEVELS_RUNTIME_UTILS_MOD,     ONLY: SET_THETA_LEVEL_GRIBX_ATM
  USE :: PARAMETERS_RUNTIME_UTILS_MOD, ONLY: COMPUTE_PARAM_GRIBX_ATM
  USE :: TIME_RUNTIME_UTILS_MOD,       ONLY: TIME_ENCODERS_ATM
  USE :: TIME_RUNTIME_UTILS_MOD,       ONLY: TIME_ENCODERS_WAM
  USE :: TIME_RUNTIME_UTILS_MOD,       ONLY: TIME_INDEXER

IMPLICIT NONE

! Default visibility
PRIVATE

! Whitelist of public symbols (preset utils)
PUBLIC :: LATEST_TABLE_VERSION
PUBLIC :: GENERATING_PROCESS_IDENTIFIER_PRESET
PUBLIC :: TIME_PRESET_GRIBX_ATM
PUBLIC :: GG_GEOMETRY_PRESET_GRIB2_WAM_S
PUBLIC :: GG_GEOMETRY_PRESET_GRIBX_ATM
PUBLIC :: SH_GEOMETRY_PRESET_GRIBX_ATM
PUBLIC :: VERTICAL_LEVELS_PRESET_GRIBX_ATM
PUBLIC :: MARS_PRESET_GRIB2_WAM_S
PUBLIC :: MARS_PRESET_GRIB2_WAM_I
PUBLIC :: MARS_LSSI_PRESET_GRIBX_ATM
PUBLIC :: MARS_PRESET_GRIBX_ATM

! Whitelist of public symbols (runtime utils)
PUBLIC :: SET_MISSING_VALUE_GG_GRIBX_ATM
PUBLIC :: SET_BITS_PER_VALUE_GG_GRIBX_ATM
PUBLIC :: SET_PACKING_SH_GRIBX_ATM
PUBLIC :: SET_SURFACE_LEVEL_GRIBX_ATM
PUBLIC :: SET_MODEL_LEVEL_GRIBX_ATM
PUBLIC :: SET_PRESSURE_LEVEL_GRIBX_ATM
PUBLIC :: SET_VORTICITY_LEVEL_GRIBX_ATM
PUBLIC :: SET_THETA_LEVEL_GRIBX_ATM
PUBLIC :: COMPUTE_PARAM_GRIBX_ATM
PUBLIC :: TIME_INDEXER
PUBLIC :: TIME_ENCODERS_ATM
PUBLIC :: TIME_ENCODERS_WAM

! Whitelist of memory management procedures
PUBLIC :: UTILS_INIT
PUBLIC :: UTILS_FREE


CONTAINS

#define PP_PROCEDURE_TYPE 'SUBROUTINE'
#define PP_PROCEDURE_NAME 'UTILS_INIT'
SUBROUTINE UTILS_INIT( CFG, MODEL_PARAMS )

  ! Symbols imported from other modules within the project.
  USE :: OM_CORE_MOD, ONLY: MODEL_PAR_T

  USE :: GENERAL_PRESET_UTILS_MOD,     ONLY: GENERAL_PRESET_INIT
  USE :: TIME_PRESET_UTILS_MOD,        ONLY: TIME_PRESET_INIT
  USE :: GEOMETRY_PRESET_UTILS_MOD,    ONLY: GEOMETRY_PRESET_INIT
  USE :: MARS_PRESET_UTILS_MOD,        ONLY: MARS_PRESET_INIT
  USE :: PACKAGING_RUNTIME_UTILS_MOD,  ONLY: PACKAGING_RUNTIME_INIT
  USE :: LEVELS_RUNTIME_UTILS_MOD,     ONLY: LEVELS_RUNTIME_INIT
  USE :: PARAMETERS_RUNTIME_UTILS_MOD, ONLY: PARAMETERS_RUNTIME_INIT
  USE :: TIME_RUNTIME_UTILS_MOD,       ONLY: TIME_RUNTIME_INIT

  ! Symbols imported from other libraries
  USE :: FCKIT_CONFIGURATION_MODULE, ONLY: FCKIT_CONFIGURATION

  ! Symbols imported by the preprocessor for debugging purposes
  PP_DEBUG_USE_VARS

  ! Symbols imported by the preprocessor for tracing purposes
  PP_TRACE_USE_VARS

IMPLICIT NONE

  ! Dummy arguments
  TYPE(FCKIT_CONFIGURATION), INTENT(IN) :: CFG
  TYPE(MODEL_PAR_T),         INTENT(IN) :: MODEL_PARAMS

  ! Local variables declared by the preprocessor for debugging purposes
  PP_DEBUG_DECL_VARS

  ! Local variables declared by the preprocessor for tracing purposes
  PP_TRACE_DECL_VARS

  ! Trace begin of procedure
  PP_TRACE_ENTER_PROCEDURE()

  CALL GENERAL_PRESET_INIT( CFG, MODEL_PARAMS )
  CALL TIME_PRESET_INIT( CFG, MODEL_PARAMS )
  CALL GEOMETRY_PRESET_INIT( CFG, MODEL_PARAMS )
  CALL MARS_PRESET_INIT( CFG, MODEL_PARAMS )
  CALL PACKAGING_RUNTIME_INIT( CFG, MODEL_PARAMS )
  CALL LEVELS_RUNTIME_INIT( CFG, MODEL_PARAMS )
  CALL PARAMETERS_RUNTIME_INIT( CFG, MODEL_PARAMS )
  CALL TIME_RUNTIME_INIT( CFG, MODEL_PARAMS )

  ! Trace end of procedure (on success)
  PP_TRACE_EXIT_PROCEDURE_ON_SUCCESS()

  ! Exit point
  RETURN

END SUBROUTINE UTILS_INIT
#undef PP_PROCEDURE_NAME
#undef PP_PROCEDURE_TYPE


#define PP_PROCEDURE_TYPE 'SUBROUTINE'
#define PP_PROCEDURE_NAME 'UTILS_FREE'
SUBROUTINE UTILS_FREE(  )

  ! Symbols imported from other modules within the project.
  USE :: GENERAL_PRESET_UTILS_MOD,     ONLY: GENERAL_PRESET_FREE
  USE :: TIME_PRESET_UTILS_MOD,        ONLY: TIME_PRESET_FREE
  USE :: GEOMETRY_PRESET_UTILS_MOD,    ONLY: GEOMETRY_PRESET_FREE
  USE :: MARS_PRESET_UTILS_MOD,        ONLY: MARS_PRESET_FREE
  USE :: PACKAGING_RUNTIME_UTILS_MOD,  ONLY: PACKAGING_RUNTIME_FREE
  USE :: LEVELS_RUNTIME_UTILS_MOD,     ONLY: LEVELS_RUNTIME_FREE
  USE :: PARAMETERS_RUNTIME_UTILS_MOD, ONLY: PARAMETERS_RUNTIME_FREE
  USE :: TIME_RUNTIME_UTILS_MOD,       ONLY: TIME_RUNTIME_FREE


  ! Symbols imported by the preprocessor for debugging purposes
  PP_DEBUG_USE_VARS

  ! Symbols imported by the preprocessor for tracing purposes
  PP_TRACE_USE_VARS

IMPLICIT NONE

  ! Local variables declared by the preprocessor for debugging purposes
  PP_DEBUG_DECL_VARS

  ! Local variables declared by the preprocessor for tracing purposes
  PP_TRACE_DECL_VARS

  ! Trace begin of procedure
  PP_TRACE_ENTER_PROCEDURE()

  CALL GENERAL_PRESET_FREE( )
  CALL TIME_PRESET_FREE( )
  CALL GEOMETRY_PRESET_FREE( )
  CALL MARS_PRESET_FREE( )
  CALL PACKAGING_RUNTIME_FREE( )
  CALL LEVELS_RUNTIME_FREE( )
  CALL PARAMETERS_RUNTIME_FREE( )
  CALL TIME_RUNTIME_FREE( )

  ! Trace end of procedure (on success)
  PP_TRACE_EXIT_PROCEDURE_ON_SUCCESS()

  ! Exit point
  RETURN

END SUBROUTINE UTILS_FREE
#undef PP_PROCEDURE_NAME
#undef PP_PROCEDURE_TYPE

END MODULE ENCODERS_UTILS_MOD