reader:
  # mode: eccodes-stream
  # Use this instead to enable candidate-based boundary detection:
  mode: candidate-boundary

stages:
  grib-based-filter:
    verbosity: 0
    grib1-messages-policy: try-to-handle
    grib2-messages-policy: try-to-handle
    invalid-messages-policy: try-to-handle
    discipline192-messages-policy:
        try-to-handle: ["4i", "me"]

  grib-to-mars:
    verbosity: 0
    api-options:
      tryFixBadInput_ZeroAccumulation: true
      tryFixBadInput_RemoveStepRangeForStrikeProbability: true
      tryFixBadInput_StandardisedAnomalyAsInstant: true
      tryFixDiscipline192-me-and-4i: true
      saveErrorStack: false
      errorStackPath: "./"
      printErrorStackToStdErr: false

  mars-to-mars:
    verbosity: 0
    api-options:
      tryFixBadInput_ZeroAccumulation: true
      saveErrorStack: false
      errorStackPath: "/lus/h1tcst01/mavm_temp_scratch_mtg2/errors"
      printErrorStackToStdErr: false

  overrides:
    verbosity: 0
    packing: ccsds
    ncycle: 162
    control: false
    expver: "2250"

  mars-based-filter:
    verbosity: 0
    api-options:
      allowFromStartStatisticsForAnalisys: false
      allowPartialStatisticsWindow: false
      allowExtendedSetOfOperationsForZeroLengthFsWindow: false
    selectors:
      match:
        param: [133093, 133094, 133095, 133096, 133097, 133098]

  mars-to-grib:
    verbosity: 0
    generate-testcases: true
    testcases-dir: "/lus/h1tcst01/mavm_temp_scratch_mtg2/test-cases-02"
    api-options:
      saveErrorStack: true
      errorStackPath: "/lus/h1tcst01/mavm_temp_scratch_mtg2/errors"
      printErrorStackToStdErr: true

  post-encode-validation:
    verbosity: 0

  grib2fdb5:
    verbosity: 0

sink:
  enabled: false
  type: fdb5
  config:
    # fdb_home: /home/fdbsc
    fdb_home: "/lus/h1tcst01/mavm_temp_scratch_mtg2/fdb-mdst/"
    userConfig:
      useSubToc: true
