
#pragma once
#include <unordered_map>
#include <vector>

#include "multio/message/Metadata.h"

namespace multio::grib2::test {

struct PdtWithSelector {
    std::int64_t productDefinitionTemplateNumber;
    message::Metadata selector;
};

const static std::vector<PdtWithSelector> mappedPdtAndSelectors{
    {20, {{"timeExtent", "None"}, {"timeFormat", "None"}, {"processType", "None"}, {"productCategory", "radar"}}},
    {254, {{"timeExtent", "None"}, {"timeFormat", "None"}, {"processType", "None"}, {"productCategory", "ccittIA5"}}},
    {31,
     {{"timeExtent", "None"},
      {"timeFormat", "None"},
      {"processType", "None"},
      {"productCategory", "satellite"},
      {"productSubCategory", "None"}}},
    {35,
     {{"timeExtent", "None"},
      {"timeFormat", "None"},
      {"processType", "None"},
      {"productCategory", "satellite"},
      {"productSubCategory", "qualityValue"}}},
    {0, {{"timeExtent", "pointInTime"}, {"timeFormat", "None"}, {"processType", "None"}, {"productCategory", "None"}}},
    {70,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "None"},
      {"productCategory", "postProcess"}}},
    {53,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "None"},
      {"productCategory", "partitioned"}}},
    {15,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "None"},
      {"productCategory", "spatialStatisticalProcessing"}}},
    {55,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "None"},
      {"productCategory", "spatioTemporalTile"}}},
    {1100,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "None"},
      {"productCategory", "hovmoeller"}}},
    {108,
     {{"timeExtent", "pointInTime"}, {"timeFormat", "None"}, {"processType", "None"}, {"productCategory", "optical"}}},
    {99,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "None"},
      {"productCategory", "wave"},
      {"productSubCategory", "spectraList"}}},
    {101,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "None"},
      {"productCategory", "wave"},
      {"productSubCategory", "spectraFormula"}}},
    {103,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "None"},
      {"productCategory", "wave"},
      {"productSubCategory", "periodRange"}}},
    {32,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "None"},
      {"productCategory", "satellite"},
      {"productSubCategory", "None"}}},
    {48,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "None"},
      {"productCategory", "aerosol"},
      {"productSubCategory", "optical"}}},
    {80,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "None"},
      {"productCategory", "aerosol"},
      {"productSubCategory", "opticalSrcsink"}}},
    {40,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "None"},
      {"productCategory", "chemical"},
      {"productSubCategory", "None"}}},
    {76,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "None"},
      {"productCategory", "chemical"},
      {"productSubCategory", "srcsink"}}},
    {57,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "None"},
      {"productCategory", "chemical"},
      {"productSubCategory", "distribution"}}},
    {1000,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "None"},
      {"productCategory", "crossSect"},
      {"productSubCategory", "None"}}},
    {1002,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "None"},
      {"productCategory", "crossSect"},
      {"productSubCategory", "statisticalOverLatLong"}}},
    {1,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "individualEnsemble"},
      {"processSubType", "None"},
      {"productCategory", "None"}}},
    {71,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "individualEnsemble"},
      {"processSubType", "None"},
      {"productCategory", "postProcess"}}},
    {54,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "individualEnsemble"},
      {"processSubType", "None"},
      {"productCategory", "partitioned"}}},
    {59,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "individualEnsemble"},
      {"processSubType", "None"},
      {"productCategory", "spatioTemporalTile"}}},
    {109,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "individualEnsemble"},
      {"processSubType", "None"},
      {"productCategory", "optical"}}},
    {100,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "individualEnsemble"},
      {"processSubType", "None"},
      {"productCategory", "wave"},
      {"productSubCategory", "spectraList"}}},
    {102,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "individualEnsemble"},
      {"processSubType", "None"},
      {"productCategory", "wave"},
      {"productSubCategory", "spectraFormula"}}},
    {104,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "individualEnsemble"},
      {"processSubType", "None"},
      {"productCategory", "wave"},
      {"productSubCategory", "periodRange"}}},
    {33,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "individualEnsemble"},
      {"processSubType", "None"},
      {"productCategory", "satellite"},
      {"productSubCategory", "None"}}},
    {45,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "individualEnsemble"},
      {"processSubType", "None"},
      {"productCategory", "aerosol"},
      {"productSubCategory", "None"}}},
    {49,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "individualEnsemble"},
      {"processSubType", "None"},
      {"productCategory", "aerosol"},
      {"productSubCategory", "optical"}}},
    {81,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "individualEnsemble"},
      {"processSubType", "None"},
      {"productCategory", "aerosol"},
      {"productSubCategory", "opticalSrcsink"}}},
    {41,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "individualEnsemble"},
      {"processSubType", "None"},
      {"productCategory", "chemical"},
      {"productSubCategory", "None"}}},
    {77,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "individualEnsemble"},
      {"processSubType", "None"},
      {"productCategory", "chemical"},
      {"productSubCategory", "srcsink"}}},
    {58,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "individualEnsemble"},
      {"processSubType", "None"},
      {"productCategory", "chemical"},
      {"productSubCategory", "distribution"}}},
    {60,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "individualEnsemble"},
      {"processSubType", "reforecast"},
      {"productCategory", "None"}}},
    {2,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "derivedEnsemble"},
      {"processSubType", "None"},
      {"productCategory", "None"}}},
    {4,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "derivedEnsemble"},
      {"processSubType", "clusterStatCircular"},
      {"productCategory", "None"}}},
    {3,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "derivedEnsemble"},
      {"processSubType", "clusterStatRectangular"},
      {"productCategory", "None"}}},
    {5,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "probability"},
      {"productCategory", "None"}}},
    {6,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "percentile"},
      {"productCategory", "None"}}},
    {86,
     {{"timeExtent", "pointInTime"}, {"timeFormat", "None"}, {"processType", "quantile"}, {"productCategory", "None"}}},
    {51,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "None"},
      {"processType", "categorial"},
      {"productCategory", "None"}}},
    {88,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "localTime"},
      {"processType", "None"},
      {"productCategory", "None"}}},
    {93,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "localTime"},
      {"processType", "None"},
      {"productCategory", "postProcess"}}},
    {92,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "localTime"},
      {"processType", "individualEnsemble"},
      {"processSubType", "None"},
      {"productCategory", "None"}}},
    {94,
     {{"timeExtent", "pointInTime"},
      {"timeFormat", "localTime"},
      {"processType", "individualEnsemble"},
      {"processSubType", "None"},
      {"productCategory", "postProcess"}}},
    {8, {{"timeExtent", "timeRange"}, {"timeFormat", "None"}, {"processType", "None"}, {"productCategory", "None"}}},
    {72,
     {{"timeExtent", "timeRange"},
      {"timeFormat", "None"},
      {"processType", "None"},
      {"productCategory", "postProcess"}}},
    {62,
     {{"timeExtent", "timeRange"},
      {"timeFormat", "None"},
      {"processType", "None"},
      {"productCategory", "spatioTemporalTile"}}},
    {1101,
     {{"timeExtent", "timeRange"}, {"timeFormat", "None"}, {"processType", "None"}, {"productCategory", "hovmoeller"}}},
    {105,
     {{"timeExtent", "timeRange"},
      {"timeFormat", "None"},
      {"processType", "None"},
      {"productCategory", "referencePeriod"}}},
    {110,
     {{"timeExtent", "timeRange"}, {"timeFormat", "None"}, {"processType", "None"}, {"productCategory", "optical"}}},
    {46,
     {{"timeExtent", "timeRange"},
      {"timeFormat", "None"},
      {"processType", "None"},
      {"productCategory", "aerosol"},
      {"productSubCategory", "None"}}},
    {82,
     {{"timeExtent", "timeRange"},
      {"timeFormat", "None"},
      {"processType", "None"},
      {"productCategory", "aerosol"},
      {"productSubCategory", "srcsink"}}},
    {42,
     {{"timeExtent", "timeRange"},
      {"timeFormat", "None"},
      {"processType", "None"},
      {"productCategory", "chemical"},
      {"productSubCategory", "None"}}},
    {78,
     {{"timeExtent", "timeRange"},
      {"timeFormat", "None"},
      {"processType", "None"},
      {"productCategory", "chemical"},
      {"productSubCategory", "srcsink"}}},
    {67,
     {{"timeExtent", "timeRange"},
      {"timeFormat", "None"},
      {"processType", "None"},
      {"productCategory", "chemical"},
      {"productSubCategory", "distribution"}}},
    {1001,
     {{"timeExtent", "timeRange"},
      {"timeFormat", "None"},
      {"processType", "None"},
      {"productCategory", "crossSect"},
      {"productSubCategory", "None"}}},
    {11,
     {{"timeExtent", "timeRange"},
      {"timeFormat", "None"},
      {"processType", "individualEnsemble"},
      {"processSubType", "None"},
      {"productCategory", "None"}}},
    {73,
     {{"timeExtent", "timeRange"},
      {"timeFormat", "None"},
      {"processType", "individualEnsemble"},
      {"processSubType", "None"},
      {"productCategory", "postProcess"}}},
    {63,
     {{"timeExtent", "timeRange"},
      {"timeFormat", "None"},
      {"processType", "individualEnsemble"},
      {"processSubType", "None"},
      {"productCategory", "spatioTemporalTile"}}},
    {106,
     {{"timeExtent", "timeRange"},
      {"timeFormat", "None"},
      {"processType", "individualEnsemble"},
      {"processSubType", "None"},
      {"productCategory", "referencePeriod"}}},
    {111,
     {{"timeExtent", "timeRange"},
      {"timeFormat", "None"},
      {"processType", "individualEnsemble"},
      {"processSubType", "None"},
      {"productCategory", "optical"}}},
    {34,
     {{"timeExtent", "timeRange"},
      {"timeFormat", "None"},
      {"processType", "individualEnsemble"},
      {"processSubType", "None"},
      {"productCategory", "satellite"},
      {"productSubCategory", "None"}}},
    {85,
     {{"timeExtent", "timeRange"},
      {"timeFormat", "None"},
      {"processType", "individualEnsemble"},
      {"processSubType", "None"},
      {"productCategory", "aerosol"},
      {"productSubCategory", "None"}}},
    {84,
     {{"timeExtent", "timeRange"},
      {"timeFormat", "None"},
      {"processType", "individualEnsemble"},
      {"processSubType", "None"},
      {"productCategory", "aerosol"},
      {"productSubCategory", "srcsink"}}},
    {43,
     {{"timeExtent", "timeRange"},
      {"timeFormat", "None"},
      {"processType", "individualEnsemble"},
      {"processSubType", "None"},
      {"productCategory", "chemical"},
      {"productSubCategory", "None"}}},
    {79,
     {{"timeExtent", "timeRange"},
      {"timeFormat", "None"},
      {"processType", "individualEnsemble"},
      {"processSubType", "None"},
      {"productCategory", "chemical"},
      {"productSubCategory", "srcsink"}}},
    {68,
     {{"timeExtent", "timeRange"},
      {"timeFormat", "None"},
      {"processType", "individualEnsemble"},
      {"processSubType", "None"},
      {"productCategory", "chemical"},
      {"productSubCategory", "distribution"}}},
    {61,
     {{"timeExtent", "timeRange"},
      {"timeFormat", "None"},
      {"processType", "individualEnsemble"},
      {"processSubType", "reforecast"},
      {"productCategory", "None"}}},
    {12,
     {{"timeExtent", "timeRange"},
      {"timeFormat", "None"},
      {"processType", "derivedEnsemble"},
      {"processSubType", "None"},
      {"productCategory", "None"}}},
    {107,
     {{"timeExtent", "timeRange"},
      {"timeFormat", "None"},
      {"processType", "derivedEnsemble"},
      {"processSubType", "None"},
      {"productCategory", "referencePeriod"}}},
    {14,
     {{"timeExtent", "timeRange"},
      {"timeFormat", "None"},
      {"processType", "derivedEnsemble"},
      {"processSubType", "clusterStatCircular"},
      {"productCategory", "None"}}},
    {13,
     {{"timeExtent", "timeRange"},
      {"timeFormat", "None"},
      {"processType", "derivedEnsemble"},
      {"processSubType", "clusterStatRectangular"},
      {"productCategory", "None"}}},
    {9,
     {{"timeExtent", "timeRange"},
      {"timeFormat", "None"},
      {"processType", "probability"},
      {"productCategory", "None"}}},
    {112,
     {{"timeExtent", "timeRange"},
      {"timeFormat", "None"},
      {"processType", "probability"},
      {"productCategory", "referencePeriod"}}},
    {10,
     {{"timeExtent", "timeRange"}, {"timeFormat", "None"}, {"processType", "percentile"}, {"productCategory", "None"}}},
    {87,
     {{"timeExtent", "timeRange"}, {"timeFormat", "None"}, {"processType", "quantile"}, {"productCategory", "None"}}},
    {91,
     {{"timeExtent", "timeRange"}, {"timeFormat", "None"}, {"processType", "categorial"}, {"productCategory", "None"}}},
    {95,
     {{"timeExtent", "timeRange"}, {"timeFormat", "localTime"}, {"processType", "None"}, {"productCategory", "None"}}},
    {97,
     {{"timeExtent", "timeRange"},
      {"timeFormat", "localTime"},
      {"processType", "None"},
      {"productCategory", "postProcess"}}},
    {96,
     {{"timeExtent", "timeRange"},
      {"timeFormat", "localTime"},
      {"processType", "individualEnsemble"},
      {"processSubType", "None"},
      {"productCategory", "None"}}},
    {98,
     {{"timeExtent", "timeRange"},
      {"timeFormat", "localTime"},
      {"processType", "individualEnsemble"},
      {"processSubType", "None"},
      {"productCategory", "postProcess"}}}};
}  // namespace multio::grib2::test
