
#pragma once
#include <unordered_map>
#include <vector>

#include "multio/message/Metadata.h"

namespace multio::grib2::test {

struct PdtWithSelector {
    std::int64_t productDefinitionTemplateNumber;
    message::Metadata selector;
};

const static std::vector<PdtWithSelector> mappedPdtAndSelectors{{20,
                                                                 {{"timeExtent", "None"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "radar"}}},
                                                                {254,
                                                                 {{"timeExtent", "None"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "ccittIA5"}}},
                                                                {31,
                                                                 {{"timeExtent", "None"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "satellite"},
                                                                  {"productSubCategory", "None"}}},
                                                                {35,
                                                                 {{"timeExtent", "None"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "satellite"},
                                                                  {"productSubCategory", "qualityValue"}}},
                                                                {0,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "None"}}},
                                                                {70,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "postProcess"}}},
                                                                {53,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "partitioned"}}},
                                                                {15,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "spatialStatisticalProcessing"}}},
                                                                {55,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "spatioTemporalTile"}}},
                                                                {1100,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "hovmoeller"}}},
                                                                {108,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "optical"}}},
                                                                {99,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "wave"},
                                                                  {"productSubCategory", "spectraList"}}},
                                                                {101,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "wave"},
                                                                  {"productSubCategory", "spectraFormula"}}},
                                                                {103,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "wave"},
                                                                  {"productSubCategory", "periodRange"}}},
                                                                {32,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "satellite"},
                                                                  {"productSubCategory", "None"}}},
                                                                {48,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "aerosol"},
                                                                  {"productSubCategory", "optical"}}},
                                                                {80,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "aerosol"},
                                                                  {"productSubCategory", "opticalSourceSink"}}},
                                                                {40,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "chemical"},
                                                                  {"productSubCategory", "None"}}},
                                                                {76,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "chemical"},
                                                                  {"productSubCategory", "sourceSink"}}},
                                                                {124,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "chemical"},
                                                                  {"productSubCategory", "radioNuclide"}}},
                                                                {57,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "chemical"},
                                                                  {"productSubCategory", "distribution"}}},
                                                                {1000,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "crossSect"},
                                                                  {"productSubCategory", "None"}}},
                                                                {1002,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "crossSect"},
                                                                  {"productSubCategory", "statisticalOverLatLong"}}},
                                                                {117,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "None"}}},
                                                                {71,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "postProcess"}}},
                                                                {54,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "partitioned"}}},
                                                                {59,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "spatioTemporalTile"}}},
                                                                {109,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "optical"}}},
                                                                {100,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "wave"},
                                                                  {"productSubCategory", "spectraList"}}},
                                                                {102,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "wave"},
                                                                  {"productSubCategory", "spectraFormula"}}},
                                                                {104,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "wave"},
                                                                  {"productSubCategory", "periodRange"}}},
                                                                {33,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "satellite"},
                                                                  {"productSubCategory", "None"}}},
                                                                {45,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "aerosol"},
                                                                  {"productSubCategory", "None"}}},
                                                                {49,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "aerosol"},
                                                                  {"productSubCategory", "optical"}}},
                                                                {81,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "aerosol"},
                                                                  {"productSubCategory", "opticalSourceSink"}}},
                                                                {41,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "chemical"},
                                                                  {"productSubCategory", "None"}}},
                                                                {77,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "chemical"},
                                                                  {"productSubCategory", "sourceSink"}}},
                                                                {125,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "chemical"},
                                                                  {"productSubCategory", "radioNuclide"}}},
                                                                {58,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "chemical"},
                                                                  {"productSubCategory", "distribution"}}},
                                                                {60,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "reforecast"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "None"}}},
                                                                {2,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "derivedForecast"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "None"}}},
                                                                {5,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "probability"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "None"}}},
                                                                {119,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "probability"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "None"}}},
                                                                {6,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "percentile"},
                                                                  {"productCategory", "None"}}},
                                                                {86,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "quantile"},
                                                                  {"productCategory", "None"}}},
                                                                {51,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "categorial"},
                                                                  {"productCategory", "None"}}},
                                                                {113,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "generalisedTile"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "None"}}},
                                                                {115,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "generalisedTile"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "None"}}},
                                                                {121,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "focalStatistics"},
                                                                  {"processType", "probability"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "None"}}},
                                                                {4,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "clusterStatCircular"},
                                                                  {"processType", "derivedForecast"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "None"}}},
                                                                {3,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "clusterStatRectangular"},
                                                                  {"processType", "derivedForecast"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "None"}}},
                                                                {88,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "localTime"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "None"}}},
                                                                {93,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "localTime"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "postProcess"}}},
                                                                {92,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "localTime"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "None"}}},
                                                                {94,
                                                                 {{"timeExtent", "pointInTime"},
                                                                  {"timeFormat", "localTime"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "postProcess"}}},
                                                                {8,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "None"}}},
                                                                {72,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "postProcess"}}},
                                                                {62,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "spatioTemporalTile"}}},
                                                                {1101,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "hovmoeller"}}},
                                                                {110,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "optical"}}},
                                                                {46,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "aerosol"},
                                                                  {"productSubCategory", "None"}}},
                                                                {82,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "aerosol"},
                                                                  {"productSubCategory", "sourceSink"}}},
                                                                {42,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "chemical"},
                                                                  {"productSubCategory", "None"}}},
                                                                {78,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "chemical"},
                                                                  {"productSubCategory", "sourceSink"}}},
                                                                {126,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "chemical"},
                                                                  {"productSubCategory", "radioNuclide"}}},
                                                                {67,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "chemical"},
                                                                  {"productSubCategory", "distribution"}}},
                                                                {1001,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "crossSect"},
                                                                  {"productSubCategory", "None"}}},
                                                                {118,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "None"}}},
                                                                {73,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "postProcess"}}},
                                                                {63,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "spatioTemporalTile"}}},
                                                                {111,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "optical"}}},
                                                                {34,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "satellite"},
                                                                  {"productSubCategory", "None"}}},
                                                                {85,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "aerosol"},
                                                                  {"productSubCategory", "None"}}},
                                                                {84,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "aerosol"},
                                                                  {"productSubCategory", "sourceSink"}}},
                                                                {43,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "chemical"},
                                                                  {"productSubCategory", "None"}}},
                                                                {79,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "chemical"},
                                                                  {"productSubCategory", "sourceSink"}}},
                                                                {127,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "chemical"},
                                                                  {"productSubCategory", "radioNuclide"}}},
                                                                {68,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "chemical"},
                                                                  {"productSubCategory", "distribution"}}},
                                                                {61,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "reforecast"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "None"}}},
                                                                {12,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "derivedForecast"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "None"}}},
                                                                {9,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "probability"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "None"}}},
                                                                {120,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "probability"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "None"}}},
                                                                {10,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "percentile"},
                                                                  {"productCategory", "None"}}},
                                                                {87,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "quantile"},
                                                                  {"productCategory", "None"}}},
                                                                {91,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "categorial"},
                                                                  {"productCategory", "None"}}},
                                                                {114,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "generalisedTile"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "None"}}},
                                                                {116,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "generalisedTile"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "None"}}},
                                                                {122,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "focalStatistics"},
                                                                  {"processType", "probability"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "None"}}},
                                                                {14,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "clusterStatCircular"},
                                                                  {"processType", "derivedForecast"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "None"}}},
                                                                {13,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "None"},
                                                                  {"spatialExtent", "clusterStatRectangular"},
                                                                  {"processType", "derivedForecast"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "None"}}},
                                                                {95,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "localTime"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "None"}}},
                                                                {97,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "localTime"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "postProcess"}}},
                                                                {96,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "localTime"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "None"}}},
                                                                {98,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "localTime"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "postProcess"}}},
                                                                {105,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "withReferencePeriod"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "None"}}},
                                                                {106,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "withReferencePeriod"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "None"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "None"}}},
                                                                {107,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "withReferencePeriod"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "derivedForecast"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "None"}}},
                                                                {112,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "withReferencePeriod"},
                                                                  {"spatialExtent", "None"},
                                                                  {"processType", "probability"},
                                                                  {"processSubType", "None"},
                                                                  {"productCategory", "None"}}},
                                                                {123,
                                                                 {{"timeExtent", "timeRange"},
                                                                  {"timeFormat", "withReferencePeriod"},
                                                                  {"spatialExtent", "focalStatistics"},
                                                                  {"processType", "probability"},
                                                                  {"processSubType", "ensemble"},
                                                                  {"productCategory", "None"}}}};
}  // namespace multio::grib2::test
