! Include preprocessor utils
#include "output_manager_preprocessor_utils.h"
#include "output_manager_preprocessor_trace_utils.h"
#include "output_manager_preprocessor_logging_utils.h"
#include "output_manager_preprocessor_errhdl_utils.h"

#define PP_FILE_NAME 'multiom_feed_prog.F90'
#define PP_SECTION_TYPE 'PROGRAM'
#define PP_SECTION_NAME 'MULTIOM_FEED_PROG'
#define PP_PROCEDURE_TYPE 'PROGRAM'
#define PP_PROCEDURE_NAME 'MULTIOM_FEED_PROG'
PROGRAM MULTIOM_FEED_PROG

  ! Symbolds imported from intrinsic modules
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: OUTPUT_UNIT
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: ERROR_UNIT

  ! Symbols imported from other modules within the project.
  USE :: MULTIOM_API, ONLY: JPIB_K
  USE :: MULTIOM_API, ONLY: HOOKS_T
  USE :: MULTIOM_API, ONLY: TOC_CONTAINER_T
  USE :: MULTIOM_API, ONLY: TOC_SIM_INIT_T
  USE :: MULTIOM_API, ONLY: TOC_ATM_FIELD_T
  USE :: MULTIOM_API, ONLY: TOC_WAM_FIELD_T
  USE :: MULTIOM_API, ONLY: TOC_FLUSH_STEP_T
  USE :: MULTIOM_API, ONLY: TOC_FLUSH_STEP_RST_T
  USE :: MULTIOM_API, ONLY: TOC_FLUSH_LAST_STEP_T
  USE :: MULTIOM_API, ONLY: TOC_SIM_END_T
  USE :: MULTIOM_API, ONLY: OUTPUT_MANAGER_BASE_A
  USE :: MULTIOM_API, ONLY: MODEL_PAR_T
  USE :: MULTIOM_API, ONLY: PROC_TOPO_T

  ! Multiom tools utils
  USE :: COMMAND_ARGUMENTS_PARSER_MOD, ONLY: COMMAND_LINE_ARGS_T
  USE :: MULTIOM_TOOLS_UTILS_MOD, ONLY: CHECK_DATA_ENDIANNES
  USE :: MULTIOM_TOOLS_UTILS_MOD, ONLY: INITIALIZE_OUTPUT_MANAGER
  USE :: MULTIOM_TOOLS_UTILS_MOD, ONLY: FINALIZE_OUTPUT_MANAGER
  USE :: MULTIOM_TOOLS_UTILS_MOD, ONLY: ENCODE_HEADER
  USE :: MULTIOM_TOOLS_UTILS_MOD, ONLY: ENCODE_SIMULATION_INIT
  USE :: MULTIOM_TOOLS_UTILS_MOD, ONLY: ENCODE_ATM_MESSAGE
  USE :: MULTIOM_TOOLS_UTILS_MOD, ONLY: ENCODE_WAM_MESSAGE
  USE :: MULTIOM_TOOLS_UTILS_MOD, ONLY: ENCODE_FLUSH
  USE :: MULTIOM_TOOLS_UTILS_MOD, ONLY: ENCODE_FLUSH_AND_RESTART
  USE :: MULTIOM_TOOLS_UTILS_MOD, ONLY: ENCODE_FLUSH_LAST_STEP
  USE :: MULTIOM_TOOLS_UTILS_MOD, ONLY: ENCODE_SIMULATION_END
  USE :: MULTIOM_TOOLS_UTILS_MOD, ONLY: ENCODE_FOOTER

  ! Symbols imported from external libraries
  USE :: MULTIO_API, ONLY: MULTIO_INITIALISE
  USE :: MULTIO_API, ONLY: MULTIO_SUCCESS

IMPLICIT NONE

  ! Local variables
  TYPE(HOOKS_T) :: HOOKS
  TYPE(PROC_TOPO_T) :: TOPOLOGY
  TYPE(MODEL_PAR_T) :: PARAMETERS
  CLASS(OUTPUT_MANAGER_BASE_A), POINTER :: OUTPUT_MANAGER
  TYPE(COMMAND_LINE_ARGS_T) :: CMDARGS
  TYPE(TOC_CONTAINER_T), DIMENSION(:), ALLOCATABLE :: TOC
  INTEGER(KIND=JPIB_K) :: TOCID
  INTEGER(KIND=JPIB_K) :: ERR
  LOGICAL :: VERBOSE
  LOGICAL :: BIG_ENDIAN_READ

  ! Error flags
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_INIT_CMD_LINE = 2_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_GET_VERBOSITY = 3_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_ENCODE_CMD_LINE = 4_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_MAKE_TABLE_OF_CONTENTS = 5_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_ENCODE_HEADER = 6_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_ENCODE_SIMULATION_INIT = 7_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_ENCODE_ATM_MESSAGE = 8_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_ENCODE_WAM_MESSAGE = 9_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_ENCODE_FLUSH = 10_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_ENCODE_FLUSH_AND_RESTART = 11_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_ENCODE_FLUSH_LAST_STEP = 12_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_ENCODE_SIMULATION_END = 13_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNKNOWN_TOC_TYPE = 14_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_ENCODE_FOOTER = 15_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_DESTROY_TABLE_OF_CONTENTS = 16_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_FREE_COMMAND_LINE_OPTIONS = 17_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_INITIALIZE_MULTIO = 18_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_CHECK_ENDIANNES = 19_JPIB_K

  ! Local variables declared by the preprocessor for debugging purposes
  PP_DEBUG_DECL_VARS

  ! Local variables declared by the preprocessor for logging purposes
  PP_LOG_DECL_VARS

  ! Local variables declared by the preprocessor for tracing purposes
  PP_TRACE_DECL_VARS

  ! Trace begin of procedure
  PP_TRACE_ENTER_PROCEDURE()

  ! Initialize the hooks
  CALL HOOKS%DEBUG_HOOK_%INIT( )

  ! Initialize multio
  ERR = MULTIO_INITIALISE()
  PP_DEBUG_CRITICAL_COND_THROW( ERR.NE.MULTIO_SUCCESS, ERRFLAG_UNABLE_TO_INITIALIZE_MULTIO )

  ! Set the default values for the command line options
  PP_TRYCALL(ERRFLAG_UNABLE_TO_INIT_CMD_LINE) CMDARGS%INIT( HOOKS )

  ! Read the verbose flag
  PP_TRYCALL(ERRFLAG_UNABLE_GET_VERBOSITY) CMDARGS%GET_VERBOSE( VERBOSE, HOOKS )

  ! Log the configuration of the tool (main configuration, filters and options)
  IF ( VERBOSE ) THEN
    PP_TRYCALL(ERRFLAG_UNABLE_TO_ENCODE_CMD_LINE) CMDARGS%PRINT( OUTPUT_UNIT, HOOKS )
  ENDIF

  ! Try to get the endianness of the data
  PP_TRYCALL(ERRFLAG_UNABLE_TO_CHECK_ENDIANNES) CHECK_DATA_ENDIANNES( CMDARGS, BIG_ENDIAN_READ, HOOKS )

  ! Construct an output manager
  PP_TRYCALL(ERRFLAG_UNABLE_TO_MAKE_TABLE_OF_CONTENTS) INITIALIZE_OUTPUT_MANAGER( CMDARGS, TOPOLOGY, &
&                                   PARAMETERS, OUTPUT_MANAGER, TOC, BIG_ENDIAN_READ, VERBOSE, HOOKS )

  ! Print the header
  PP_TRYCALL(ERRFLAG_UNABLE_TO_ENCODE_HEADER) ENCODE_HEADER( CMDARGS, OUTPUT_MANAGER, BIG_ENDIAN_READ, VERBOSE, HOOKS )

  ! Loop over the toc entries
  FeederLoop: DO TOCID = 1, SIZE(TOC)

    ! Depending on the TOC type call the appropriate write function
    SELECT TYPE ( TOC_ENTRY => TOC(TOCID)%ENTRY_ )

    CLASS IS ( TOC_SIM_INIT_T )

      PP_TRYCALL(ERRFLAG_UNABLE_TO_ENCODE_SIMULATION_INIT) ENCODE_SIMULATION_INIT( CMDARGS, OUTPUT_MANAGER, TOC_ENTRY, BIG_ENDIAN_READ, VERBOSE, HOOKS )

    CLASS IS ( TOC_ATM_FIELD_T )

      PP_TRYCALL(ERRFLAG_UNABLE_TO_ENCODE_ATM_MESSAGE) ENCODE_ATM_MESSAGE( CMDARGS, OUTPUT_MANAGER, TOC_ENTRY, BIG_ENDIAN_READ, VERBOSE, HOOKS )

    CLASS IS ( TOC_WAM_FIELD_T )

      PP_TRYCALL(ERRFLAG_UNABLE_TO_ENCODE_WAM_MESSAGE) ENCODE_WAM_MESSAGE( CMDARGS, OUTPUT_MANAGER, TOC_ENTRY, BIG_ENDIAN_READ, VERBOSE, HOOKS )

    CLASS IS ( TOC_FLUSH_STEP_T )

      PP_TRYCALL(ERRFLAG_UNABLE_TO_ENCODE_FLUSH) ENCODE_FLUSH( CMDARGS, OUTPUT_MANAGER, TOC_ENTRY, BIG_ENDIAN_READ, VERBOSE, HOOKS )

    CLASS IS ( TOC_FLUSH_STEP_RST_T )

      PP_TRYCALL(ERRFLAG_UNABLE_TO_ENCODE_FLUSH_AND_RESTART) ENCODE_FLUSH_AND_RESTART( CMDARGS, OUTPUT_MANAGER, TOC_ENTRY, BIG_ENDIAN_READ, VERBOSE, HOOKS )

    CLASS IS ( TOC_FLUSH_LAST_STEP_T )

      PP_TRYCALL(ERRFLAG_UNABLE_TO_ENCODE_FLUSH_LAST_STEP) ENCODE_FLUSH_LAST_STEP( CMDARGS, OUTPUT_MANAGER, TOC_ENTRY, BIG_ENDIAN_READ, VERBOSE, HOOKS )

    CLASS IS ( TOC_SIM_END_T )

      PP_TRYCALL(ERRFLAG_UNABLE_TO_ENCODE_SIMULATION_END) ENCODE_SIMULATION_END( CMDARGS, OUTPUT_MANAGER, TOC_ENTRY, BIG_ENDIAN_READ, VERBOSE, HOOKS )
      EXIT FeederLoop

    CLASS DEFAULT
      PP_DEBUG_CRITICAL_THROW( ERRFLAG_UNKNOWN_TOC_TYPE )

    END SELECT

  ENDDO FeederLoop

  ! Print the footer
  PP_TRYCALL(ERRFLAG_UNABLE_TO_ENCODE_HEADER) ENCODE_FOOTER( CMDARGS, OUTPUT_MANAGER, BIG_ENDIAN_READ, VERBOSE, HOOKS )

  ! Finalize output manager
  PP_TRYCALL(ERRFLAG_UNABLE_TO_DESTROY_TABLE_OF_CONTENTS) FINALIZE_OUTPUT_MANAGER( CMDARGS, OUTPUT_MANAGER, TOC, BIG_ENDIAN_READ, VERBOSE, HOOKS )

  ! Free memory
  PP_TRYCALL(ERRFLAG_UNABLE_TO_FREE_COMMAND_LINE_OPTIONS) CMDARGS%FREE( HOOKS )

  !> Be sure we don't have any memory leaks
  CALL HOOKS%DEBUG_HOOK_%FREE( )

  !> Exit point (on success)
  STOP 0

! Error handler
PP_ERROR_HANDLER

#if defined( PP_DEBUG_ENABLE_ERROR_HANDLING )
!$omp critical(ERROR_HANDLER)

  BLOCK

    ! Error handling variables
    PP_DEBUG_PUSH_FRAME()

    SELECT CASE(ERRIDX)
    CASE (ERRFLAG_UNABLE_TO_INIT_CMD_LINE)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Error initializing the command line options' )
    CASE (ERRFLAG_UNABLE_GET_VERBOSITY)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Error getting the verbosity flag' )
    CASE (ERRFLAG_UNABLE_TO_ENCODE_CMD_LINE)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Error printing the command line options' )
    CASE (ERRFLAG_UNABLE_TO_MAKE_TABLE_OF_CONTENTS)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Error creating the table of contents' )
    CASE (ERRFLAG_UNABLE_TO_ENCODE_HEADER)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Error writing the header' )
    CASE (ERRFLAG_UNABLE_TO_ENCODE_SIMULATION_INIT)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Error writing the simulation init message' )
    CASE (ERRFLAG_UNABLE_TO_ENCODE_ATM_MESSAGE)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Error writing the atm message' )
    CASE (ERRFLAG_UNABLE_TO_ENCODE_WAM_MESSAGE)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Error writing the wam message' )
    CASE (ERRFLAG_UNABLE_TO_ENCODE_FLUSH)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Error writing the flush message' )
    CASE (ERRFLAG_UNABLE_TO_ENCODE_FLUSH_AND_RESTART)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Error writing the flush and restart message' )
    CASE (ERRFLAG_UNABLE_TO_ENCODE_FLUSH_LAST_STEP)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Error writing the flush last step message' )
    CASE (ERRFLAG_UNABLE_TO_ENCODE_SIMULATION_END)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Error writing the simulation end message' )
    CASE (ERRFLAG_UNKNOWN_TOC_TYPE)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Unknown table of contents type' )
    CASE (ERRFLAG_UNABLE_TO_ENCODE_FOOTER)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Error writing the footer' )
    CASE (ERRFLAG_UNABLE_TO_DESTROY_TABLE_OF_CONTENTS)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Error destroying the output manager' )
    CASE (ERRFLAG_UNABLE_TO_FREE_COMMAND_LINE_OPTIONS)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Error freeing the command line options' )
    CASE (ERRFLAG_UNABLE_TO_INITIALIZE_MULTIO)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Error initializing multio' )
    CASE (ERRFLAG_UNABLE_TO_CHECK_ENDIANNES)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Error checking the endianness of the data' )
    CASE DEFAULT
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Unknown error' )
    END SELECT

    ! Print the error stack
    CALL HOOKS%DEBUG_HOOK_%PRINT_ERROR_STACK( ERROR_UNIT )

    ! Free the error stack
    CALL HOOKS%DEBUG_HOOK_%FREE( )

    ! Write the error message and stop the program
    PP_DEBUG_ABORT

  END BLOCK

!$omp end critical(ERROR_HANDLER)
#endif

  ! Exit point (on error)
  STOP 1


END PROGRAM MULTIOM_FEED_PROG
#undef PP_FILE_NAME
#undef PP_SECTION_TYPE
#undef PP_SECTION_NAME
#undef PP_PROCEDURE_TYPE
#undef PP_PROCEDURE_NAME
