from enum import IntEnum, unique

from .lib import lib


@unique
class DataType(IntEnum):
    SUCCESS = lib.MULTIO_SUCCESS
    ERROR_ECKIT_EXCEPTION = lib.MULTIO_ERROR_ECKIT_EXCEPTION
    ERROR_GENERAL_EXCEPTION = lib.MULTIO_ERROR_GENERAL_EXCEPTION
    ERROR_UNKNOWN_EXCEPTION = lib.MULTIO_ERROR_UNKNOWN_EXCEPTION


SUCCESS = DataType.SUCCESS
ERROR_ECKIT_EXCEPTION = DataType.ERROR_ECKIT_EXCEPTION
ERROR_GENERAL_EXCEPTION = DataType.ERROR_GENERAL_EXCEPTION
ERROR_UNKNOWN_EXCEPTION = DataType.ERROR_UNKNOWN_EXCEPTION
