MODULE OM_TRACE_MOD

  ! Symbolds imported from intrinsic modules
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: ERROR_UNIT

  ! Symbols imported from other modules within the project.
  USE :: OM_DATA_KIND_MOD, ONLY: JPTR_K

IMPLICIT NONE

! Default visibility
PRIVATE

TYPE :: TRACER_T
  REAL(KIND=JPTR_K) :: ZHOOK_HANDLE_
END TYPE

INTERFACE
  SUBROUTINE DR_HOOK_DEFAULT8_IF(CDNAME,KSWITCH,PKEY)
    USE :: OM_DATA_KIND_MOD, ONLY: JPIM_K
    USE :: OM_DATA_KIND_MOD, ONLY: JPTR_K
  IMPLICIT NONE
    CHARACTER(LEN=*),     INTENT(IN)    :: CDNAME
    INTEGER(KIND=JPIM_K), INTENT(IN)    :: KSWITCH
    REAL(KIND=JPTR_K),    INTENT(INOUT) :: PKEY
  END SUBROUTINE DR_HOOK_DEFAULT8_IF
END INTERFACE

PROCEDURE(DR_HOOK_DEFAULT8_IF), POINTER :: DR_HOOK => NULL()
LOGICAL :: LHOOK_ = .FALSE.


! Whitelist of public symbols (types)
PUBLIC :: TRACER_T

! Whitelist of public symbols (procedures)
PUBLIC :: OM_TRACE_ENTER_PROCEDURE
PUBLIC :: OM_TRACE_EXIT_PROCEDURE_ON_SUCCESS
PUBLIC :: OM_TRACE_EXIT_PROCEDURE_ON_ERROR
PUBLIC :: OM_SET_DR_HOOK

CONTAINS



SUBROUTINE OM_SET_DR_HOOK( LHOOK, DR_HOOK_PROCEDURE )
IMPLICIT NONE

LOGICAL,            INTENT(IN) :: LHOOK
PROCEDURE(DR_HOOK_DEFAULT8_IF) :: DR_HOOK_PROCEDURE

LHOOK_  = LHOOK
DR_HOOK => DR_HOOK_PROCEDURE

END SUBROUTINE OM_SET_DR_HOOK




SUBROUTINE OM_TRACE_ENTER_PROCEDURE( TRACER, FNAME, SECTION_TYPE, SECTION_NAME, PROC_TYPE, PROC_NAME, LINE )

  ! Symbols imported from other modules within the project.
  USE :: OM_DATA_KIND_MOD, ONLY: JPIB_K

IMPLICIT NONE

  ! Dummy arguments
  TYPE(TRACER_T),                INTENT(INOUT) :: TRACER
  CHARACTER(LEN=*),              INTENT(IN)    :: FNAME
  CHARACTER(LEN=*),              INTENT(IN)    :: SECTION_TYPE
  CHARACTER(LEN=*),              INTENT(IN)    :: SECTION_NAME
  CHARACTER(LEN=*),              INTENT(IN)    :: PROC_TYPE
  CHARACTER(LEN=*),              INTENT(IN)    :: PROC_NAME
  INTEGER(KIND=JPIB_K),          INTENT(IN)    :: LINE

  IF ( ASSOCIATED(DR_HOOK) .AND. LHOOK_ ) THEN
    CALL DR_HOOK( TRIM(SECTION_NAME)//'::'//TRIM(PROC_NAME), 0, TRACER%ZHOOK_HANDLE_ )
  ENDIF

  RETURN

END SUBROUTINE OM_TRACE_ENTER_PROCEDURE



SUBROUTINE OM_TRACE_EXIT_PROCEDURE_ON_SUCCESS( TRACER, FNAME, SECTION_TYPE, SECTION_NAME, PROC_TYPE, PROC_NAME, LINE )

  ! Symbols imported from other modules within the project.
  USE :: OM_DATA_KIND_MOD, ONLY: JPIB_K

IMPLICIT NONE

  ! Dummy arguments
  TYPE(TRACER_T),                INTENT(INOUT) :: TRACER
  CHARACTER(LEN=*),              INTENT(IN)    :: FNAME
  CHARACTER(LEN=*),              INTENT(IN)    :: SECTION_TYPE
  CHARACTER(LEN=*),              INTENT(IN)    :: SECTION_NAME
  CHARACTER(LEN=*),              INTENT(IN)    :: PROC_TYPE
  CHARACTER(LEN=*),              INTENT(IN)    :: PROC_NAME
  INTEGER(KIND=JPIB_K),          INTENT(IN)    :: LINE


  IF ( ASSOCIATED(DR_HOOK) .AND. LHOOK_ ) THEN
    CALL DR_HOOK( TRIM(SECTION_NAME)//'::'//TRIM(PROC_NAME), 1, TRACER%ZHOOK_HANDLE_ )
  ENDIF

  RETURN

END SUBROUTINE OM_TRACE_EXIT_PROCEDURE_ON_SUCCESS



SUBROUTINE OM_TRACE_EXIT_PROCEDURE_ON_ERROR( TRACER, FNAME, SECTION_TYPE, SECTION_NAME, PROC_TYPE, PROC_NAME, LINE )

  ! Symbols imported from other modules within the project.
  USE :: OM_DATA_KIND_MOD, ONLY: JPIB_K

IMPLICIT NONE

  ! Dummy arguments
  TYPE(TRACER_T),                INTENT(INOUT) :: TRACER
  CHARACTER(LEN=*),              INTENT(IN)    :: FNAME
  CHARACTER(LEN=*),              INTENT(IN)    :: SECTION_TYPE
  CHARACTER(LEN=*),              INTENT(IN)    :: SECTION_NAME
  CHARACTER(LEN=*),              INTENT(IN)    :: PROC_TYPE
  CHARACTER(LEN=*),              INTENT(IN)    :: PROC_NAME
  INTEGER(KIND=JPIB_K),          INTENT(IN)    :: LINE



  RETURN

END SUBROUTINE OM_TRACE_EXIT_PROCEDURE_ON_ERROR



END MODULE OM_TRACE_MOD