! Include preprocessor utils
#include "output_manager_preprocessor_utils.h"
#include "output_manager_preprocessor_trace_utils.h"
#include "output_manager_preprocessor_logging_utils.h"
#include "output_manager_preprocessor_errhdl_utils.h"


#define PP_FILE_NAME 'multiom_api.F90'
#define PP_SECTION_TYPE 'MODULE'
#define PP_SECTION_NAME 'MULTIOM_API'
MODULE MULTIOM_API

  ! Include the error handler
  USE :: HOOKS_MOD, ONLY: HOOKS_T
  USE :: TRACE_MOD, ONLY: OM_SET_DR_HOOK

  ! Datatypes
  USE :: DATAKINDS_DEF_MOD, ONLY: JPIB_K
  USE :: DATAKINDS_DEF_MOD, ONLY: JPIM_K
  USE :: DATAKINDS_DEF_MOD, ONLY: JPTR_K
  USE :: DATAKINDS_DEF_MOD, ONLY: JPRM_K
  USE :: DATAKINDS_DEF_MOD, ONLY: JPRD_K

  ! Enumerators
  USE :: ENUMERATORS_MOD, ONLY: IPREFIX2ILEVTYPE
  USE :: ENUMERATORS_MOD, ONLY: ILEVTYPE2CLEVTYPE
  USE :: ENUMERATORS_MOD, ONLY: IREPRES2CREPRES
  USE :: ENUMERATORS_MOD, ONLY: VALUES_SP_E
  USE :: ENUMERATORS_MOD, ONLY: VALUES_DP_E

  ! ifs interface
  USE :: IFS_MSG_MOD, ONLY: OM_ATM_MSG_T
  USE :: IFS_MSG_MOD, ONLY: OM_WAM_MSG_T
  USE :: IFS_MSG_MOD, ONLY: MSG_PRINT_ATM
  USE :: IFS_MSG_MOD, ONLY: MSG_PRINT_WAM
  USE :: IFS_MSG_MOD, ONLY: MSG_CREATE_NAME
  USE :: IFS_MSG_MOD, ONLY: MSG_ROPEN
  USE :: IFS_MSG_MOD, ONLY: MSG_READ_ATM
  USE :: IFS_MSG_MOD, ONLY: MSG_READ_WAM
  USE :: IFS_MSG_MOD, ONLY: MSG_CLOSE
  USE :: IFS_PAR_MOD, ONLY: PROC_TOPO_T
  USE :: IFS_PAR_MOD, ONLY: MODEL_PAR_T
  USE :: IFS_PAR_MOD, ONLY: PAR_CREATE_NAME
  USE :: IFS_PAR_MOD, ONLY: PAR_ROPEN
  USE :: IFS_PAR_MOD, ONLY: PAR_READ
  USE :: IFS_PAR_MOD, ONLY: PAR_CLOSE
  USE :: IFS_VAL_MOD, ONLY: VAL_CREATE_NAME
  USE :: IFS_VAL_MOD, ONLY: VAL_ROPEN
  USE :: IFS_VAL_MOD, ONLY: VAL_READ_SP
  USE :: IFS_VAL_MOD, ONLY: VAL_GENERATE_SP
  USE :: IFS_VAL_MOD, ONLY: VAL_READ_DP
  USE :: IFS_VAL_MOD, ONLY: VAL_GENERATE_DP
  USE :: IFS_VAL_MOD, ONLY: VAL_CLOSE
  USE :: IFS_TOC_MOD, ONLY: TOC_CONTAINER_T
  USE :: IFS_TOC_MOD, ONLY: TOC_CREATE_NAME
  USE :: IFS_TOC_MOD, ONLY: TOC_ENTRY_BASE_T
  USE :: IFS_TOC_MOD, ONLY: TOC_SIM_INIT_T
  USE :: IFS_TOC_MOD, ONLY: TOC_ATM_FIELD_T
  USE :: IFS_TOC_MOD, ONLY: TOC_WAM_FIELD_T
  USE :: IFS_TOC_MOD, ONLY: TOC_FLUSH_STEP_T
  USE :: IFS_TOC_MOD, ONLY: TOC_FLUSH_STEP_RST_T
  USE :: IFS_TOC_MOD, ONLY: TOC_FLUSH_LAST_STEP_T
  USE :: IFS_TOC_MOD, ONLY: TOC_SIM_END_T
  USE :: IFS_TOC_MOD, ONLY: TOC_READ_ALL
  USE :: IFS_TOC_MOD, ONLY: TOC_READ
  USE :: IFS_TOC_MOD, ONLY: TOC_FREE

  ! Output manager management
  USE :: OUTPUT_MANAGER_FACTORY_MOD, ONLY: OUTPUT_MANAGER_BASE_A
  USE :: OUTPUT_MANAGER_FACTORY_MOD, ONLY: MAKE_OUTPUT_MANAGER
  USE :: OUTPUT_MANAGER_FACTORY_MOD, ONLY: DESTROY_OUTPUT_MANAGER

IMPLICIT NONE

! Default visibility
PRIVATE

! Whitelist of public symbols

! Include the error handler
PUBLIC :: HOOKS_T
PUBLIC :: OM_SET_DR_HOOK

! Datatypes
PUBLIC :: JPIB_K
PUBLIC :: JPIM_K
PUBLIC :: JPTR_K
PUBLIC :: JPRM_K
PUBLIC :: JPRD_K

! Enumerators
PUBLIC :: IPREFIX2ILEVTYPE
PUBLIC :: ILEVTYPE2CLEVTYPE
PUBLIC :: IREPRES2CREPRES
PUBLIC :: VALUES_SP_E
PUBLIC :: VALUES_DP_E

! ifs interface
PUBLIC :: OM_ATM_MSG_T
PUBLIC :: OM_WAM_MSG_T
PUBLIC :: MSG_PRINT_ATM
PUBLIC :: MSG_PRINT_WAM
PUBLIC :: MSG_CREATE_NAME
PUBLIC :: MSG_ROPEN
PUBLIC :: MSG_READ_ATM
PUBLIC :: MSG_READ_WAM
PUBLIC :: MSG_CLOSE
PUBLIC :: PROC_TOPO_T
PUBLIC :: MODEL_PAR_T
PUBLIC :: PAR_CREATE_NAME
PUBLIC :: PAR_ROPEN
PUBLIC :: PAR_READ
PUBLIC :: PAR_CLOSE
PUBLIC :: VAL_CREATE_NAME
PUBLIC :: VAL_ROPEN
PUBLIC :: VAL_READ_SP
PUBLIC :: VAL_GENERATE_SP
PUBLIC :: VAL_READ_DP
PUBLIC :: VAL_GENERATE_DP
PUBLIC :: VAL_CLOSE
PUBLIC :: TOC_CONTAINER_T
PUBLIC :: TOC_CREATE_NAME
PUBLIC :: TOC_ENTRY_BASE_T
PUBLIC :: TOC_SIM_INIT_T
PUBLIC :: TOC_ATM_FIELD_T
PUBLIC :: TOC_WAM_FIELD_T
PUBLIC :: TOC_FLUSH_STEP_T
PUBLIC :: TOC_FLUSH_STEP_RST_T
PUBLIC :: TOC_FLUSH_LAST_STEP_T
PUBLIC :: TOC_SIM_END_T
PUBLIC :: TOC_READ_ALL
PUBLIC :: TOC_READ
PUBLIC :: TOC_FREE

! Output manager management
PUBLIC :: OUTPUT_MANAGER_BASE_A
PUBLIC :: MAKE_OUTPUT_MANAGER
PUBLIC :: DESTROY_OUTPUT_MANAGER

END MODULE MULTIOM_API
#undef PP_SECTION_NAME
#undef PP_SECTION_TYPE
#undef PP_FILE_NAME
