! Include preprocessor utils
#include "output_manager_preprocessor_utils.h"
#include "output_manager_preprocessor_trace_utils.h"
#include "output_manager_preprocessor_logging_utils.h"
#include "output_manager_preprocessor_errhdl_utils.h"


#define PP_FILE_NAME 'cached_mapped_encoder_wrapper_mod.F90'
#define PP_SECTION_TYPE 'MODULE'
#define PP_SECTION_NAME 'CACHED_MAPPED_ENCODER_WRAPPER_MOD'
MODULE CACHED_MAPPED_ENCODER_WRAPPER_MOD

  ! Symbols imported from other modules within the project.
  USE :: DATAKINDS_DEF_MOD, ONLY: JPIB_K

  ! Symbols imported from other modules within the project.
  USE :: MULTIOM_CACHED_ENCODER_MOD, ONLY: MULTIOM_CACHED_ENCODERS_T

IMPLICIT NONE

  !> Encoder index used used to identify the encoder wrapper
  INTEGER(KIND=JPIB_K), PARAMETER :: CACHED_MAPPED_ENCODER_IDX_E = 1_JPIB_K
  CHARACTER(LEN=*), PARAMETER :: CACHED_MAPPED_ENCODER_NAME_E = 'cached-mapped-encoder'

  !> Class used as a wrapper for the encoder
  TYPE :: CACHED_ENCODER_CONTAINER_T
    TYPE(MULTIOM_CACHED_ENCODERS_T), POINTER :: ENCODER => NULL()
  END TYPE

  !> Whitelist of public symbols
  PUBLIC :: CACHED_MAPPED_ENCODER_IDX_E
  PUBLIC :: CACHED_MAPPED_ENCODER_NAME_E
  PUBLIC :: CREATE_CACHED_MAPPED_ENCODER
  PUBLIC :: INIT_CACHED_MAPPED_ENCODER
  PUBLIC :: EXTRACT_CACHED_MAPPED_ENCODER
  PUBLIC :: FREE_CACHED_MAPPED_ENCODER

CONTAINS


#define PP_PROCEDURE_TYPE 'FUNCTION'
#define PP_PROCEDURE_NAME 'ENCODE_CACHED_MAPPED_ENCODER'
PP_THREAD_SAFE FUNCTION ENCODE_CACHED_MAPPED_ENCODER( WRAPPED_ENCODER, F_MARS_DICT, F_PAR_DICT, HOOKS ) RESULT(RET)

  !> Symbols imported from intrinsic modules.
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_PTR
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_ASSOCIATED

  ! Symbols imported from other modules within the project.
  USE :: DATAKINDS_DEF_MOD,          ONLY: JPIB_K
  USE :: HOOKS_MOD,                  ONLY: HOOKS_T
  USE :: MULTIOM_CACHED_ENCODER_MOD, ONLY: MULTIOM_CACHED_ENCODERS_T
  USE :: FORTRAN_MESSAGE_MOD,        ONLY: FORTRAN_MESSAGE_T
  USE :: PARAMETRIZATION_MOD,        ONLY: PARAMETRIZATION_T
  USE :: METADATA_LIST_MOD,          ONLY: METADATA_LIST_T


  ! Symbols imported by the preprocessor for debugging purposes
  PP_DEBUG_USE_VARS

  ! Symbols imported by the preprocessor for logging purposes
  PP_LOG_USE_VARS

  ! Symbols imported by the preprocessor for tracing purposes
  PP_TRACE_USE_VARS

IMPLICIT NONE

  !> Dummy arguments
  TYPE(C_PTR),             INTENT(INOUT) :: WRAPPED_ENCODER
  TYPE(FORTRAN_MESSAGE_T), INTENT(IN)    :: F_MARS_DICT
  TYPE(PARAMETRIZATION_T), INTENT(IN)    :: F_PAR_DICT
  TYPE(HOOKS_T),           INTENT(INOUT) :: HOOKS

  ! Function result
  INTEGER(KIND=JPIB_K) :: RET

  ! Local variables
  TYPE(MULTIOM_CACHED_ENCODERS_T), POINTER :: CACHED_MAPPED_ENCODER
  TYPE(METADATA_LIST_T)                    :: METADATA_LIST

  ! Local error flags
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_EXTRACT_ENCODER=1_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_CALL_THE_ENCODER=2_JPIB_K

  ! Local variables declared by the preprocessor for debugging purposes
  PP_DEBUG_DECL_VARS

  ! Local variables declared by the preprocessor for logging purposes
  PP_LOG_DECL_VARS

  ! Local variables declared by the preprocessor for tracing purposes
  PP_TRACE_DECL_VARS

  ! Trace begin of procedure
  PP_TRACE_ENTER_PROCEDURE()

  ! Initialization of good path return value
  PP_SET_ERR_SUCCESS( RET )

  ! Extract the encoder
  PP_TRYCALL(ERRFLAG_EXTRACT_ENCODER) EXTRACT_CACHED_MAPPED_ENCODER( WRAPPED_ENCODER, CACHED_MAPPED_ENCODER, HOOKS )
  PP_DEBUG_CRITICAL_COND_THROW( .NOT.ASSOCIATED(CACHED_MAPPED_ENCODER), ERRFLAG_EXTRACT_ENCODER )

  ! Call the encoder
  PP_TRYCALL(ERRFLAG_CALL_THE_ENCODER) CACHED_MAPPED_ENCODER%ENCODE(  F_MARS_DICT, F_PAR_DICT, METADATA_LIST, HOOKS )

#if 0
  !> Loop over the encoding rules
  PP_TRYCALL(ERRFLAG_UNABLE_CHECK_LIST) METADATA_LIST%SIZE( MD_SIZE, HOOKS )
  PP_DEBUG_CRITICAL_COND_THROW( MD_SIZE .NE. 1_JPIM_K, ERRFLAG_WRONG_DATA_LEN )

  !> Get the encoding rule
  PP_TRYCALL(ERRFLAG_UNABLE_TO_POP_FROM_LIST) METADATA_LIST%POP( OUT_MSG, OUT_PAR, &
&       MAPPING_TAG, MAPPING_NAME, ENCODER_TAG, ENCODER_NAME, MD, HOOKS )

  ! Get the metadata

  SELECT TYPE(A => MD)

  CLASS IS (GRIB_METADATA_T)

    HANDLE=0_JPIB_K

    PP_TRYCALL(ERRFLAG_UNABLE_TO_GET_HANDLE) A%GET_HANDLE( HANDLE, HOOKS )

    PP_TRYCALL(ERRFLAG_GET_GRIB_MESSAGE) GET_GRIB_MESSAGE(BUFFER, HANDLE, DATA_LENGTH, HOOKS )

    ! PP_TRYCALL(ERRFLAG_GRIB_MESSAGE_TO_C) CONVERT_TO_C_STRING(BUFFER, C_CODES_HANDLE_LOC, HOOKS)
    PP_TRYCALL(ERRFLAG_GRIB_MESSAGE_TO_C) COPY_F_BUFFER_TO_C_BUFFER(BUFFER, C_CODES_HANDLE_LOC, HOOKS)

    C_MESSAGE_LEN=INT(SIZE(BUFFER), KIND=C_INT)

    ! PP_TRYCALL(ERRFLAG_GRIB_MESSAGE_TO_C) GRIB_MESSAGE_TO_C_CODES_HANDLE(BUFFER, C_CODES_HANDLE_LOC, HOOKS )

    DEALLOCATE(BUFFER, STAT=STAT)
    PP_DEBUG_DEVELOP_COND_THROW(STAT.NE.0, ERRFLAG_UNABLE_TO_DEALLOCATE_BUFFER)

  CLASS DEFAULT
    PP_DEBUG_CRITICAL_THROW( ERRFLAG_METADATA_NOT_SUPPORTED )
  END SELECT

  !> Free the encoded metadata
  PP_TRYCALL(ERRFLAG_UNABLE_DEALLOCATE_METADATA) DESTROY_METADATA( MD, HOOKS )

  !> Free the message/parametrization
  PP_TRYCALL(ERRFLAG_UNABLE_TO_FREE_MSG) OUT_MSG%FREE( HOOKS )
  PP_TRYCALL(ERRFLAG_UNABLE_TO_FREE_PAR) OUT_PAR%FREE( HOOKS )
#endif

  ! Trace end of procedure (on success)
  PP_TRACE_EXIT_PROCEDURE_ON_SUCCESS()

  ! Exit point (On success)
  RETURN

! Error handler
PP_ERROR_HANDLER

  ! Initialization of bad path return value
  PP_SET_ERR_FAILURE( RET )

#if defined( PP_DEBUG_ENABLE_ERROR_HANDLING )
!$omp critical(ERROR_HANDLER)

  BLOCK

    ! Error handling variables
    PP_DEBUG_PUSH_FRAME()

    ! Handle different errors
    SELECT CASE(ERRIDX)
    CASE (ERRFLAG_EXTRACT_ENCODER)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Unable to extract encoder' )
    CASE (ERRFLAG_CALL_THE_ENCODER)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Unable to call the encoder' )
    CASE DEFAULT
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'unhandled error' )
    END SELECT

    ! Trace end of procedure (on error)
    PP_TRACE_EXIT_PROCEDURE_ON_ERROR()

    ! Write the error message and stop the program
    PP_DEBUG_ABORT

  END BLOCK

!$omp end critical(ERROR_HANDLER)
#endif

  ! Exit point (on error)
  RETURN

END FUNCTION ENCODE_CACHED_MAPPED_ENCODER
#undef PP_PROCEDURE_NAME
#undef PP_PROCEDURE_TYPE



#define PP_PROCEDURE_TYPE 'FUNCTION'
#define PP_PROCEDURE_NAME 'INIT_CACHED_MAPPED_ENCODER'
PP_THREAD_SAFE FUNCTION INIT_CACHED_MAPPED_ENCODER( WRAPPED_ENCODER, OPTIONS, HOOKS ) RESULT(RET)

  !> Symbols imported from intrinsic modules.
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_PTR
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_ASSOCIATED

  ! Symbols imported from other modules within the project.
  USE :: DATAKINDS_DEF_MOD,                ONLY: JPIB_K
  USE :: HOOKS_MOD,                        ONLY: HOOKS_T
  USE :: API_OPTIONS_DICTIONARY_UTILS_MOD, ONLY: API_OPTIONS_T
  USE :: MULTIOM_CACHED_ENCODER_MOD,       ONLY: MULTIOM_CACHED_ENCODERS_T
  USE :: API_F_C_WRAPPER_MOD,              ONLY: F_C_WRAPPER_T
  USE :: API_F_C_WRAPPER_MOD,              ONLY: F_C_ALLOCATE_WRAPPER

  USE :: MULTIOM_CACHED_ENCODER_MOD, ONLY: MULTIOM_CACHED_ENCODERS_T
  USE :: METADATA_BASE_MOD,          ONLY: METADATA_BASE_A
  USE :: METADATA_FACTORY_MOD,       ONLY: MAKE_METADATA
  USE :: FILTER_OPTIONS_MOD,         ONLY: FILTER_OPTIONS_T
  USE :: GRIB_ENCODER_OPTIONS_MOD,   ONLY: GRIB_ENCODER_OPTIONS_T
  USE :: MAPPING_OPTIONS_MOD,        ONLY: MAPPING_OPTIONS_T
  USE :: CACHE_UTILS_MOD,            ONLY: CACHE_OPTIONS_T

  ! Symbols imported by the preprocessor for debugging purposes
  PP_DEBUG_USE_VARS

  ! Symbols imported by the preprocessor for logging purposes
  PP_LOG_USE_VARS

  ! Symbols imported by the preprocessor for tracing purposes
  PP_TRACE_USE_VARS

IMPLICIT NONE

  !> Dummy arguments
  TYPE(C_PTR),         INTENT(INOUT) :: WRAPPED_ENCODER
  TYPE(API_OPTIONS_T), INTENT(IN)    :: OPTIONS
  TYPE(HOOKS_T),       INTENT(INOUT) :: HOOKS

  ! Function result
  INTEGER(KIND=JPIB_K) :: RET

 ! Options
  TYPE(MULTIOM_CACHED_ENCODERS_T), POINTER :: CACHED_MAPPED_ENCODER
  CLASS(METADATA_BASE_A), POINTER :: METADATA

  TYPE(CACHE_OPTIONS_T)           :: CACHE_OPTIONS
  TYPE(GRIB_ENCODER_OPTIONS_T)    :: ENCODER_OPTIONS
  TYPE(MAPPING_OPTIONS_T)         :: MAPPING_OPTIONS
  TYPE(FILTER_OPTIONS_T)          :: FILTER_OPTIONS

  ! Local error flags
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_WRAPPER_ALREADY_ASSOCIATED=1_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_ENCODER_NOT_ASSOCIATED=2_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_METADATA_NOT_ASSOCIATED=3_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_EXTRACT_ENCODER=4_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_LOADING_LOCAL_SAMPLE=5_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_INITIALIZE_ENCODER=6_JPIB_K

  ! Local variables declared by the preprocessor for debugging purposes
  PP_DEBUG_DECL_VARS

  ! Local variables declared by the preprocessor for logging purposes
  PP_LOG_DECL_VARS

  ! Local variables declared by the preprocessor for tracing purposes
  PP_TRACE_DECL_VARS

  ! Trace begin of procedure
  PP_TRACE_ENTER_PROCEDURE()

  ! Initialization of good path return value
  PP_SET_ERR_SUCCESS( RET )

  ! Error handling
  PP_DEBUG_CRITICAL_COND_THROW( C_ASSOCIATED(WRAPPED_ENCODER), ERRFLAG_WRAPPER_ALREADY_ASSOCIATED )

  !> Initialize the encoder
  CACHED_MAPPED_ENCODER => NULL()
  METADATA => NULL()

  !> Create the encoder
  PP_TRYCALL(ERRFLAG_UNABLE_TO_EXTRACT_ENCODER) CREATE_CACHED_MAPPED_ENCODER( &
&       WRAPPED_ENCODER, CACHED_MAPPED_ENCODER, HOOKS )
  PP_DEBUG_CRITICAL_COND_THROW( .NOT.ASSOCIATED(CACHED_MAPPED_ENCODER), ERRFLAG_ENCODER_NOT_ASSOCIATED )

  ! Create the reference metadata to be used in the encoder
  PP_TRYCALL( ERRFLAG_LOADING_LOCAL_SAMPLE ) MAKE_METADATA( METADATA, 'grib', OPTIONS%SAMPLE_FNAME, HOOKS )
  PP_DEBUG_CRITICAL_COND_THROW( .NOT.ASSOCIATED(METADATA), ERRFLAG_METADATA_NOT_ASSOCIATED )

  !> Initialize the encoder
   PP_TRYCALL(ERRFLAG_INITIALIZE_ENCODER) CACHED_MAPPED_ENCODER%INIT(&
&       OPTIONS%MAPPING_RULES_FNAME, OPTIONS%ENCODING_RULES_FNAME, METADATA, &
&       CACHE_OPTIONS, ENCODER_OPTIONS, MAPPING_OPTIONS, FILTER_OPTIONS, &
&       HOOKS )

  ! Trace end of procedure (on success)
  PP_TRACE_EXIT_PROCEDURE_ON_SUCCESS()

  ! Exit point (On success)
  RETURN

! Error handler
PP_ERROR_HANDLER

  ! Initialization of bad path return value
  PP_SET_ERR_FAILURE( RET )

#if defined( PP_DEBUG_ENABLE_ERROR_HANDLING )
!$omp critical(ERROR_HANDLER)

  BLOCK

    ! Error handling variables
    PP_DEBUG_PUSH_FRAME()

    ! Handle different errors
    SELECT CASE(ERRIDX)
    CASE (ERRFLAG_WRAPPER_ALREADY_ASSOCIATED)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Encoder already associated at function entry' )
    CASE (ERRFLAG_ENCODER_NOT_ASSOCIATED)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Encoder not associated after allocation' )
    CASE (ERRFLAG_METADATA_NOT_ASSOCIATED)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Metadata not associated after allocation' )
    CASE (ERRFLAG_UNABLE_TO_EXTRACT_ENCODER)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Unable to extract encoder' )
    CASE (ERRFLAG_LOADING_LOCAL_SAMPLE)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Unable to load local sample' )
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Sample path: "'//TRIM(ADJUSTL(OPTIONS%SAMPLES_PATH))//'"' )
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Sample name: "'//TRIM(ADJUSTL(OPTIONS%SAMPLE_FNAME))//'"' )
    CASE (ERRFLAG_INITIALIZE_ENCODER)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Unable to initialize encoder' )
    CASE DEFAULT
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'unhandled error' )
    END SELECT

    ! Trace end of procedure (on error)
    PP_TRACE_EXIT_PROCEDURE_ON_ERROR()

    ! Write the error message and stop the program
    PP_DEBUG_ABORT

  END BLOCK

!$omp end critical(ERROR_HANDLER)
#endif

  ! Exit point (on error)
  RETURN

END FUNCTION INIT_CACHED_MAPPED_ENCODER
#undef PP_PROCEDURE_NAME
#undef PP_PROCEDURE_TYPE


#define PP_PROCEDURE_TYPE 'FUNCTION'
#define PP_PROCEDURE_NAME 'CREATE_CACHED_MAPPED_ENCODER'
PP_THREAD_SAFE FUNCTION CREATE_CACHED_MAPPED_ENCODER( WRAPPED_ENCODER, ENCODER, HOOKS ) RESULT(RET)

  !> Symbols imported from intrinsic modules.
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_PTR
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_INT8_T
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_ASSOCIATED
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_LOC

  ! Symbols imported from other modules within the project.
  USE :: DATAKINDS_DEF_MOD,          ONLY: JPIB_K
  USE :: HOOKS_MOD,                  ONLY: HOOKS_T
  USE :: MULTIOM_CACHED_ENCODER_MOD, ONLY: MULTIOM_CACHED_ENCODERS_T
  USE :: API_F_C_WRAPPER_MOD,        ONLY: F_C_WRAPPER_T
  USE :: API_F_C_WRAPPER_MOD,        ONLY: F_C_ALLOCATE_WRAPPER

  ! Symbols imported by the preprocessor for debugging purposes
  PP_DEBUG_USE_VARS

  ! Symbols imported by the preprocessor for logging purposes
  PP_LOG_USE_VARS

  ! Symbols imported by the preprocessor for tracing purposes
  PP_TRACE_USE_VARS

IMPLICIT NONE

  !> Dummy arguments
  TYPE(C_PTR),                              INTENT(INOUT) :: WRAPPED_ENCODER
  TYPE(MULTIOM_CACHED_ENCODERS_T), POINTER, INTENT(INOUT) :: ENCODER
  TYPE(HOOKS_T),                            INTENT(INOUT) :: HOOKS

  ! Function result
  INTEGER(KIND=JPIB_K) :: RET

  ! Local variables
  TYPE(CACHED_ENCODER_CONTAINER_T) :: ENCODER_CONTAINER
  TYPE(F_C_WRAPPER_T),    POINTER, DIMENSION(:) :: WRAPPER
  INTEGER(KIND=C_INT8_T), POINTER, DIMENSION(:) :: BUFFER
  INTEGER(KIND=JPIB_K) :: ALLOC_STAT
  CHARACTER(LEN=:), ALLOCATABLE :: ERRMSG

  !> Local prameters
  INTEGER(KIND=JPIB_K), PARAMETER :: CACHED_ENCODER_CONTAINER_BYTE_SIZE = &
&   STORAGE_SIZE(ENCODER_CONTAINER) / 8_JPIB_K

  ! Local error flags
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_WRAPPER_ALREADY_ASSOCIATED=1_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_ENCODER_ALREADY_ASSOCIATED=2_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_ALLOCATE_ENCODER=3_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_ALLOCATE_WRAPPER=4_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_WRAPPER_NOT_ASSOCIATED_AFTER_ALLOCATION=5_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_BUFFER_NOT_ASSOCIATED_AFTER_ALLOCATION=6_JPIB_K

  ! Local variables declared by the preprocessor for debugging purposes
  PP_DEBUG_DECL_VARS

  ! Local variables declared by the preprocessor for logging purposes
  PP_LOG_DECL_VARS

  ! Local variables declared by the preprocessor for tracing purposes
  PP_TRACE_DECL_VARS

  ! Trace begin of procedure
  PP_TRACE_ENTER_PROCEDURE()

  ! Initialization of good path return value
  PP_SET_ERR_SUCCESS( RET )

  ! Error handling
  PP_DEBUG_CRITICAL_COND_THROW( C_ASSOCIATED(WRAPPED_ENCODER), ERRFLAG_WRAPPER_ALREADY_ASSOCIATED)
  PP_DEBUG_CRITICAL_COND_THROW( ASSOCIATED(ENCODER), ERRFLAG_ENCODER_ALREADY_ASSOCIATED)

  ! Allocate the encoder
  ALLOCATE( ENCODER_CONTAINER%ENCODER, STAT=ALLOC_STAT, ERRMSG=ERRMSG )
  PP_DEBUG_CRITICAL_COND_THROW( ALLOC_STAT .NE. 0_JPIB_K, ERRFLAG_UNABLE_TO_ALLOCATE_ENCODER )

  ! Allocate the wrapper
  WRAPPER => NULL()
  BUFFER => NULL()
  PP_TRYCALL(ERRFLAG_UNABLE_TO_ALLOCATE_WRAPPER) F_C_ALLOCATE_WRAPPER( &
&   WRAPPER, BUFFER, CACHED_MAPPED_ENCODER_IDX_E, CACHED_ENCODER_CONTAINER_BYTE_SIZE, HOOKS )

  ! Error handling
  PP_DEBUG_CRITICAL_COND_THROW( .NOT.ASSOCIATED(WRAPPER), ERRFLAG_WRAPPER_NOT_ASSOCIATED_AFTER_ALLOCATION)
  PP_DEBUG_CRITICAL_COND_THROW( .NOT.ASSOCIATED(BUFFER), ERRFLAG_BUFFER_NOT_ASSOCIATED_AFTER_ALLOCATION)

  ! Wrap the encoder in order to be able to expose it to c
  BUFFER = TRANSFER(ENCODER_CONTAINER, BUFFER, CACHED_ENCODER_CONTAINER_BYTE_SIZE )

  ! Set the return arguments
  ENCODER => ENCODER_CONTAINER%ENCODER
  WRAPPED_ENCODER = C_LOC(WRAPPER)

  ! Trace end of procedure (on success)
  PP_TRACE_EXIT_PROCEDURE_ON_SUCCESS()

  ! Exit point (On success)
  RETURN

! Error handler
PP_ERROR_HANDLER

  ! Initialization of bad path return value
  PP_SET_ERR_FAILURE( RET )

#if defined( PP_DEBUG_ENABLE_ERROR_HANDLING )
!$omp critical(ERROR_HANDLER)

  BLOCK

    ! Error handling variables
    PP_DEBUG_PUSH_FRAME()

    ! Handle different errors
    SELECT CASE(ERRIDX)
    CASE (ERRFLAG_WRAPPER_ALREADY_ASSOCIATED)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Wrapper already associated' )
    CASE (ERRFLAG_ENCODER_ALREADY_ASSOCIATED)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Encoder already associated' )
    CASE (ERRFLAG_UNABLE_TO_ALLOCATE_ENCODER)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Unable to allocate encoder' )
      IF ( ALLOCATED(ERRMSG) ) THEN
        PP_DEBUG_PUSH_MSG_TO_FRAME( 'Error message: ' // TRIM(ERRMSG) )
        DEALLOCATE( ERRMSG, STAT=ALLOC_STAT )
      END IF
    CASE (ERRFLAG_UNABLE_TO_ALLOCATE_WRAPPER)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Unable to allocate wrapper' )
    CASE (ERRFLAG_WRAPPER_NOT_ASSOCIATED_AFTER_ALLOCATION)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Wrapper not associated after allocation' )
    CASE (ERRFLAG_BUFFER_NOT_ASSOCIATED_AFTER_ALLOCATION)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Buffer not associated after allocation' )
    CASE DEFAULT
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'unhandled error' )
    END SELECT

    ! Trace end of procedure (on error)
    PP_TRACE_EXIT_PROCEDURE_ON_ERROR()

    ! Write the error message and stop the program
    PP_DEBUG_ABORT

  END BLOCK

!$omp end critical(ERROR_HANDLER)
#endif

  ! Exit point (on error)
  RETURN

END FUNCTION CREATE_CACHED_MAPPED_ENCODER
#undef PP_PROCEDURE_NAME
#undef PP_PROCEDURE_TYPE


#define PP_PROCEDURE_TYPE 'FUNCTION'
#define PP_PROCEDURE_NAME 'EXTRACT_CACHED_MAPPED_ENCODER'
PP_THREAD_SAFE FUNCTION EXTRACT_CACHED_MAPPED_ENCODER( WRAPPED_ENCODER, ENCODER, HOOKS ) RESULT(RET)

  !> Symbols imported from intrinsic modules.
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_PTR
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_INT8_T
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_ASSOCIATED
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_F_POINTER

  ! Symbols imported from other modules within the project.
  USE :: DATAKINDS_DEF_MOD,          ONLY: JPIB_K
  USE :: HOOKS_MOD,                  ONLY: HOOKS_T
  USE :: MULTIOM_CACHED_ENCODER_MOD, ONLY: MULTIOM_CACHED_ENCODERS_T
  USE :: API_F_C_WRAPPER_MOD,        ONLY: F_C_WRAPPER_T
  USE :: API_F_C_WRAPPER_MOD,        ONLY: F_C_EXTRACT_WRAPPER

  ! Symbols imported by the preprocessor for debugging purposes
  PP_DEBUG_USE_VARS

  ! Symbols imported by the preprocessor for logging purposes
  PP_LOG_USE_VARS

  ! Symbols imported by the preprocessor for tracing purposes
  PP_TRACE_USE_VARS

IMPLICIT NONE

  !> Dummy arguments
  TYPE(C_PTR),                              INTENT(IN)    :: WRAPPED_ENCODER
  TYPE(MULTIOM_CACHED_ENCODERS_T), POINTER, INTENT(INOUT) :: ENCODER
  TYPE(HOOKS_T),                            INTENT(INOUT) :: HOOKS

  !> Function result
  INTEGER(KIND=JPIB_K) :: RET

  ! Local variables
  TYPE(F_C_WRAPPER_T),    POINTER, DIMENSION(:) :: WRAPPER
  INTEGER(KIND=C_INT8_T), POINTER, DIMENSION(:) :: BUFFER
  TYPE(CACHED_ENCODER_CONTAINER_T) :: ENCODER_CONTAINER
  INTEGER(KIND=JPIB_K) :: DIM

  !> Local prameters
  INTEGER(KIND=JPIB_K), PARAMETER :: CACHED_ENCODER_CONTAINER_BYTE_SIZE = &
&   STORAGE_SIZE(ENCODER_CONTAINER) / 8_JPIB_K

  !> Local error flags
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_WRAPPER_NOT_ASSOCIATED=1_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_ENCODER_ALREADY_ASSOCIATED=2_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_EXTRACT_WRAPPER=3_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_EXTRACT_BUFFER=4_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_BUFFER_NOT_ASSOCIATED=5_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_WRONG_BUFFER_SIZE=6_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_ENCODER_NOT_ASSOCIATED=7_JPIB_K

  ! Local variables declared by the preprocessor for debugging purposes
  PP_DEBUG_DECL_VARS

  ! Local variables declared by the preprocessor for logging purposes
  PP_LOG_DECL_VARS

  ! Local variables declared by the preprocessor for tracing purposes
  PP_TRACE_DECL_VARS

  ! Trace begin of procedure
  PP_TRACE_ENTER_PROCEDURE()

  ! Initialization of good path return value
  PP_SET_ERR_SUCCESS( RET )

  ! Error handling
  PP_DEBUG_CRITICAL_COND_THROW( .NOT.C_ASSOCIATED(WRAPPED_ENCODER), ERRFLAG_WRAPPER_NOT_ASSOCIATED )
  PP_DEBUG_CRITICAL_COND_THROW( ASSOCIATED(ENCODER), ERRFLAG_ENCODER_ALREADY_ASSOCIATED )

  ! Extract the wrapper
  WRAPPER => NULL()
  CALL C_F_POINTER( WRAPPED_ENCODER, WRAPPER )
  PP_DEBUG_CRITICAL_COND_THROW( .NOT.ASSOCIATED(WRAPPER), ERRFLAG_UNABLE_TO_EXTRACT_WRAPPER )

  ! Extract the buffer
  BUFFER => NULL()
  DIM = 0_JPIB_K
  PP_TRYCALL(ERRFLAG_UNABLE_TO_EXTRACT_BUFFER) F_C_EXTRACT_WRAPPER( &
&   WRAPPER, BUFFER, DIM, HOOKS )

  ! Error handling
  PP_DEBUG_CRITICAL_COND_THROW( .NOT.ASSOCIATED(BUFFER), ERRFLAG_BUFFER_NOT_ASSOCIATED )
  PP_DEBUG_CRITICAL_COND_THROW( DIM .NE. CACHED_ENCODER_CONTAINER_BYTE_SIZE, ERRFLAG_WRONG_BUFFER_SIZE )

  ! Get the Container
  ENCODER_CONTAINER = TRANSFER( BUFFER, ENCODER_CONTAINER )
  PP_DEBUG_CRITICAL_COND_THROW( .NOT.ASSOCIATED(ENCODER_CONTAINER%ENCODER), ERRFLAG_ENCODER_NOT_ASSOCIATED )

  ! Associate the encoder pointer
  ENCODER => ENCODER_CONTAINER%ENCODER

  ! Trace end of procedure (on success)
  PP_TRACE_EXIT_PROCEDURE_ON_SUCCESS()

  ! Exit point (On success)
  RETURN

! Error handler
PP_ERROR_HANDLER

  ! Initialization of bad path return value
  PP_SET_ERR_FAILURE( RET )

#if defined( PP_DEBUG_ENABLE_ERROR_HANDLING )
!$omp critical(ERROR_HANDLER)

  BLOCK

    ! Error handling variables
    PP_DEBUG_PUSH_FRAME()

    SELECT CASE(ERRIDX)
    CASE (ERRFLAG_WRAPPER_NOT_ASSOCIATED)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Wrapper not associated' )
    CASE (ERRFLAG_ENCODER_ALREADY_ASSOCIATED)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Encoder already associated' )
    CASE (ERRFLAG_UNABLE_TO_EXTRACT_WRAPPER)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Unable to extract wrapper' )
    CASE (ERRFLAG_UNABLE_TO_EXTRACT_BUFFER)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Unable to extract buffer' )
    CASE (ERRFLAG_BUFFER_NOT_ASSOCIATED)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Buffer not associated' )
    CASE (ERRFLAG_WRONG_BUFFER_SIZE)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Wrong buffer size' )
    CASE (ERRFLAG_ENCODER_NOT_ASSOCIATED)
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Encoder not associated' )
    CASE DEFAULT
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Unknown error' )
    END SELECT

    ! Trace end of procedure (on error)
    PP_TRACE_EXIT_PROCEDURE_ON_ERROR()

    ! Write the error message and stop the program
    PP_DEBUG_ABORT

  END BLOCK

!$omp end critical(ERROR_HANDLER)
#endif

  RETURN

END FUNCTION EXTRACT_CACHED_MAPPED_ENCODER
#undef PP_PROCEDURE_NAME
#undef PP_PROCEDURE_TYPE




#define PP_PROCEDURE_TYPE 'FUNCTION'
#define PP_PROCEDURE_NAME 'FREE_CACHED_MAPPED_ENCODER'
PP_THREAD_SAFE FUNCTION FREE_CACHED_MAPPED_ENCODER( WRAPPED_ENCODER, HOOKS ) RESULT(RET)

  !> Symbols imported from intrinsic modules.
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_PTR
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_INT8_T
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_ASSOCIATED
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_F_POINTER
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_NULL_PTR

  ! Symbols imported from other modules within the project.
  USE :: DATAKINDS_DEF_MOD,          ONLY: JPIB_K
  USE :: HOOKS_MOD,                  ONLY: HOOKS_T
  USE :: MULTIOM_CACHED_ENCODER_MOD, ONLY: MULTIOM_CACHED_ENCODERS_T
  USE :: API_F_C_WRAPPER_MOD,        ONLY: F_C_WRAPPER_T
  USE :: API_F_C_WRAPPER_MOD,        ONLY: F_C_EXTRACT_WRAPPER
  USE :: API_F_C_WRAPPER_MOD,        ONLY: F_C_FREE_WRAPPER

  ! Symbols imported by the preprocessor for debugging purposes
  PP_DEBUG_USE_VARS

  ! Symbols imported by the preprocessor for logging purposes
  PP_LOG_USE_VARS

  ! Symbols imported by the preprocessor for tracing purposes
  PP_TRACE_USE_VARS

IMPLICIT NONE

  !> Dummy arguments
  TYPE(C_PTR),   INTENT(INOUT) :: WRAPPED_ENCODER
  TYPE(HOOKS_T), INTENT(INOUT) :: HOOKS

  !> Function result
  INTEGER(KIND=JPIB_K) :: RET

  ! Local variables
  TYPE(F_C_WRAPPER_T), POINTER, DIMENSION(:) :: WRAPPER
  INTEGER(KIND=C_INT8_T), POINTER, DIMENSION(:) :: BUFFER
  TYPE(MULTIOM_CACHED_ENCODERS_T), POINTER :: ENCODER
  TYPE(CACHED_ENCODER_CONTAINER_T) :: ENCODER_CONTAINER
  INTEGER(KIND=JPIB_K) :: DIM
  INTEGER(KIND=JPIB_K) :: ALLOC_STAT
  CHARACTER(LEN=:), ALLOCATABLE :: ERRMSG

  !> Local prameters
  INTEGER(KIND=JPIB_K), PARAMETER :: CACHED_ENCODER_CONTAINER_BYTE_SIZE = &
&   STORAGE_SIZE(ENCODER_CONTAINER) / 8_JPIB_K

  !> Local error flags
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_WRAPPER_NOT_ASSOCIATED=1_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_EXTRACT_ENCODER=2_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_EXTRACT_WRAPPER=3_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_EXTRACT_BUFFER=4_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_BUFFER_NOT_ASSOCIATED=5_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_WRONG_BUFFER_SIZE=6_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_ENCODER_NOT_ASSOCIATED=7_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_FREE_ENCODER=8_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_DEALLOCATE_ENCODER=9_JPIB_K
  INTEGER(KIND=JPIB_K), PARAMETER :: ERRFLAG_UNABLE_TO_FREE_WRAPPER=10_JPIB_K

  ! Local variables declared by the preprocessor for debugging purposes
  PP_DEBUG_DECL_VARS

  ! Local variables declared by the preprocessor for logging purposes
  PP_LOG_DECL_VARS

  ! Local variables declared by the preprocessor for tracing purposes
  PP_TRACE_DECL_VARS

  ! Trace begin of procedure
  PP_TRACE_ENTER_PROCEDURE()

  ! Initialization of good path return value
  PP_SET_ERR_SUCCESS( RET )

  ! Error handling
  PP_DEBUG_CRITICAL_COND_THROW( .NOT.C_ASSOCIATED(WRAPPED_ENCODER), ERRFLAG_WRAPPER_NOT_ASSOCIATED )

  ! Extract the wrapper
  WRAPPER => NULL()
  CALL C_F_POINTER( WRAPPED_ENCODER, WRAPPER, [1] )
  PP_DEBUG_CRITICAL_COND_THROW( .NOT.ASSOCIATED(WRAPPER), ERRFLAG_UNABLE_TO_EXTRACT_WRAPPER )

  ! Extract the buffer
  BUFFER => NULL()
  DIM = 0_JPIB_K
  PP_TRYCALL(ERRFLAG_UNABLE_TO_EXTRACT_BUFFER) F_C_EXTRACT_WRAPPER( &
&   WRAPPER, BUFFER, DIM, HOOKS )

  ! Error handling
  PP_DEBUG_CRITICAL_COND_THROW( .NOT.ASSOCIATED(BUFFER), ERRFLAG_BUFFER_NOT_ASSOCIATED )
  PP_DEBUG_CRITICAL_COND_THROW( DIM .NE. CACHED_ENCODER_CONTAINER_BYTE_SIZE, ERRFLAG_WRONG_BUFFER_SIZE )

  ! Get the Container
  ENCODER_CONTAINER = TRANSFER( BUFFER, ENCODER_CONTAINER )
  PP_DEBUG_CRITICAL_COND_THROW( .NOT.ASSOCIATED(ENCODER_CONTAINER%ENCODER), ERRFLAG_ENCODER_NOT_ASSOCIATED )

  ! Associate the encoder pointer
  ENCODER => ENCODER_CONTAINER%ENCODER

  ! Free the encoder
  PP_TRYCALL(ERRFLAG_UNABLE_TO_FREE_ENCODER) ENCODER%FREE( HOOKS )

  ! Deallocate the encoder
  DEALLOCATE( ENCODER_CONTAINER%ENCODER, STAT=ALLOC_STAT, ERRMSG=ERRMSG )
  PP_DEBUG_CRITICAL_COND_THROW( ALLOC_STAT .NE. 0_JPIB_K, ERRFLAG_UNABLE_TO_DEALLOCATE_ENCODER )
  ENCODER_CONTAINER%ENCODER => NULL()
  ENCODER => NULL()

  ! Error handling
  BUFFER = 0_C_INT8_T

  ! Free the wrapper
  PP_TRYCALL(ERRFLAG_UNABLE_TO_FREE_WRAPPER) F_C_FREE_WRAPPER( &
&   WRAPPER, HOOKS )
  WRAPPER => NULL()
  BUFFER => NULL()

  ! Reset the c pointer
  WRAPPED_ENCODER = C_NULL_PTR

  ! Trace end of procedure (on success)
  PP_TRACE_EXIT_PROCEDURE_ON_SUCCESS()

  ! Exit point on success
  RETURN

! Error handler
PP_ERROR_HANDLER

  ! Initialization of bad path return value
  PP_SET_ERR_FAILURE( RET )

#if defined( PP_DEBUG_ENABLE_ERROR_HANDLING )
!$omp critical(ERROR_HANDLER)

  BLOCK

    ! Error handling variables
    PP_DEBUG_PUSH_FRAME()

    ! HAndle different errors
    SELECT CASE(ERRIDX)

    CASE DEFAULT
      PP_DEBUG_PUSH_MSG_TO_FRAME( 'Unhandled error' )
    END SELECT

    ! Trace end of procedure (on error)
    PP_TRACE_EXIT_PROCEDURE_ON_ERROR()

    ! Write the error message and stop the program
    PP_DEBUG_ABORT

  END BLOCK

!$omp end critical(ERROR_HANDLER)
#endif

  ! Exit point (on error)
  RETURN

END FUNCTION FREE_CACHED_MAPPED_ENCODER
#undef PP_PROCEDURE_NAME
#undef PP_PROCEDURE_TYPE

END MODULE CACHED_MAPPED_ENCODER_WRAPPER_MOD
#undef PP_SECTION_NAME
#undef PP_SECTION_TYPE
#undef PP_FILE_NAME