# (C) Copyright 2024- ECMWF.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.


name: Build Python Wrapper Wheel

on:
  # Trigger the workflow manually
  workflow_dispatch: ~

  # Allow to be called from another workflow -- currently from cd-pypi
  workflow_call: ~

jobs:
  # python-wrapper-wheel:
  #   name: Python Wrapper Wheel
  #   uses: ecmwf/reusable-workflows/.github/workflows/python-wrapper-wheel.yml@main
  #   with:
  #     wheel_directory: python/multiolib
  #   secrets: inherit
  multirelease-nightly:
    name: Multirelease Nightly
    runs-on: [self-hosted, Linux, platform-builder-Rocky-8.6]
    container:
      image: eccr.ecmwf.int/wheelmaker/2_28:multirelease
      options: --user github-actions
      credentials:
        username: ${{ secrets.ECMWF_DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.ECMWF_DOCKER_REGISTRY_ACCESS_TOKEN }}
    steps:
      - run: |
          /buildscripts/multirelease.sh 3.11 /venv/ prod "eckit eccodes atlas metkit fdb mir fckit multio odc"
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          TWINE_PASSWORD_PROD: ${{ secrets.PYPI_API_TOKEN }}
          TWINE_PASSWORD_TEST: ${{ secrets.PYPI_TEST_API_TOKEN }}

